{
  "hash": "168d6dc8d798c25ab23f23dcf763ff57",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 2\"\nauthor: \"yang yayong\"\ndate: \"May 21 2025\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  message: false\n  freeze: true\n  warning: FALSE\n  format: docx\n  editor: visual\n---\n\n\n\n\n# VAST Challenge 2024 Mini-Challenge 1\n\n# Overview\n\nIn this exercise, I will address **Question 1** and **Question 2** individually.\n\n1.  Design and develop visualizations and visual analytic tools that will allow Silas to explore and understand the profile of Sailor Shift’s career\n\n    1.  Who has she been most influenced by over time?\n\n    2.  Who has she collaborated with and directly or indirectly influenced?\n\n    3.  How has she influenced collaborators of the broader Oceanus Folk community?\n\n## Getting Started\n\nFor the purpose of this exercise, four R packages will be used. They are tidyverse, jsonlite, tidygraph and ggraph.\n\nIn the code chunk below, `p_load()` of **pacman** package is used to load the R packages into R environemnt.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, jsonlite,\n               tidygraph, ggraph,ggplot2,SmartEDA,igraph,visNetwork,DiagrammeR)\n```\n:::\n\n\n\n\n## Importing Kownledge Graph Data\n\nFor the purpose of this exercise, *MC1_graph.json* file will be used. Before getting started, you should have the data set in the **data** sub-folder.\n\nIn the code chunk below, `fromJSON()` of **jsonlite** package is used to import *MC1_graph.json* file into R and save the output object\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkg <- fromJSON(\"data/MC1_graph.json\")\n```\n:::\n\n\n\n\nWhat are the components of kg data?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(kg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi TRUE\n $ graph     :List of 2\n  ..$ node_default: Named list()\n  ..$ edge_default: Named list()\n $ nodes     :'data.frame':\t17412 obs. of  10 variables:\n  ..$ Node Type     : chr [1:17412] \"Song\" \"Person\" \"Person\" \"Person\" ...\n  ..$ name          : chr [1:17412] \"Breaking These Chains\" \"Carlos Duffy\" \"Min Qin\" \"Xiuying Xie\" ...\n  ..$ single        : logi [1:17412] TRUE NA NA NA NA FALSE ...\n  ..$ release_date  : chr [1:17412] \"2017\" NA NA NA ...\n  ..$ genre         : chr [1:17412] \"Oceanus Folk\" NA NA NA ...\n  ..$ notable       : logi [1:17412] TRUE NA NA NA NA TRUE ...\n  ..$ id            : int [1:17412] 0 1 2 3 4 5 6 7 8 9 ...\n  ..$ written_date  : chr [1:17412] NA NA NA NA ...\n  ..$ stage_name    : chr [1:17412] NA NA NA NA ...\n  ..$ notoriety_date: chr [1:17412] NA NA NA NA ...\n $ links     :'data.frame':\t37857 obs. of  4 variables:\n  ..$ Edge Type: chr [1:37857] \"InterpolatesFrom\" \"RecordedBy\" \"PerformerOf\" \"ComposerOf\" ...\n  ..$ source   : int [1:37857] 0 0 1 1 2 2 3 5 5 5 ...\n  ..$ target   : int [1:37857] 1841 4 0 16180 0 16180 0 5088 14332 11677 ...\n  ..$ key      : int [1:37857] 0 0 0 0 0 0 0 0 0 0 ...\n```\n\n\n:::\n:::\n\n\n\n\nThe result shows a typical **knowledge graph (KG)** data structure, the detail explanation is as followed:\n\n1.The overall structure is a list of 5 elements:\n\n| Element Name | Meaning |\n|------------------------------------|------------------------------------|\n| directed: TRUE | Indicates the graph is **directed** (i.e., relationships have direction, like “someone performed a song”) |\n| multigraph: TRUE | Indicates this is a **multigraph**, meaning multiple edges (relationships) can exist between the same pair of nodes (e.g., a person can be both “composer” and “performer”) |\n| graph | Contains default attributes for nodes and edges (currently empty named lists) |\n| nodes | A `data.frame`, each row represents a **node** (e.g., a person or a song) |\n| links | A `data.frame`, each row represents an **edge** (i.e., a relationship between two nodes) |\n\n2.`nodes` table (node metadata)\n\nThere are **17,412 nodes**, with the following variables:\n\n| Column Name    | Example / Meaning                               |\n|----------------|-------------------------------------------------|\n| Node Type      | Node type, such as `\"Song\"` or `\"Person\"`       |\n| name           | Name of the node (e.g., a person or song title) |\n| single         | Whether it is a single (TRUE / FALSE)           |\n| release_date   | Release date (e.g., `\"2017\"`)                   |\n| genre          | Genre (e.g., `\"Oceanus Folk\"`)                  |\n| notable        | Whether it's notable (TRUE / FALSE)             |\n| id             | Unique ID for the node                          |\n| written_date   | Date the song was written                       |\n| stage_name     | Stage name (if any)                             |\n| notoriety_date | Date the artist became known (if any)           |\n\n3.`links` table (edge/relationship information)\n\nThere are **37,857 edges**, with the following columns:\n\n| Column Name | Meaning / Example |\n|------------------------------------|------------------------------------|\n| Edge Type | Type of relationship (e.g., `\"PerformerOf\"`, `\"ComposerOf\"`, `\"InterpolateFrom\"`) |\n| source | ID of the source node |\n| target | ID of the target node |\n| key | Differentiates multiple edges between the same nodes |\n\n**Inspect structure**\n\nBefore preparing the data, it is always a good practice to examine the structure of *kg* object.\n\nIn the code chunk below `str()` is used to reveal the structure of *kg* object.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(kg, max.level = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi TRUE\n $ graph     :List of 2\n $ nodes     :'data.frame':\t17412 obs. of  10 variables:\n $ links     :'data.frame':\t37857 obs. of  4 variables:\n```\n\n\n:::\n:::\n\n\n\n\n## Extracting the edges and nodes tables\n\nNext, `as_tibble()` of **tibble** package package is used to **extract the nodes and links tibble data frames** from *kg* object into two separate tibble data frames called *nodes_tbl* and *edges_tbl* respectively.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- as_tibble(kg$nodes)\nedges_tbl <- as_tibble(kg$links) \n```\n:::\n\n\n\n\n### Initial EDA\n\nIt is time for us to apply appropriate EDA methods to examine the data.\n\nIn this code chunk below, ggplot2 functions are used the reveal the frequency distribution of *Edge Type* field of *edges_tbl*.\n\n::: panel-tabset\n## Nodes\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl %>%\n  count(`Node Type`) %>%\n  ggplot(aes(x = n, y = reorder(`Node Type`, n))) +\n  geom_col(fill = \"steelblue\") +\n  labs(title = \"Distribution of Node Types in Knowledge Graph\",\n       x = \"Count\", y = \"Node Type\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-6-1.png)\n:::\n:::\n\n\n\n\n**Most nodes are of type `Person`**\n\n-   **Explanation**: Individuals (singers, composers, producers, etc.) form the majority of nodes.\n\n-   **Insight**: The knowledge graph is **person-centric**, emphasizing individual contributions in the music ecosystem.\n\n**`Song` is the second most frequent node type**\n\n-   **Explanation**: Songs are heavily represented, as expected in a music-related knowledge graph.\n\n-   **Insight**: This reflects the graph’s role in **mapping who is connected to which songs**, enabling analysis of performance, authorship, and influence.\n\n**Other node types (e.g., `RecordLabel`, `Album`, `MusicalGroup`) are far fewer**\n\n-   **Explanation**: Entities like music labels, albums, and groups are present but much less prominent.\n\n-   **Insight**: These nodes play a **supporting role** in contextualizing the people-song relationships, potentially useful for advanced analyses (e.g., influence of labels, collaborations within groups).\n\n**`MusicalGroup` nodes are very rare**\n\n-   **Insight**: Either the graph focuses more on individual artists rather than bands/groups, or group membership data may be under-represented.\n\n## Edges\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_tbl %>%\n  count(`Edge Type`) %>%\n  ggplot(aes(x = n, y = reorder(`Edge Type`, n))) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(title = \"Edge Type Distribution in Knowledge Graph\",\n       x = \"Count\", y = \"Edge Type\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-7-1.png)\n:::\n:::\n\n\n\n\n### **\"PerformerOf\" is the most frequent edge type**\n\n-   **Explanation:** The majority of edges connect a **person** to a **song** via a performance relationship.\n\n-   **Insight:** This indicates that the relationship between performers and songs is a core structure in the knowledge graph, showing that the graph places a strong emphasis on **who performed what**.\n\n**\"RecordedBy\", \"ComposerOf\", and \"ProducerOf\" are also common**\n\n-   **Explanation:** Besides performers, the graph also documents many **creators** of the music, including **composers, producers**, and **recording personnel**.\n\n-   **Insight:** This suggests the graph goes beyond surface-level links, capturing multiple roles across the **music creation pipeline**.\n\n**Edge types like \"DirectlySamples\", \"CoverOf\", \"MemberOf\", and \"LyricalReferenceTo\" are less frequent**\n\n-   **Explanation:** These edges represent more complex or less common musical relationships, such as:\n\n-   **DirectlySamples**: relates to copyright and musical inspiration\n\n-   **CoverOf**: shows the propagation of classic works through cover versions\n\n-   **MemberOf**: describes group or band membership\n\n-   **Insight:** Although less common, these edge types may hold higher value in studying **musical influence** and **cultural transmission**.\n:::\n\nOn the other hands, code chunk below uses ggplot2 functions to reveal the frequency distribution of *Node Type* field of *nodes_tbl*.\n\n## Creating Knowledge Graph\n\n### Mapping from node id to row index\n\nBefore we can go ahead to build the tidygraph object, it is important for us to ensures each id from the node list is mapped to the correct row number. This requirement can be achive by using the code chunk below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_map <- tibble(id = nodes_tbl$id,  #Retrieve the ID column of each row node\n                 index = seq_len(\n                   nrow(nodes_tbl)))  #Generate a line number sequence from 1 to n\n```\n:::\n\n\n\n\n### Map source and target IDs to row indices\n\nNext, we will map the source and the target IDs to row indices by using the code chunk below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_tbl <- edges_tbl %>%\n  left_join(id_map, by = c(\"source\" = \"id\")) %>%  # source id → from index\n  rename(from = index) %>% \n  left_join(id_map, by = c(\"target\" = \"id\")) %>%  # target id → to index\n  rename(to = index)\n```\n:::\n\n\n\n\n::: callout-note\nTo better understand the changes before and after the process, it is to take a screenshot of *edges_tbl* before and after this process and examine the differences.\n:::\n\n![](images/clipboard-2426498860.png){width=\"351\"}\n\n![](images/clipboard-3714188848.png){width=\"351\"}\n\nNow we can see the difference between before and after the *edges_tbl.*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(edges_tbl$`Edge Type`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n        ComposerOf            CoverOf    DirectlySamples      DistributedBy \n              3290               1429                619               3013 \n         InStyleOf   InterpolatesFrom LyricalReferenceTo         LyricistOf \n              2289               1574               1496               2985 \n          MemberOf        PerformerOf         ProducerOf         RecordedBy \n               568              13587               3209               3798 \n```\n\n\n:::\n:::\n\n\n\n\n### Filter out any unmatched (invalid) edges\n\nLastly, the code chunk below will be used to exclude the unmatch edges.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_tbl <- edges_tbl %>%\n  filter(!is.na(from), !is.na(to))\n```\n:::\n\n\n\n\n### Creating tidygraph\n\nLastly, `tbl_graph()` is used to create tidygraph’s graph object by using the code chunk below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph <- tbl_graph(nodes = nodes_tbl, \n                   edges = edges_tbl, \n                   directed = kg$directed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tbl_graph: 17412 nodes and 37857 edges\n#\n# A directed multigraph with 16 components\n#\n# Node Data: 17,412 × 10 (active)\n   `Node Type` name         single release_date genre notable    id written_date\n   <chr>       <chr>        <lgl>  <chr>        <chr> <lgl>   <int> <chr>       \n 1 Song        Breaking Th… TRUE   2017         Ocea… TRUE        0 <NA>        \n 2 Person      Carlos Duffy NA     <NA>         <NA>  NA          1 <NA>        \n 3 Person      Min Qin      NA     <NA>         <NA>  NA          2 <NA>        \n 4 Person      Xiuying Xie  NA     <NA>         <NA>  NA          3 <NA>        \n 5 RecordLabel Nautical Mi… NA     <NA>         <NA>  NA          4 <NA>        \n 6 Song        Unshackled … FALSE  2026         Lo-F… TRUE        5 <NA>        \n 7 Person      Luke Payne   NA     <NA>         <NA>  NA          6 <NA>        \n 8 Person      Xiulan Zeng  NA     <NA>         <NA>  NA          7 <NA>        \n 9 Person      David Frank… NA     <NA>         <NA>  NA          8 <NA>        \n10 RecordLabel Colline-Cas… NA     <NA>         <NA>  NA          9 <NA>        \n# ℹ 17,402 more rows\n# ℹ 2 more variables: stage_name <chr>, notoriety_date <chr>\n#\n# Edge Data: 37,857 × 6\n   from    to `Edge Type`      source target   key\n  <int> <int> <chr>             <int>  <int> <int>\n1     1  1842 InterpolatesFrom      0   1841     0\n2     1     5 RecordedBy            0      4     0\n3     2     1 PerformerOf           1      0     0\n# ℹ 37,854 more rows\n```\n\n\n:::\n:::\n\n\n\n\nwe might want to confirm the output object is indeed in tidygraph format by using the code chunk below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(graph)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"tbl_graph\" \"igraph\"   \n```\n\n\n:::\n:::\n\n\n\n\n## Visualising the knowledge graph\n\nIn this section, we will use ggraph’s functions to visualise and analyse the graph object.\n\n::: callout-warning\nThe two examples below are not model answers, they are examples to show you how to use the mantra of **Overview first, details on demand** of visual investigation.\n:::\n\nSeveral of the ggraph layouts involve randomisation. In order to ensure reproducibility, it is necessary to set the seed value before plotting by using the code chunk below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\n\n\n### **Visualising the whole graph**\n\nIn the code chunk below, ggraph functions are used to visualise the whole graph.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggraph(graph, layout = \"fr\") +\n  geom_edge_link(alpha = 0.3, \n                 colour = \"gray\") +\n  geom_node_point(aes(color = `Node Type`), \n                  size = 4) +\n  geom_node_text(aes(label = name), \n                 repel = TRUE, \n                 size = 2.5) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-16-1.png)\n:::\n:::\n\n\n\n\nNotice that the whole graph is very messy and we can hardy discover any useful patterns. This is always the case in graph visualisation and analysis. In order to gain meaningful visual discovery, it is always useful for us to looking into the details, for example by plotting sub-graphs.\n\n### **Visualising the sub-graph**\n\nIn this section, we are interested to create a sub-graph base on *MemberOf* value in *Edge Type* column of the *edges* data frame.\n\n#### **Filtering edges to only “MemberOf”**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_memberof <- graph %>%\n  activate(edges) %>%   ##\n  filter(`Edge Type` == \"MemberOf\")\n```\n:::\n\n\n\n\n#### **Extracting only connected nodes (i.e., used in these edges)**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nused_node_indices <- graph_memberof %>%\n  activate(edges) %>%\n  as_tibble() %>%\n  select(from, to) %>%\n  unlist() %>%\n  unique()\n```\n:::\n\n\n\n\n#### **Keeping only those nodes**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_memberof <- graph_memberof %>%\n  activate(nodes) %>%\n  mutate(row_id = row_number()) %>%\n  filter(row_id %in% used_node_indices) %>%\n  select(-row_id)  # optional cleanup\n```\n:::\n\n\n\n\n#### **Plotting the sub-graph**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggraph(graph_memberof, \n       layout = \"fr\") +\n  geom_edge_link(alpha = 0.5, \n                 colour = \"gray\") +\n  geom_node_point(aes(color = `Node Type`), \n                  size = 1) +\n  geom_node_text(aes(label = name), \n                 repel = TRUE, \n                 size = 2.5) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-docx/unnamed-chunk-20-1.png)\n:::\n:::\n\n\n\n\nNotice that the sub-graph above is very clear and the relationship between musical group and person can be visualise easily.\n\n## Proceed to answer the questions for Mini-Challenge 1\n\nFirstly, I created an `extract_subnetwork` function to simplify the process of extracting network data. The methodology was referenced from a [senior's work.](https://isss608-kjcpaas.netlify.app/take-home_exs/ex3/take-home_ex3#mini-challenge-3) In this case, I will also add a `direction` parameter to allow for further filtering.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Extract_subnetwork \"}\nextract_subnetwork <- function(graph, node_name, \n                               distance = NULL, \n                               direction = c(\"all\", \"in\", \"out\"),\n                               edge_types = NULL,\n                               node_types = NULL) {\n  direction <- match.arg(direction)\n  node <- which(V(graph)$name == node_name)\n  if (length(node) == 0) stop(\"Node name not found in graph.\")\n  distance <- ifelse(is.null(distance), length(graph), distance)\n\n  mode <- switch(direction,\n                 all = \"all\",\n                 `in` = \"in\",\n                 out = \"out\")\n\n  igraph_subgraph <- induced_subgraph(graph, vids = ego(graph, node, order = distance, mode = mode)[[1]])\n\n  nodes_df <- igraph::as_data_frame(igraph_subgraph, what = \"vertices\")\n  edges_df <- igraph::as_data_frame(igraph_subgraph, what = \"edges\")\n\n  if (!is.null(edge_types)) {\n    edges_df <- edges_df %>% dplyr::filter(`Edge Type` %in% edge_types)\n  }\n\n  if (!is.null(node_types)) {\n    nodes_df <- nodes_df %>% dplyr::filter(`Node Type` %in% node_types)\n  }\n\n  used_node_ids <- unique(c(edges_df$from, edges_df$to))\n  nodes_df <- nodes_df %>% dplyr::filter(name %in% used_node_ids)\n\n  tidygraph::tbl_graph(nodes = nodes_df, edges = edges_df, directed = igraph::is_directed(graph))\n}\n```\n:::\n\n\n\n\n**Mini-Challenge 1 consists of three questions. Following a group discussion, I selected Question 1, and the steps I took to address the three sub-questions are described below.**\n\n1.  **Who has she been most influenced by over time?**\n\nTo address the first question, we considered both direct and indirect influences on Sailor Shift, as well as the temporal dynamics of these influences. The process was divided into three main steps:\n\n**1.1** Identify the individuals who directly influenced her.\\\n\n**1.2** Examine the works created by Sailor Shift, and trace any indirect influences on these works from others.\\\n\n**1.3** Apply a timeline to analyze how these influences evolved over time and observe any trends in their impact.\n\nSailor Shift \\<-- Person\n\nSailor Shift --\\> work \\<-- Person\n\nSailor Shift --\\> work_s \\<-- work_p \\<-- Person\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Who has she been most influenced by over time?\"}\ngrViz(\"\ndigraph complex_influence {\n  graph [layout = dot, rankdir = LR, splines = true]\n\n  node [fontname = Helvetica, style = filled, fillcolor = \\\"white\\\", shape = box]\n  edge [style = italic, fontname = Helvetica, fontsize = 12, labeldistance = 1.2, labelloc = c, color = gray30]\n\n\n  A   [label = 'Person A']\n  B   [label = 'Person B']\n  SS  [label = 'Sailor Shift', shape = ellipse, fillcolor = \\\"#fff7c0\\\"]\n  W   [label = 'Work s']\n  W1  [label = 'Work p']\n  WO  [label = 'Work o']  \n\n  A  -> SS  [label = 'influences']\n  SS -> W   [label = 'creates']\n  B  -> W1  [label = 'creates']\n  W1 -> W   [label = 'influences']\n  WO -> SS  [label = 'influences']  \n}\n\")\n```\n:::\n\n\n\n\n![](images/clipboard-3878243445.png)\n\n2.  **Who has she collaborated with and directly or indirectly influenced?**\n\nTo address the second question, we examined both direct and indirect influences involving Sailor Shift, placing her at the center of the analysis.The process was divided into three main steps:\n\n**2.1** Identify who she has collaborated with\n\nSailor Shift--\\>work \\<-- Person\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Who has she collaborated with and directly or indirectly influenced?\"}\ngrViz(\"\ndigraph sailor_collab {\n  graph [layout = dot, rankdir = LR]\n\n  node [fontname = Helvetica, style = filled, fillcolor = \\\"#ffffff\\\", shape = box,fontsize = 10, width = 0.5, height = 0.3]\n  edge [fontname = Helvetica, fontsize = 10, color = gray40]\n\n  Sailor [label = 'Sailor Shift', shape = ellipse, fillcolor = '#fff7c0']\n  Work   [label = 'Work', shape = box, fillcolor = '#e0f7fa']\n  Person [label = 'Collaborator', shape = ellipse]\n\n  Sailor -> Work [label = 'co-created']\n  Person -> Work [label = 'co-created']\n}\n\")\n```\n:::\n\n\n\n\n![](images/clipboard-42460967.png){width=\"696\"}\\\n**2.2** Determine who she has directly or indirectly influenced\n\nSailor Shift --\\> Person --\\> work (direct)\n\nSailor Shift--\\> work --\\> Person (indirect)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Determine who she has directly or indirectly influenced\"}\ngrViz(\"\ndigraph sailor_influence {\n  graph [layout = dot, rankdir = LR]\n\n  node [fontname = Helvetica, style = filled, fillcolor = \\\"#ffffff\\\", shape = box]\n  edge [fontname = Helvetica, fontsize = 11, labelfontsize = 11, color = gray40]\n\n  SS  [label = 'Sailor Shift', shape = ellipse, fillcolor = '#fff7c0']\n  P1  [label = 'Person\\n(direct)']\n  W1  [label = 'Work']\n  W2  [label = 'Work\\n(indirect)']\n  P2  [label = 'Person ']\n\n  SS -> P1 [label = 'influences']\n  P1 -> W1 [label = 'creates']\n\n  SS -> W2 [label = 'creates']\n  W2 -> P2 [label = 'influences']\n}\n\")\n```\n:::\n\n\n\n\n![](images/clipboard-2688711872.png)\n\n**3.How has she influenced collaborators of the broader Oceanus Folk community?**\n\nSailor Shift--\\> Person/community(Oceanus Folk) --\\> Work(Oceanus Folk)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"How has she influenced collaborators of the broader Oceanus Folk community?\"}\ngrViz(\"\ndigraph oceanus_influence {\n  graph [layout = dot, rankdir = LR]\n\n  node [fontname = Helvetica, style = filled, fillcolor = \\\"#ffffff\\\", shape = box, fontsize = 10]\n  edge [fontname = Helvetica, fontsize = 9, color = gray40]\n\n  Sailor   [label = 'Sailor Shift', shape = ellipse, fillcolor = '#fff7c0']\n  Community [label = 'Person/Community\\\\n(Oceanus Folk)', shape = ellipse]\n  Work     [label = 'Work\\\\n(Oceanus Folk)', shape = box, fillcolor = '#e0f7fa']\n\n  Sailor -> Community [label = 'influenced']\n  Community -> Work   [label = 'created']\n}\n\")\n```\n:::\n\n\n\n\n![](images/clipboard-3868416711.png)\n\n::: callout-caution\nIt is important to be especially careful with the direction of relationships such as **\"PerformerOf,\" \"ComposerOf,\" \"LyricistOf,\" \"ProducerOf,\"** as well as **\"DirectlySamples,\" \"InStyleOf,\" \"CoverOf,\" \"InterpolatesFrom,\"** and **\"LyricalReferenceTo.\"**\\\n\nSpecial attention must be paid to accurately identifying the **source** and **target** of each edge to preserve the correct semantic meaning.\n:::\n\n## Let’s begin.\n\n### **1.Who has she been most influenced by over time?**\n\nThe following is the thinking process:\n\nSailor Shift \\<-- Person\n\nSailor Shift--\\> work \\<-- Person\n\nSailor Shift--\\> work_s \\<-- work_p \\<-- Person\n\nFrom the initial (though imperfect) visNetwork visualization, we first examined what she had produced, and then proceeded to explore further connections.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"First examined what she had produced\"}\nsubgraph_in <- extract_subnetwork(\n  graph, \n  node_name = \"Sailor Shift\", \n  distance = 5, \n  direction = \"out\"\n)\n\nsubgraph_igraph <- as.igraph(subgraph_in)\n\nnodes_all <- igraph::as_data_frame(subgraph_igraph, what = \"vertices\")\nedges_all <- igraph::as_data_frame(subgraph_igraph, what = \"edges\")\n\nsailor_id <- nodes_all$name[nodes_all$name == \"Sailor Shift\"]\nedges_1st <- edges_all %>% filter(from == \"Sailor Shift\")\n\nvalid_targets <- edges_1st %>%\n  left_join(nodes_all, by = c(\"to\" = \"name\")) %>%\n  filter(`Node Type` %in% c(\"MusicalGroup\", \"Song\", \"Album\",\"RecordLabel\")) %>%\n  pull(to)\n\nvalid_node_ids <- unique(c(\"Sailor Shift\", valid_targets))\nedges_vn <- edges_all %>% \n  filter(from %in% valid_node_ids | to %in% valid_node_ids)\n\nused_nodes <- unique(c(edges_vn$from, edges_vn$to))\nnodes_vn <- nodes_all %>%\n  filter(name %in% used_nodes) %>%\n  mutate(id = name, label = name, group = `Node Type`)\n\nedges_vn <- edges_vn %>%\n  mutate(\n    label = `Edge Type`, \n    title = paste0(\"Edge Type: \", `Edge Type`)  \n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisNetwork(nodes_vn, edges_vn, height = \"800px\", width = \"100%\") %>%\n  visEdges(\n    arrows = \"to\",\n    font = list(\n      size = 12,         \n      align = \"middle\", \n      color = \"black\"    \n    )\n  ) %>%  \n  visOptions(\n    highlightNearest = list(enabled = TRUE, degree = 4, hover = TRUE),\n    nodesIdSelection = TRUE,\n    selectedBy = \"group\"\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 1234) %>%\n  visInteraction(navigationButtons = TRUE)\n```\n:::\n\n\n\n\n#### **First Layer** Exploration\n\nWe started with all nodes directly connected from Sailor Shift, and added the type information of each corresponding from-node.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_1st_full_named <- edges_1st %>%\n  left_join(nodes_all %>% select(name, `Node Type`) %>%\n              rename(from = name, `From Type` = `Node Type`), by = \"from\") %>%\n  \n  left_join(nodes_all %>% select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n              rename(to = name, `To Type` = `Node Type`, `To Release` = release_date,\n                     `To Genre` = genre, `To Notable` = notable, `To Notoriety Date` = notoriety_date),\n            by = \"to\") %>%\n  \n  select(from, `From Type`, to, `To Type`, `Edge Type`, `To Release`, `To Genre`, `To Notable`, `To Notoriety Date`)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(edges_1st_full_named)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to                                     |To Type      |Edge Type          |To Release |To Genre     |To Notable |To Notoriety Date |\n|:------------|:---------|:--------------------------------------|:------------|:------------------|:----------|:------------|:----------|:-----------------|\n|Sailor Shift |Person    |Neon Heartbeat                         |Album        |LyricistOf         |2031       |Synthwave    |FALSE      |NA                |\n|Sailor Shift |Person    |Ballads for the End of Time            |Album        |LyricistOf         |2033       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Melancholy Circuitry                   |Album        |LyricistOf         |2033       |Americana    |TRUE       |NA                |\n|Sailor Shift |Person    |Drifting Between the Stars and the Sea |Album        |LyricistOf         |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Artificial Sunsets                     |Album        |LyricistOf         |2035       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Electric Reverie                       |Album        |LyricistOf         |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Ballads for the Low Tide               |Album        |LyricistOf         |2037       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Fiddle & The Fjord                 |MusicalGroup |InStyleOf          |NA         |NA           |NA         |NA                |\n|Sailor Shift |Person    |Tides of Echos                         |Album        |LyricistOf         |2029       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Hidden Depths                          |Album        |LyricistOf         |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Ivy Echos                              |MusicalGroup |DirectlySamples    |NA         |NA           |NA         |NA                |\n|Sailor Shift |Person    |Ivy Echos                              |MusicalGroup |MemberOf           |NA         |NA           |NA         |NA                |\n|Sailor Shift |Person    |The Kelp Forest Canticles              |Album        |LyricistOf         |2024       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Luminescent Tides                      |Album        |LyricistOf         |2025       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Shoreline Sonnets                      |Album        |LyricistOf         |2026       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidal Pop Waves                        |Album        |LyricistOf         |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidal Pop Waves                        |Album        |PerformerOf        |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salty Dreams                           |Album        |LyricistOf         |2030       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salty Dreams                           |Album        |PerformerOf        |2030       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Current & The Chord                |Album        |LyricistOf         |2032       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Current & The Chord                |Album        |PerformerOf        |2032       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Coral Beats                            |Album        |LyricistOf         |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Coral Beats                            |Album        |PerformerOf        |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides & Ballads                        |Album        |LyricistOf         |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides & Ballads                        |Album        |PerformerOf        |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Oceanbound                             |Album        |LyricistOf         |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Oceanbound                             |Album        |PerformerOf        |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Echoes of the Deep                     |Album        |LyricistOf         |2040       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Echoes of the Deep                     |Album        |PerformerOf        |2040       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |High Tide Heartbeat                    |Song         |PerformerOf        |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Electric Eel Love                      |Song         |PerformerOf        |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Sun-Drenched Daydream                  |Song         |PerformerOf        |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Chord of the Deep                      |Song         |PerformerOf        |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Heart of the Habitat                   |Song         |PerformerOf        |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Reef Rhythm                            |Song         |PerformerOf        |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Driftwood Lullaby                      |Song         |PerformerOf        |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Saltwater Hymn                         |Song         |PerformerOf        |2032       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Moon Over the Tide                     |Song         |PerformerOf        |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Into the Current                       |Song         |PerformerOf        |2034       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Barnacle Heart                         |Song         |PerformerOf        |2034       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Fog & Fiddle                           |Song         |PerformerOf        |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Fisherman's Prayer                 |Song         |PerformerOf        |2036       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Stormsong                              |Song         |PerformerOf        |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salt in My Veins                       |Song         |PerformerOf        |2040       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |The Last Mariner                       |Song         |PerformerOf        |2040       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |The Saltwater Weavers                  |MusicalGroup |InStyleOf          |NA         |NA           |NA         |NA                |\n|Sailor Shift |Person    |Drowned Harbor                         |MusicalGroup |LyricalReferenceTo |NA         |NA           |NA         |NA                |\n|Sailor Shift |Person    |Tidesworn Ballads                      |Album        |PerformerOf        |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidesworn Ballads                      |Album        |LyricistOf         |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Submerged Sonatas                      |Album        |PerformerOf        |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Submerged Sonatas                      |Album        |LyricistOf         |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Seashell Serenade                      |Song         |PerformerOf        |2030       |Oceanus Folk |TRUE       |2030              |\n\n\n:::\n:::\n\n\n\n\nBelow is all the information on the **First** layer, and then remove if there is no other influenced layer\n\n::: panel-tabset\n## DirectlySamples \\#\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"DirectlySamples\")\n\nedges_selected <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% selected_types)\n\nknitr::kable(edges_selected)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to        |To Type      |Edge Type       |To Release |To Genre |To Notable |To Notoriety Date |\n|:------------|:---------|:---------|:------------|:---------------|:----------|:--------|:----------|:-----------------|\n|Sailor Shift |Person    |Ivy Echos |MusicalGroup |DirectlySamples |NA         |NA       |NA         |NA                |\n\n\n:::\n:::\n\n\n\n\n## InStyleOf \\#\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"InStyleOf\")\n\nedges_selected <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% selected_types)\n\nknitr::kable(edges_selected)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to                     |To Type      |Edge Type |To Release |To Genre |To Notable |To Notoriety Date |\n|:------------|:---------|:----------------------|:------------|:---------|:----------|:--------|:----------|:-----------------|\n|Sailor Shift |Person    |The Fiddle & The Fjord |MusicalGroup |InStyleOf |NA         |NA       |NA         |NA                |\n|Sailor Shift |Person    |The Saltwater Weavers  |MusicalGroup |InStyleOf |NA         |NA       |NA         |NA                |\n\n\n:::\n:::\n\n\n\n\n## LyricalReferenceTo \\#\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"LyricalReferenceTo\")\n\nedges_selected_LyricalReferenceTo <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% selected_types)\n\nknitr::kable(edges_selected_LyricalReferenceTo)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to             |To Type      |Edge Type          |To Release |To Genre |To Notable |To Notoriety Date |\n|:------------|:---------|:--------------|:------------|:------------------|:----------|:--------|:----------|:-----------------|\n|Sailor Shift |Person    |Drowned Harbor |MusicalGroup |LyricalReferenceTo |NA         |NA       |NA         |NA                |\n\n\n:::\n:::\n\n\n\n\n## LyricistOf\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"LyricistOf\")\n\nedges_selected <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% selected_types)\n\nknitr::kable(edges_selected)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to                                     |To Type |Edge Type  |To Release |To Genre     |To Notable |To Notoriety Date |\n|:------------|:---------|:--------------------------------------|:-------|:----------|:----------|:------------|:----------|:-----------------|\n|Sailor Shift |Person    |Neon Heartbeat                         |Album   |LyricistOf |2031       |Synthwave    |FALSE      |NA                |\n|Sailor Shift |Person    |Ballads for the End of Time            |Album   |LyricistOf |2033       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Melancholy Circuitry                   |Album   |LyricistOf |2033       |Americana    |TRUE       |NA                |\n|Sailor Shift |Person    |Drifting Between the Stars and the Sea |Album   |LyricistOf |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Artificial Sunsets                     |Album   |LyricistOf |2035       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Electric Reverie                       |Album   |LyricistOf |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Ballads for the Low Tide               |Album   |LyricistOf |2037       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides of Echos                         |Album   |LyricistOf |2029       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Hidden Depths                          |Album   |LyricistOf |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Kelp Forest Canticles              |Album   |LyricistOf |2024       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Luminescent Tides                      |Album   |LyricistOf |2025       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Shoreline Sonnets                      |Album   |LyricistOf |2026       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidal Pop Waves                        |Album   |LyricistOf |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salty Dreams                           |Album   |LyricistOf |2030       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Current & The Chord                |Album   |LyricistOf |2032       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Coral Beats                            |Album   |LyricistOf |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides & Ballads                        |Album   |LyricistOf |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Oceanbound                             |Album   |LyricistOf |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Echoes of the Deep                     |Album   |LyricistOf |2040       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidesworn Ballads                      |Album   |LyricistOf |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Submerged Sonatas                      |Album   |LyricistOf |2031       |Oceanus Folk |TRUE       |NA                |\n\n\n:::\n:::\n\n\n\n\n## MemberOf \\#\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"MemberOf\")\n\nedges_selected <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% selected_types)\n\nknitr::kable(edges_selected)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to        |To Type      |Edge Type |To Release |To Genre |To Notable |To Notoriety Date |\n|:------------|:---------|:---------|:------------|:---------|:----------|:--------|:----------|:-----------------|\n|Sailor Shift |Person    |Ivy Echos |MusicalGroup |MemberOf  |NA         |NA       |NA         |NA                |\n\n\n:::\n:::\n\n\n\n\n## PerformerOf\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"PerformerOf\")\n\nedges_selected <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% selected_types)\n\nknitr::kable(edges_selected)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to                      |To Type |Edge Type   |To Release |To Genre     |To Notable |To Notoriety Date |\n|:------------|:---------|:-----------------------|:-------|:-----------|:----------|:------------|:----------|:-----------------|\n|Sailor Shift |Person    |Tidal Pop Waves         |Album   |PerformerOf |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salty Dreams            |Album   |PerformerOf |2030       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Current & The Chord |Album   |PerformerOf |2032       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Coral Beats             |Album   |PerformerOf |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides & Ballads         |Album   |PerformerOf |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Oceanbound              |Album   |PerformerOf |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Echoes of the Deep      |Album   |PerformerOf |2040       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |High Tide Heartbeat     |Song    |PerformerOf |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Electric Eel Love       |Song    |PerformerOf |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Sun-Drenched Daydream   |Song    |PerformerOf |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Chord of the Deep       |Song    |PerformerOf |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Heart of the Habitat    |Song    |PerformerOf |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Reef Rhythm             |Song    |PerformerOf |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Driftwood Lullaby       |Song    |PerformerOf |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Saltwater Hymn          |Song    |PerformerOf |2032       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Moon Over the Tide      |Song    |PerformerOf |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Into the Current        |Song    |PerformerOf |2034       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Barnacle Heart          |Song    |PerformerOf |2034       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Fog & Fiddle            |Song    |PerformerOf |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Fisherman's Prayer  |Song    |PerformerOf |2036       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Stormsong               |Song    |PerformerOf |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salt in My Veins        |Song    |PerformerOf |2040       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |The Last Mariner        |Song    |PerformerOf |2040       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Tidesworn Ballads       |Album   |PerformerOf |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Submerged Sonatas       |Album   |PerformerOf |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Seashell Serenade       |Song    |PerformerOf |2030       |Oceanus Folk |TRUE       |2030              |\n\n\n:::\n:::\n\n\n\n:::\n\nThen we can visual all the connect from Sailor:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_1st_filtered <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% c(\"LyricistOf\", \"PerformerOf\", \"MemberOf\"))\n\nknitr::kable(edges_1st_filtered)\n```\n\n::: {.cell-output-display}\n\n\n|from         |From Type |to                                     |To Type      |Edge Type   |To Release |To Genre     |To Notable |To Notoriety Date |\n|:------------|:---------|:--------------------------------------|:------------|:-----------|:----------|:------------|:----------|:-----------------|\n|Sailor Shift |Person    |Neon Heartbeat                         |Album        |LyricistOf  |2031       |Synthwave    |FALSE      |NA                |\n|Sailor Shift |Person    |Ballads for the End of Time            |Album        |LyricistOf  |2033       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Melancholy Circuitry                   |Album        |LyricistOf  |2033       |Americana    |TRUE       |NA                |\n|Sailor Shift |Person    |Drifting Between the Stars and the Sea |Album        |LyricistOf  |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Artificial Sunsets                     |Album        |LyricistOf  |2035       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Electric Reverie                       |Album        |LyricistOf  |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Ballads for the Low Tide               |Album        |LyricistOf  |2037       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides of Echos                         |Album        |LyricistOf  |2029       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Hidden Depths                          |Album        |LyricistOf  |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Ivy Echos                              |MusicalGroup |MemberOf    |NA         |NA           |NA         |NA                |\n|Sailor Shift |Person    |The Kelp Forest Canticles              |Album        |LyricistOf  |2024       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Luminescent Tides                      |Album        |LyricistOf  |2025       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Shoreline Sonnets                      |Album        |LyricistOf  |2026       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidal Pop Waves                        |Album        |LyricistOf  |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidal Pop Waves                        |Album        |PerformerOf |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salty Dreams                           |Album        |LyricistOf  |2030       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salty Dreams                           |Album        |PerformerOf |2030       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Current & The Chord                |Album        |LyricistOf  |2032       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Current & The Chord                |Album        |PerformerOf |2032       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Coral Beats                            |Album        |LyricistOf  |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Coral Beats                            |Album        |PerformerOf |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides & Ballads                        |Album        |LyricistOf  |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tides & Ballads                        |Album        |PerformerOf |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Oceanbound                             |Album        |LyricistOf  |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Oceanbound                             |Album        |PerformerOf |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Echoes of the Deep                     |Album        |LyricistOf  |2040       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Echoes of the Deep                     |Album        |PerformerOf |2040       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |High Tide Heartbeat                    |Song         |PerformerOf |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Electric Eel Love                      |Song         |PerformerOf |2028       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Sun-Drenched Daydream                  |Song         |PerformerOf |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Chord of the Deep                      |Song         |PerformerOf |2028       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Heart of the Habitat                   |Song         |PerformerOf |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Reef Rhythm                            |Song         |PerformerOf |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Driftwood Lullaby                      |Song         |PerformerOf |2030       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Saltwater Hymn                         |Song         |PerformerOf |2032       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Moon Over the Tide                     |Song         |PerformerOf |2034       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Into the Current                       |Song         |PerformerOf |2034       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Barnacle Heart                         |Song         |PerformerOf |2034       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Fog & Fiddle                           |Song         |PerformerOf |2036       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |The Fisherman's Prayer                 |Song         |PerformerOf |2036       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Stormsong                              |Song         |PerformerOf |2038       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Salt in My Veins                       |Song         |PerformerOf |2040       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |The Last Mariner                       |Song         |PerformerOf |2040       |Oceanus Folk |FALSE      |NA                |\n|Sailor Shift |Person    |Tidesworn Ballads                      |Album        |PerformerOf |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Tidesworn Ballads                      |Album        |LyricistOf  |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Submerged Sonatas                      |Album        |PerformerOf |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Submerged Sonatas                      |Album        |LyricistOf  |2031       |Oceanus Folk |TRUE       |NA                |\n|Sailor Shift |Person    |Seashell Serenade                      |Song         |PerformerOf |2030       |Oceanus Folk |TRUE       |2030              |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"All the connect from Sailor-Song & Album & Group\"}\nedge_colors <- c(\n  \"PerformerOf\"         = \"#2ca02c\",\n\n  \"LyricistOf\"          = \"#1f77b4\",\n \n \n  \"MemberOf\"            = \"#d62728\"\n)\n\nnodes_subgraph <- nodes_all %>%\n  filter(name %in% c(\"Sailor Shift\", edges_1st_filtered$to)) %>%\n  transmute(id = name, label = name, group = `Node Type`)\n\nedges_subgraph <- edges_1st_filtered %>%\n  left_join(\n    nodes_all %>% select(name, `Node Type`) %>% rename(to = name, to_type = `Node Type`),\n    by = \"to\"\n  ) %>%\n  mutate(\n    color = edge_colors[`Edge Type`],\n    title = paste0(\"Edge Type: \", `Edge Type`, \"<br>To Type: \", to_type)\n  ) %>%\n  transmute(\n    from = from,\n    to = to,\n    title = title,\n    color = color,\n    arrows = \"to\"\n  )\n\nedge_legend <- data.frame(\n  label = names(edge_colors),\n  color = unname(edge_colors),\n  arrows = rep(\"to\", length(edge_colors)),\n  stringsAsFactors = FALSE\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisNetwork(nodes_subgraph, edges_subgraph, width = \"100%\", height = \"700px\") %>%\n  visEdges(smooth = TRUE) %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%\n  visLegend(\n    addEdges = edge_legend,\n    useGroups = TRUE,\n    position = \"right\",\n  ) %>%\n  visPhysics(\n    solver = \"forceAtlas2Based\",\n    forceAtlas2Based = list(gravitationalConstant = -80),\n    stabilization = list(enabled = TRUE, iterations = 100)\n  ) %>%\n  visLayout(randomSeed = 123)\n```\n:::\n\n\n\n\n::: callout-note\n## What we can find from the network？\n\n**She is a highly prolific creator**\n\n-   The dense number of outgoing edges indicates that Sailor Shift has contributed to or performed a large number of works, including both songs and albums.\n\n-   The number of connected nodes shows she is linked to over 20 works, placing her at the center of the network.\n\n**She plays both performer and lyricist roles**\n\nThe presence of many green edges (PerformerOf) and blue edges (LyricistOf) suggests:\n\n-   She not only performs but also writes lyrics for her works.\n\n-   She plays a dual role in the music creation process, showing versatility as both a performer and a songwriter.\n\n**She is not an entirely solo artist**\n\nA red edge (MemberOf) connects her to the red node `Ivy Echos`, indicating:\n\n-   She is a member of this musical group.\n\n-   Some of her creative output may result from group collaboration.\n\n-   She maintains a balance between solo and group work.\n\nSailor Shift is a central figure,skilled in both songwriting and performance, and active in both solo and collaborative projects. Her work likely forms a key part of the community's creative landscape.\n:::\n\n#### Third Layer Exploration\n\nNext, we aim to explore other’s relationship with Ivy Echos.”\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nivy_groups <- edges_all %>%\n  filter(to == \"Ivy Echos\", `Edge Type` == \"MemberOf\") %>%\n  pull(from)\nivy_groups\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Sailor Shift\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_members <- edges_all %>%\n  filter(`Edge Type` == \"MemberOf\", to %in% ivy_groups) %>%\n  select(from, to) %>%\n  rename(Member = from, Group = to)\n\nprint(group_members)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Member Group \n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n:::\n\n\n\n\nWe attempted to identify the *MemberOf* relationships for Ivy Echos, but the results suggest that this information is not included in the current dataset.”\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsailor_works <- edges_1st_full_named %>%\n  filter(`Edge Type` %in% c(\"ComposerOf\", \"PerformerOf\", \"LyricistOf\", \"ProducerOf\",\"MemberOf\"),\n         `To Type` %in% c(\"Song\", \"Album\",\"MusicalGroup\",\"Person\",\"RecordLabel\")) %>%\n  pull(to) %>%\n  unique()\n\nedges_others <- edges_all %>%\n  filter(\n    to %in% sailor_works,\n    `Edge Type` %in% c(\"ComposerOf\", \"PerformerOf\", \"LyricistOf\", \"ProducerOf\"),\n    from != \"Sailor Shift\"  \n  )\n\nedges_others_full <- edges_others %>%\n  left_join(nodes_all, by = c(\"from\" = \"name\")) %>%\n  rename(Participant = from, ParticipantType = `Node Type`) %>%\n  select(Participant, ParticipantType, to, `Edge Type`)\n\nknitr::kable(edges_others_full)\n```\n\n::: {.cell-output-display}\n\n\n|Participant |ParticipantType |to                        |Edge Type   |\n|:-----------|:---------------|:-------------------------|:-----------|\n|Ivy Echos   |MusicalGroup    |The Kelp Forest Canticles |PerformerOf |\n|Ivy Echos   |MusicalGroup    |Luminescent Tides         |PerformerOf |\n|Ivy Echos   |MusicalGroup    |Shoreline Sonnets         |PerformerOf |\n\n\n:::\n:::\n\n\n\n\nFrom the result we can see, in this dataset,Ivy Echos has perform three songs.These will late add in the Folk Musci Group for further analysis.\n\nFor more convenient exploration, we selected the nodes connected to the third layer in order to observe indirect influences\n\nGet the complete information of the from node\n\nSailor Shift --(PerformerOf etc.)--\\> Song A --(InStyleOf etc.)--\\> Song B\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Get the complete information of the from node\"}\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\nsailor_index <- nodes_tbl %>%\n  filter(name == \"Sailor Shift\") %>%\n  pull(index)\n\nedges_from_sailor <- edges_tbl %>%\n  filter(from == sailor_index)\n\nfirst_layer_info <- edges_from_sailor %>%\n  inner_join(nodes_tbl, by = c(\"to\" = \"index\")) %>%\n  filter(`Node Type` %in% c(\"Song\", \"Album\", \"MusicalGroup\", \"RecordLabel\"))\n\nfirst_layer_targets <- first_layer_info$to\n\ninfluence_edges <- c(\"InStyleOf\", \"LyricalReferenceTo\", \"InterpolatesFrom\", \"CoverOf\", \"DirectlySamples\")\n\nedges_2nd <- edges_tbl %>%\n  filter(from %in% first_layer_targets & `Edge Type` %in% influence_edges)\n```\n:::\n\n\n\n\nIn order to find more insights in one table, we have added the \"from\" information to the data frame\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Get the complete information of the from node\"}\nedges_1st <- edges_all %>%\n  filter(from == \"Sailor Shift\")\n\nedges_1st_full <- edges_1st %>%\n  left_join(nodes_all, by = c(\"to\" = \"name\")) %>%\n  select(from, to, `Edge Type`, `Node Type`, release_date,genre,notable,notoriety_date)\n\nselected_types <- c(\"LyricistOf\", \"PerformerOf\")\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\n\ntarget_nodes <- unique(edges_selected$to)\n\nedges_2nd <- edges_all %>%\n  filter(from %in% target_nodes)\n\nfrom_info <- nodes_all %>%\n  select(name, `Node Type`) %>%\n  rename(from = name, `From Node Type` = `Node Type`)\n\nto_info <- nodes_all %>%\n  select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n  rename(\n    to = name,\n    `To Node Type` = `Node Type`,\n    to_release_date = release_date,\n    to_genre = genre,\n    to_notable = notable,\n    to_notoriety_date = notoriety_date\n  )\n\nedges_2nd_full <- edges_2nd %>%\n  left_join(from_info, by = \"from\") %>%\n  left_join(to_info, by = \"to\") %>%\n  select(\n    from, `From Node Type`, to, `To Node Type`, `Edge Type`,\n    to_release_date, to_genre, to_notable, to_notoriety_date\n  )\n\n\nknitr::kable(edges_2nd_full)\n```\n\n::: {.cell-output-display}\n\n\n|from                      |From Node Type |to                                   |To Node Type |Edge Type          |to_release_date |to_genre             |to_notable |to_notoriety_date |\n|:-------------------------|:--------------|:------------------------------------|:------------|:------------------|:---------------|:--------------------|:----------|:-----------------|\n|Melancholy Circuitry      |Album          |Twilight's Threshold                 |Song         |CoverOf            |2007            |Synthwave            |TRUE       |2007              |\n|Electric Reverie          |Album          |Reflejo Interior                     |Song         |InterpolatesFrom   |1983            |Americana            |TRUE       |NA                |\n|Electric Reverie          |Album          |Folklore's Heartbeat                 |Song         |InStyleOf          |2020            |Blues Rock           |TRUE       |2033              |\n|Tides of Echos            |Album          |The Long Way Home                    |Album        |InStyleOf          |2023            |Dream Pop            |TRUE       |NA                |\n|Tides of Echos            |Album          |Weathered Miles                      |Song         |InterpolatesFrom   |2023            |Doom Metal           |TRUE       |NA                |\n|The Kelp Forest Canticles |Album          |Hallowed Transaction                 |Album        |DirectlySamples    |2017            |Doom Metal           |TRUE       |NA                |\n|The Kelp Forest Canticles |Album          |Für uns alle zusammen                |Song         |CoverOf            |2017            |Alternative Rock     |TRUE       |NA                |\n|Salty Dreams              |Album          |Susurros de Pasión                   |Song         |InStyleOf          |2004            |Synthwave            |TRUE       |2004              |\n|Salty Dreams              |Album          |Partisan's Lament                    |Song         |CoverOf            |2030            |Indie Pop            |TRUE       |NA                |\n|Coral Beats               |Album          |Sacred Fragments                     |Song         |InStyleOf          |2003            |Synthwave            |TRUE       |2003              |\n|Coral Beats               |Album          |Harvest Dance at Ler Valley          |Song         |CoverOf            |2010            |Psychedelic Rock     |TRUE       |NA                |\n|Oceanbound                |Album          |Bold Without Apology                 |Song         |LyricalReferenceTo |2010            |Indie Rock           |TRUE       |NA                |\n|Oceanbound                |Album          |Altitude of Mistakes                 |Song         |LyricalReferenceTo |2015            |Americana            |TRUE       |2015              |\n|High Tide Heartbeat       |Song           |Addicted to Your Heartache           |Album        |InterpolatesFrom   |2004            |Southern Gothic Rock |TRUE       |NA                |\n|Electric Eel Love         |Song           |Twelve Bells of Augsburg             |Song         |InStyleOf          |2026            |Psychedelic Rock     |TRUE       |NA                |\n|Electric Eel Love         |Song           |The Crown We Wear                    |Song         |CoverOf            |2022            |Indie Rock           |TRUE       |NA                |\n|Driftwood Lullaby         |Song           |Echoes of Forgotten Light            |Song         |InStyleOf          |2004            |Alternative Rock     |TRUE       |NA                |\n|Saltwater Hymn            |Song           |Parallel Memories                    |Song         |InStyleOf          |2028            |Dream Pop            |TRUE       |NA                |\n|Moon Over the Tide        |Song           |Divergent Memories                   |Song         |InterpolatesFrom   |2017            |Indie Folk           |TRUE       |2017              |\n|Moon Over the Tide        |Song           |Silent Steps in the Forest's Embrace |Song         |LyricalReferenceTo |2023            |Avant-Garde Folk     |TRUE       |2023              |\n|Barnacle Heart            |Song           |Our Inevitable Path                  |Song         |InStyleOf          |2017            |Indie Folk           |TRUE       |NA                |\n|Fog & Fiddle              |Song           |Provence Aria                        |Song         |InStyleOf          |2023            |Indie Rock           |TRUE       |NA                |\n|Fog & Fiddle              |Song           |Coastal Whispers of Biscay           |Song         |InterpolatesFrom   |2031            |Alternative Rock     |TRUE       |NA                |\n|Stormsong                 |Song           |When the Bar Lights Go Up            |Song         |InStyleOf          |2000            |Emo/Pop Punk         |TRUE       |NA                |\n|Stormsong                 |Song           |Exoskeleton Dissolve                 |Song         |DirectlySamples    |2020            |Indie Rock           |TRUE       |2020              |\n|Tidesworn Ballads         |Album          |Dreamscape of Judgment               |Song         |CoverOf            |2023            |Symphonic Metal      |TRUE       |NA                |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Get the complete information of the from node (From and To Info)\"}\nfrom_info <- nodes_all %>%\n  select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n  rename(\n    from = name,\n    `From Node Type` = `Node Type`,\n    from_release_date = release_date,\n    from_genre = genre,\n    from_notable = notable,\n    from_notoriety_date = notoriety_date\n  )\n\nto_info <- nodes_all %>%\n  select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n  rename(\n    to = name,\n    `To Node Type` = `Node Type`,\n    to_release_date = release_date,\n    to_genre = genre,\n    to_notable = notable,\n    to_notoriety_date = notoriety_date\n  )\n\nedges_2nd_full <- edges_2nd %>%\n  left_join(from_info, by = \"from\") %>%\n  left_join(to_info, by = \"to\") %>%\n  select(\n    from, `From Node Type`, from_release_date, from_genre, from_notable, from_notoriety_date,\n    to, `To Node Type`, to_release_date, to_genre, to_notable, to_notoriety_date,\n    `Edge Type`\n  )\n\nknitr::kable(edges_2nd_full)\n```\n\n::: {.cell-output-display}\n\n\n|from                      |From Node Type |from_release_date |from_genre   |from_notable |from_notoriety_date |to                                   |To Node Type |to_release_date |to_genre             |to_notable |to_notoriety_date |Edge Type          |\n|:-------------------------|:--------------|:-----------------|:------------|:------------|:-------------------|:------------------------------------|:------------|:---------------|:--------------------|:----------|:-----------------|:------------------|\n|Melancholy Circuitry      |Album          |2033              |Americana    |TRUE         |NA                  |Twilight's Threshold                 |Song         |2007            |Synthwave            |TRUE       |2007              |CoverOf            |\n|Electric Reverie          |Album          |2038              |Oceanus Folk |TRUE         |NA                  |Reflejo Interior                     |Song         |1983            |Americana            |TRUE       |NA                |InterpolatesFrom   |\n|Electric Reverie          |Album          |2038              |Oceanus Folk |TRUE         |NA                  |Folklore's Heartbeat                 |Song         |2020            |Blues Rock           |TRUE       |2033              |InStyleOf          |\n|Tides of Echos            |Album          |2029              |Oceanus Folk |TRUE         |NA                  |The Long Way Home                    |Album        |2023            |Dream Pop            |TRUE       |NA                |InStyleOf          |\n|Tides of Echos            |Album          |2029              |Oceanus Folk |TRUE         |NA                  |Weathered Miles                      |Song         |2023            |Doom Metal           |TRUE       |NA                |InterpolatesFrom   |\n|The Kelp Forest Canticles |Album          |2024              |Oceanus Folk |TRUE         |NA                  |Hallowed Transaction                 |Album        |2017            |Doom Metal           |TRUE       |NA                |DirectlySamples    |\n|The Kelp Forest Canticles |Album          |2024              |Oceanus Folk |TRUE         |NA                  |Für uns alle zusammen                |Song         |2017            |Alternative Rock     |TRUE       |NA                |CoverOf            |\n|Salty Dreams              |Album          |2030              |Oceanus Folk |TRUE         |NA                  |Susurros de Pasión                   |Song         |2004            |Synthwave            |TRUE       |2004              |InStyleOf          |\n|Salty Dreams              |Album          |2030              |Oceanus Folk |TRUE         |NA                  |Partisan's Lament                    |Song         |2030            |Indie Pop            |TRUE       |NA                |CoverOf            |\n|Coral Beats               |Album          |2034              |Oceanus Folk |TRUE         |NA                  |Sacred Fragments                     |Song         |2003            |Synthwave            |TRUE       |2003              |InStyleOf          |\n|Coral Beats               |Album          |2034              |Oceanus Folk |TRUE         |NA                  |Harvest Dance at Ler Valley          |Song         |2010            |Psychedelic Rock     |TRUE       |NA                |CoverOf            |\n|Oceanbound                |Album          |2038              |Oceanus Folk |TRUE         |NA                  |Bold Without Apology                 |Song         |2010            |Indie Rock           |TRUE       |NA                |LyricalReferenceTo |\n|Oceanbound                |Album          |2038              |Oceanus Folk |TRUE         |NA                  |Altitude of Mistakes                 |Song         |2015            |Americana            |TRUE       |2015              |LyricalReferenceTo |\n|High Tide Heartbeat       |Song           |2028              |Oceanus Folk |FALSE        |NA                  |Addicted to Your Heartache           |Album        |2004            |Southern Gothic Rock |TRUE       |NA                |InterpolatesFrom   |\n|Electric Eel Love         |Song           |2028              |Oceanus Folk |TRUE         |NA                  |Twelve Bells of Augsburg             |Song         |2026            |Psychedelic Rock     |TRUE       |NA                |InStyleOf          |\n|Electric Eel Love         |Song           |2028              |Oceanus Folk |TRUE         |NA                  |The Crown We Wear                    |Song         |2022            |Indie Rock           |TRUE       |NA                |CoverOf            |\n|Driftwood Lullaby         |Song           |2030              |Oceanus Folk |FALSE        |NA                  |Echoes of Forgotten Light            |Song         |2004            |Alternative Rock     |TRUE       |NA                |InStyleOf          |\n|Saltwater Hymn            |Song           |2032              |Oceanus Folk |FALSE        |NA                  |Parallel Memories                    |Song         |2028            |Dream Pop            |TRUE       |NA                |InStyleOf          |\n|Moon Over the Tide        |Song           |2034              |Oceanus Folk |TRUE         |NA                  |Divergent Memories                   |Song         |2017            |Indie Folk           |TRUE       |2017              |InterpolatesFrom   |\n|Moon Over the Tide        |Song           |2034              |Oceanus Folk |TRUE         |NA                  |Silent Steps in the Forest's Embrace |Song         |2023            |Avant-Garde Folk     |TRUE       |2023              |LyricalReferenceTo |\n|Barnacle Heart            |Song           |2034              |Oceanus Folk |FALSE        |NA                  |Our Inevitable Path                  |Song         |2017            |Indie Folk           |TRUE       |NA                |InStyleOf          |\n|Fog & Fiddle              |Song           |2036              |Oceanus Folk |TRUE         |NA                  |Provence Aria                        |Song         |2023            |Indie Rock           |TRUE       |NA                |InStyleOf          |\n|Fog & Fiddle              |Song           |2036              |Oceanus Folk |TRUE         |NA                  |Coastal Whispers of Biscay           |Song         |2031            |Alternative Rock     |TRUE       |NA                |InterpolatesFrom   |\n|Stormsong                 |Song           |2038              |Oceanus Folk |TRUE         |NA                  |When the Bar Lights Go Up            |Song         |2000            |Emo/Pop Punk         |TRUE       |NA                |InStyleOf          |\n|Stormsong                 |Song           |2038              |Oceanus Folk |TRUE         |NA                  |Exoskeleton Dissolve                 |Song         |2020            |Indie Rock           |TRUE       |2020              |DirectlySamples    |\n|Tidesworn Ballads         |Album          |2031              |Oceanus Folk |TRUE         |NA                  |Dreamscape of Judgment               |Song         |2023            |Symphonic Metal      |TRUE       |NA                |CoverOf            |\n\n\n:::\n:::\n\n\n\n\nNow we can observe the next layer — identifying which songs and related works have influenced Sailor Shift. At the same time, we also aim to incorporate the time dimension into this analysis.\n\n#### **Construct edges_time_ready data**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Construct edges_time_ready data\"}\nedges_time_ready <- edges_2nd_full %>%\n  mutate(\n    from_release_date = as.numeric(from_release_date),\n    to_release_date = as.numeric(to_release_date)\n  ) %>%\n  filter(!is.na(from_release_date) & !is.na(to_release_date)) %>%\n  mutate(\n    influencer_point = to,\n    sailor_point = from,\n    work_label = paste0(from, \" (Sailor)\"),\n    y_axis_label = paste0(from, \" (Sailor)\") \n  ) %>%\n  tidyr::pivot_longer(\n    cols = c(to_release_date, from_release_date),\n    names_to = \"timepoint\",\n    values_to = \"year\"\n  ) %>%\n  mutate(\n    point_type = ifelse(timepoint == \"from_release_date\", \"Sailor\", \"Influencer\"),\n    label = ifelse(point_type == \"Sailor\", from, to),\n    label_display = ifelse(point_type == \"Sailor\", paste0(label, \" (Sailor)\"), label),\n    genre = ifelse(point_type == \"Sailor\", from_genre, to_genre),\n    notable = ifelse(point_type == \"Sailor\", from_notable, to_notable)\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(edges_time_ready, aes(x = year, y = y_axis_label, group = paste(from, to))) +\n  geom_line(\n    aes(text = paste(\"Influence:\", to, \"→\", from)),\n    color = \"grey40\", linewidth = 0.4, alpha = 0.6\n  ) +\n  geom_point(\n    aes(\n      text = paste0(\n        \"Year: \", year,\n        \"<br>Work: \", label_display,\n        \"<br>Type: \", point_type,\n        \"<br>Genre: \", genre,\n        \"<br>Notable: \", ifelse(notable == TRUE, \"Yes\", \"No\"),\n        \"<br>Edge Type: \", `Edge Type`\n      ),\n      color = point_type\n    ),\n    size = 1.8, alpha = 0.9\n  ) +\n  scale_color_manual(values = c(\"Influencer\" = \"#1F78B4\", \"Sailor\" = \"#E41A1C\")) +\n  labs(\n    title = \"Influence Timeline of Sailor Shift's Works\",\n    subtitle = \"Lines point to Sailor's works (fixed y-axis)\",\n    x = \"Release Year\", y = \"Sailor's Work\", color = \"Point Type\"\n  ) +\n  scale_x_continuous(breaks = pretty(edges_time_ready$year, n = 10)) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_text(size = 7),\n    plot.title = element_text(hjust = 0, face = \"bold\", size = 16),\n    panel.grid.minor = element_blank(),\n    legend.position = \"bottom\",\n   \n  )\n\ninteractive_plot <- plotly::ggplotly(p, tooltip = \"text\")\ninteractive_plot\n```\n:::\n\n\n\n\n::: callout-note\n## When was she influenced, by whom, and in what way?\n\nTiming and Type of Influence\n\n-   Sailor Shift’s compositions were inspired by a wide temporal range of influencer works from the 1980s to the 2020s.\n\n-   Notable classics that shaped her music include:\n\n    Reflejo Interior (1983, Americana) → Influenced *Electric Reverie*\n\n    Twilight’s Threshold (2007, Synthwave) → Influenced *Tides of Echos*\n\n    Hallowed Transaction (2017, Doom Metal) and *Divergent Memories (2017, Indie Folk)* → Contributed to her emerging Indie and Metal sounds\n\n-   From a genre perspective, Sailor draws from Synthwave, Doom Metal, Dream Pop, Indie Rock, and Psychedelic Rock, blending them into her distinctive Oceanus Folk style.\n\nTime Distribution & Creative Rhythm\n\n-   2015–2020 marks the *starting phase of stylistic absorption*.\\\n\n    Songs like *Melancholy Circuitry* and *Stormsong* show early influence connections — indicating the onset of external musical borrowing.\n\n-   2023–2035 is her most active creative and stylistic integration period.\\\n\n    The visualization shows a dense cluster of red points (Sailor’s works) and blue points (influencer works), suggesting heavy external inspiration and high creative output during this time.\n\nCreative Maturity vs. Density of Inspiration\n\n-   Songs such as:\n\n    *Tidesworn Ballads*, *Coral Beats*, *Driftwood Lullaby*, *Electric Reverie*\\\n\n    are influenced by multiple sources — identifying them as \"convergent inspiration\" pieces reflecting diverse stylistic integration.\n\n-   Data also reveals:\n\n    Most of Sailor’s songs are of the Oceanus Folk genre, while the influencers span Synthwave, Southern Gothic, Indie Pop, Symphonic Metal, and more.\n\n    Her most notable works (marked as `Notable = TRUE`) tend to be those that were heavily influenced — indicating that *inspiration led to impact*.\n:::\n\nWe analyze the 'Other Person → Other Work → Sailor ' connections that contribute to the influence on Sailor Shift’s second-layer works.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Connections on Sailor Shift’s second-layer works\"}\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\nsailor_index <- nodes_tbl %>%\n  filter(name == \"Sailor Shift\") %>%\n  pull(index)\n\nedges_from_sailor <- edges_tbl %>%\n  filter(from == sailor_index)\n\nfirst_layer_info <- edges_from_sailor %>%\n  inner_join(nodes_tbl, by = c(\"to\" = \"index\")) %>%\n  filter(`Node Type` %in% c(\"Song\", \"Album\", \"MusicalGroup\", \"RecordLabel\"))\n\nfirst_layer_targets <- first_layer_info$to\n\ninfluence_edges <- c(\"InStyleOf\", \"LyricalReferenceTo\", \"InterpolatesFrom\", \"CoverOf\", \"DirectlySamples\")\n\nedges_2nd <- edges_tbl %>%\n  filter(from %in% first_layer_targets & `Edge Type` %in% influence_edges)\n\ninfluenced_works <- edges_2nd$to\nsongs_with_outgoing <- unique(edges_2nd$from)\n\nperson_edge_types <- c(\"PerformerOf\", \"ComposerOf\", \"LyricistOf\", \"ProducerOf\")\n\nedges_people_to_2nd <- edges_tbl %>%\n  filter(\n    to %in% influenced_works,\n    `Edge Type` %in% person_edge_types\n  ) %>%\n  left_join(nodes_tbl %>% select(index, `Node Type`), by = c(\"from\" = \"index\")) %>%\n  rename(`From Node Type` = `Node Type`) %>%\n  filter(`From Node Type` %in% c(\"Person\", \"RecordLabel\")) %>%\n  left_join(nodes_tbl %>% select(index, `Node Type`, release_date), by = c(\"to\" = \"index\")) %>%\n  rename(`To Node Type` = `Node Type`, release_date = release_date)\n```\n:::\n\n\n\n\n#### Indirectly influenced Sailor work and Sailor\n\nHere we can clearly see ,who has indirectly influenced Sailor work and Sailor.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_people_to_2nd_tbl <- edges_people_to_2nd %>%\n  left_join(nodes_tbl %>% select(index, name), by = c(\"from\" = \"index\")) %>%\n  rename(`Person Name` = name) %>%\n  left_join(nodes_tbl %>% select(index, name), by = c(\"to\" = \"index\")) %>%\n  rename(`Work Name` = name) %>%\n  select(`Person Name`, `Work Name`, `Edge Type`, `From Node Type`, `To Node Type`, release_date)\n\nknitr::kable(edges_people_to_2nd_tbl)\n```\n\n::: {.cell-output-display}\n\n\n|Person Name            |Work Name                            |Edge Type   |From Node Type |To Node Type |release_date |\n|:----------------------|:------------------------------------|:-----------|:--------------|:------------|:------------|\n|Ming Ren               |Provence Aria                        |PerformerOf |Person         |Song         |2023         |\n|Belinda Knappe         |Harvest Dance at Ler Valley          |ProducerOf  |Person         |Song         |2010         |\n|Yang Peng              |Sacred Fragments                     |PerformerOf |Person         |Song         |2003         |\n|Yang Peng              |Sacred Fragments                     |ProducerOf  |Person         |Song         |2003         |\n|Min Cao                |Sacred Fragments                     |PerformerOf |Person         |Song         |2003         |\n|Qiang Zhou             |Bold Without Apology                 |ComposerOf  |Person         |Song         |2010         |\n|Jing Kang              |Bold Without Apology                 |PerformerOf |Person         |Song         |2010         |\n|Jing Kang              |Bold Without Apology                 |ProducerOf  |Person         |Song         |2010         |\n|Jun Zhou               |Susurros de Pasión                   |PerformerOf |Person         |Song         |2004         |\n|Yong Dong              |Altitude of Mistakes                 |PerformerOf |Person         |Song         |2015         |\n|Urszula Stochmal       |Addicted to Your Heartache           |PerformerOf |Person         |Album        |2004         |\n|Urszula Stochmal       |Addicted to Your Heartache           |LyricistOf  |Person         |Album        |2004         |\n|Urszula Stochmal       |Addicted to Your Heartache           |ComposerOf  |Person         |Album        |2004         |\n|Ming Long              |Twilight's Threshold                 |PerformerOf |Person         |Song         |2007         |\n|Ming Long              |Twilight's Threshold                 |ProducerOf  |Person         |Song         |2007         |\n|Yong Lu                |Twilight's Threshold                 |LyricistOf  |Person         |Song         |2007         |\n|Yang Wan               |Sacred Fragments                     |ComposerOf  |Person         |Song         |2003         |\n|Yoko Hashimoto         |Hallowed Transaction                 |ProducerOf  |Person         |Album        |2017         |\n|Kaori Ito              |Hallowed Transaction                 |ComposerOf  |Person         |Album        |2017         |\n|Naoko Sato             |Hallowed Transaction                 |LyricistOf  |Person         |Album        |2017         |\n|Naoko Sato             |Hallowed Transaction                 |PerformerOf |Person         |Album        |2017         |\n|Yan Tang               |Altitude of Mistakes                 |ComposerOf  |Person         |Song         |2015         |\n|Jeremiah Love          |Twelve Bells of Augsburg             |PerformerOf |Person         |Song         |2026         |\n|Jeremiah Love          |Twelve Bells of Augsburg             |ProducerOf  |Person         |Song         |2026         |\n|Zachary Francis        |Twelve Bells of Augsburg             |PerformerOf |Person         |Song         |2026         |\n|Robert Woods           |Twelve Bells of Augsburg             |LyricistOf  |Person         |Song         |2026         |\n|Robert Woods           |Twelve Bells of Augsburg             |PerformerOf |Person         |Song         |2026         |\n|Sean Jones             |Partisan's Lament                    |ProducerOf  |Person         |Song         |2030         |\n|Min Long               |Susurros de Pasión                   |LyricistOf  |Person         |Song         |2004         |\n|Min Long               |Susurros de Pasión                   |PerformerOf |Person         |Song         |2004         |\n|Gang Shao              |Susurros de Pasión                   |LyricistOf  |Person         |Song         |2004         |\n|Gang Shao              |Susurros de Pasión                   |PerformerOf |Person         |Song         |2004         |\n|Qiang Yuan             |Susurros de Pasión                   |PerformerOf |Person         |Song         |2004         |\n|Wei Zhao               |Susurros de Pasión                   |ProducerOf  |Person         |Song         |2004         |\n|Juan Zhou              |Susurros de Pasión                   |PerformerOf |Person         |Song         |2004         |\n|Yang Zhao              |Susurros de Pasión                   |PerformerOf |Person         |Song         |2004         |\n|Xiulan Fang            |Altitude of Mistakes                 |PerformerOf |Person         |Song         |2015         |\n|Qiang Liu              |Altitude of Mistakes                 |ComposerOf  |Person         |Song         |2015         |\n|Qiang Liu              |Altitude of Mistakes                 |PerformerOf |Person         |Song         |2015         |\n|Jun Qiao               |Altitude of Mistakes                 |PerformerOf |Person         |Song         |2015         |\n|Ming Huang             |Altitude of Mistakes                 |PerformerOf |Person         |Song         |2015         |\n|Samantha Bullock       |Partisan's Lament                    |PerformerOf |Person         |Song         |2030         |\n|Shannon Harvey         |Our Inevitable Path                  |PerformerOf |Person         |Song         |2017         |\n|Shannon Harvey         |Our Inevitable Path                  |LyricistOf  |Person         |Song         |2017         |\n|Shannon Harvey         |Our Inevitable Path                  |ComposerOf  |Person         |Song         |2017         |\n|Lori Massey            |When the Bar Lights Go Up            |PerformerOf |Person         |Song         |2000         |\n|Lori Massey            |When the Bar Lights Go Up            |LyricistOf  |Person         |Song         |2000         |\n|Sheryl Roman           |Reflejo Interior                     |PerformerOf |Person         |Song         |1983         |\n|John Graves            |Reflejo Interior                     |ComposerOf  |Person         |Song         |1983         |\n|Jason Aguirre          |Reflejo Interior                     |PerformerOf |Person         |Song         |1983         |\n|Matthew Lane           |Reflejo Interior                     |ProducerOf  |Person         |Song         |1983         |\n|Cipriano Peranda       |Exoskeleton Dissolve                 |ComposerOf  |Person         |Song         |2020         |\n|Igor Dyś               |Echoes of Forgotten Light            |PerformerOf |Person         |Song         |2004         |\n|Igor Dyś               |Echoes of Forgotten Light            |LyricistOf  |Person         |Song         |2004         |\n|Tao Gao                |Silent Steps in the Forest's Embrace |PerformerOf |Person         |Song         |2023         |\n|Tao Gao                |Silent Steps in the Forest's Embrace |ProducerOf  |Person         |Song         |2023         |\n|Joseph Ponce           |Für uns alle zusammen                |PerformerOf |Person         |Song         |2017         |\n|Herbert Mcfarland      |Für uns alle zusammen                |PerformerOf |Person         |Song         |2017         |\n|Rachel Montes          |Für uns alle zusammen                |PerformerOf |Person         |Song         |2017         |\n|Caitlin Miller         |Für uns alle zusammen                |LyricistOf  |Person         |Song         |2017         |\n|Rebecca Wise           |Für uns alle zusammen                |PerformerOf |Person         |Song         |2017         |\n|Ping Liao              |Dreamscape of Judgment               |LyricistOf  |Person         |Song         |2023         |\n|Trevor Bass            |Dreamscape of Judgment               |PerformerOf |Person         |Song         |2023         |\n|Xiuying Du             |Dreamscape of Judgment               |PerformerOf |Person         |Song         |2023         |\n|Xia Yuan               |Dreamscape of Judgment               |PerformerOf |Person         |Song         |2023         |\n|Sandra Burke           |Dreamscape of Judgment               |PerformerOf |Person         |Song         |2023         |\n|Yan Li                 |Dreamscape of Judgment               |ComposerOf  |Person         |Song         |2023         |\n|Yan Li                 |Dreamscape of Judgment               |PerformerOf |Person         |Song         |2023         |\n|Ping Jin               |Parallel Memories                    |LyricistOf  |Person         |Song         |2028         |\n|Tao Wen                |Parallel Memories                    |PerformerOf |Person         |Song         |2028         |\n|Tao Wen                |Parallel Memories                    |ProducerOf  |Person         |Song         |2028         |\n|Guiying Ren            |Parallel Memories                    |PerformerOf |Person         |Song         |2028         |\n|Lei Shi                |Parallel Memories                    |PerformerOf |Person         |Song         |2028         |\n|Wei Liang              |Parallel Memories                    |ComposerOf  |Person         |Song         |2028         |\n|Wei Liang              |Parallel Memories                    |PerformerOf |Person         |Song         |2028         |\n|Joshua Taylor          |Divergent Memories                   |PerformerOf |Person         |Song         |2017         |\n|Joshua Taylor          |Divergent Memories                   |LyricistOf  |Person         |Song         |2017         |\n|Joshua Taylor          |Divergent Memories                   |ComposerOf  |Person         |Song         |2017         |\n|Lei Fu                 |Provence Aria                        |PerformerOf |Person         |Song         |2023         |\n|Lei Fu                 |Provence Aria                        |ProducerOf  |Person         |Song         |2023         |\n|Yan Dai                |Provence Aria                        |LyricistOf  |Person         |Song         |2023         |\n|Yan Dai                |Provence Aria                        |PerformerOf |Person         |Song         |2023         |\n|Daniel Mccormick       |Provence Aria                        |PerformerOf |Person         |Song         |2023         |\n|Lei Jin                |Provence Aria                        |PerformerOf |Person         |Song         |2023         |\n|James Medina           |Coastal Whispers of Biscay           |PerformerOf |Person         |Song         |2031         |\n|Matthew Best           |Coastal Whispers of Biscay           |LyricistOf  |Person         |Song         |2031         |\n|Matthew Best           |Coastal Whispers of Biscay           |PerformerOf |Person         |Song         |2031         |\n|Linda Burns            |Coastal Whispers of Biscay           |PerformerOf |Person         |Song         |2031         |\n|Brooke Olson           |Folklore's Heartbeat                 |PerformerOf |Person         |Song         |2020         |\n|David Reese            |Exoskeleton Dissolve                 |PerformerOf |Person         |Song         |2020         |\n|Ryan Dunlap            |Exoskeleton Dissolve                 |PerformerOf |Person         |Song         |2020         |\n|Elmo Calbo             |Exoskeleton Dissolve                 |PerformerOf |Person         |Song         |2020         |\n|Amico Luciani          |Exoskeleton Dissolve                 |PerformerOf |Person         |Song         |2020         |\n|Wei Zhao               |Silent Steps in the Forest's Embrace |ComposerOf  |Person         |Song         |2023         |\n|Tao Hu                 |Folklore's Heartbeat                 |ComposerOf  |Person         |Song         |2020         |\n|Tao Hu                 |Folklore's Heartbeat                 |PerformerOf |Person         |Song         |2020         |\n|Ming Qiao              |The Long Way Home                    |LyricistOf  |Person         |Album        |2023         |\n|Na Ye                  |The Long Way Home                    |PerformerOf |Person         |Album        |2023         |\n|Na Ye                  |The Long Way Home                    |ProducerOf  |Person         |Album        |2023         |\n|Debra Graham           |Weathered Miles                      |ComposerOf  |Person         |Song         |2023         |\n|Debra Graham           |Weathered Miles                      |PerformerOf |Person         |Song         |2023         |\n|Edward Evans           |Weathered Miles                      |LyricistOf  |Person         |Song         |2023         |\n|Dylan Schwartz         |Weathered Miles                      |PerformerOf |Person         |Song         |2023         |\n|James Henderson        |Weathered Miles                      |PerformerOf |Person         |Song         |2023         |\n|Amy Powell             |Weathered Miles                      |ProducerOf  |Person         |Song         |2023         |\n|Shawn Johnson          |Weathered Miles                      |ProducerOf  |Person         |Song         |2023         |\n|Joel Long              |Weathered Miles                      |PerformerOf |Person         |Song         |2023         |\n|Michael Nixon          |Weathered Miles                      |ComposerOf  |Person         |Song         |2023         |\n|Michael Nixon          |Weathered Miles                      |PerformerOf |Person         |Song         |2023         |\n|Nathan Jones           |Weathered Miles                      |PerformerOf |Person         |Song         |2023         |\n|Kimberly Estrada       |Twilight's Threshold                 |PerformerOf |Person         |Song         |2007         |\n|Fang Ding              |Twilight's Threshold                 |PerformerOf |Person         |Song         |2007         |\n|Miss Jennifer Williams |The Crown We Wear                    |PerformerOf |Person         |Song         |2022         |\n|William Robinson       |The Crown We Wear                    |PerformerOf |Person         |Song         |2022         |\n|William Robinson       |The Crown We Wear                    |ProducerOf  |Person         |Song         |2022         |\n|Judy Yang              |The Crown We Wear                    |PerformerOf |Person         |Song         |2022         |\n|Joanna Avery           |The Crown We Wear                    |PerformerOf |Person         |Song         |2022         |\n|Molly Gonzalez         |The Crown We Wear                    |PerformerOf |Person         |Song         |2022         |\n|Juan Shi               |Sacred Fragments                     |PerformerOf |Person         |Song         |2003         |\n|Ming Zhou              |Sacred Fragments                     |PerformerOf |Person         |Song         |2003         |\n|Simone Säuberlich      |Harvest Dance at Ler Valley          |ComposerOf  |Person         |Song         |2010         |\n|Simone Säuberlich      |Harvest Dance at Ler Valley          |PerformerOf |Person         |Song         |2010         |\n|Oceanic Records        |The Saltwater Weavers                |ProducerOf  |RecordLabel    |MusicalGroup |NA           |\n|Oceanic Records        |The Tide Singer's Knot               |ProducerOf  |RecordLabel    |MusicalGroup |NA           |\n|Oceanus Records        |The Salty Wakes                      |ProducerOf  |RecordLabel    |MusicalGroup |NA           |\n|Oceanus Records        |The Fiddle & The Fjord               |ProducerOf  |RecordLabel    |MusicalGroup |NA           |\n\n\n:::\n:::\n\n\n\n\n#### **Final Visualization Summary: Direct and Indirect Influences on Sailor Shift**\n\n-   First Layer: Nodes directly connected from Sailor Shift.\n\nIncludes:\n\nSongs and albums (these will propagate influence to the next layer)\n\nBands and record labels (no further propagation needed)\n\n-   Second Layer: All works that are influenced by the first-layer songs/albums and are linked to other individuals.\n\n-   Third Layer: The creators, producers, and other contributors behind the second-layer works, completing the indirect influence chain.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Final Visualization Summary-Direct and Indirect Influences on Sailor Shift\"}\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\nsailor_index <- nodes_tbl %>%\n  filter(name == \"Sailor Shift\") %>%\n  pull(index)\n\nedges_from_sailor <- edges_tbl %>%\n  filter(from == sailor_index)\n\nfirst_layer_info <- edges_from_sailor %>%\n  inner_join(nodes_tbl, by = c(\"to\" = \"index\")) %>%\n  filter(`Node Type` %in% c(\"Song\", \"Album\", \"MusicalGroup\", \"RecordLabel\"))\n\nfirst_layer_targets <- first_layer_info$to\n\ninfluence_edges <- c(\"InStyleOf\", \"LyricalReferenceTo\", \"InterpolatesFrom\", \"CoverOf\", \"DirectlySamples\")\n\nedges_2nd <- edges_tbl %>%\n  filter(from %in% first_layer_targets & `Edge Type` %in% influence_edges)\n\ninfluenced_works <- edges_2nd$to\nsongs_with_outgoing <- unique(edges_2nd$from)\n\nperson_edge_types <- c(\"PerformerOf\", \"ComposerOf\", \"LyricistOf\", \"ProducerOf\")\n\nedges_people_to_2nd <- edges_tbl %>%\n  filter(\n    to %in% influenced_works,\n    `Edge Type` %in% person_edge_types\n  ) %>%\n  left_join(nodes_tbl %>% select(index, `Node Type`), by = c(\"from\" = \"index\")) %>%\n  rename(`From Node Type` = `Node Type`) %>%\n  filter(`From Node Type` %in% c(\"Person\", \"RecordLabel\")) %>%\n  left_join(nodes_tbl %>% select(index, `Node Type`, release_date), by = c(\"to\" = \"index\")) %>%\n  rename(`To Node Type` = `Node Type`, release_date = release_date)\n\nfirst_layer_filtered <- first_layer_info %>%\n  filter(\n    (`Node Type` %in% c(\"Song\", \"Album\") & to %in% songs_with_outgoing) |\n    (`Node Type` %in% c(\"MusicalGroup\", \"RecordLabel\"))\n  )\n\nedges_from_sailor_filtered <- edges_from_sailor %>%\n  semi_join(first_layer_filtered, by = c(\"to\" = \"to\"))\n\nall_edges <- bind_rows(\n  edges_from_sailor_filtered,\n  edges_2nd,\n  edges_people_to_2nd %>% rename(from = from, to = to)\n)\n\nnode_ids <- unique(c(all_edges$from, all_edges$to))\n\nnodes_subgraph <- nodes_tbl %>%\n  filter(index %in% node_ids) %>%\n  transmute(\n    id = index,\n    label = name,\n    group = `Node Type`\n  )\n\nedges_subgraph <- all_edges %>%\n  transmute(\n    from = from,\n    to = to,\n    label = `Edge Type`,\n    title = paste0(\"Edge Type: \", `Edge Type`, \"<br>Release: \", release_date)\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisNetwork(nodes_subgraph, edges_subgraph, width = \"100%\", height = \"700px\") %>%\n  visEdges(arrows = \"to\") %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%\n  visLegend(\n    useGroups = TRUE,\n    position = \"right\",\n  ) %>%\n  visPhysics(\n    solver = \"forceAtlas2Based\",\n    forceAtlas2Based = list(gravitationalConstant = -80),\n    stabilization = list(enabled = TRUE, iterations = 100)\n  ) %>%\n  visLayout(randomSeed = 123)\n```\n:::\n\n\n\n\n::: callout-note\n## Who has she been most influenced?\n\nThe visual network clearly illustrates that Sailor Shift is not an isolated creator, but rather a convergence point within a multi-layered web of artistic influence.\n\nShe is directly influenced by several notable works, such as Tides of Echos and Electric Reverie, which themselves are shaped by earlier compositions and artists.\n\nAmong the sources of influence, four musical groups play a key role, including her own band Ivy Echos. The remaining groups—such as The Saltwater Weavers, The Fiddle & the Fjord, and The Salty Wakes—are projects she was closely involved in, either as a producer or performer. This dual role highlights her position as both an influencer and a participant in collaborative creation.\n\nIn the third layer of the influence network, most of the connections are formed through InStyleOf and InterpolatesFrom edges, indicating that Sailor Shift primarily draws inspiration from the style and structural elements of earlier works. Only a few edges fall under CoverOf, suggesting that her creative process leans more toward reinterpretation and transformation rather than direct replication.\n\nThis cascading network of style, melody, and lyrical influence reflects not only her artistic lineage, but also reveals the broader creative transmission ecosystem within the Oceanus Folk community.\n:::\n\n### **2.Who has she collaborated with and directly or indirectly influenced? &** \n\n### **3.How has she influenced collaborators of the broader Oceanus Folk community**\n\n#### First we will first answer ：Who has she influenced ?\n\nAnd here is the directly neighbours :\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\nsailor_index <- nodes_tbl %>%\n  filter(name == \"Sailor Shift\") %>%\n  pull(index)\n\ninfluence_edges <- c(\"InStyleOf\", \"CoverOf\", \"InterpolatesFrom\", \"LyricalReferenceTo\", \"DirectlySamples\")\n\nedges_from_sailor <- edges_tbl %>%\n  filter(to == sailor_index & `Edge Type` %in% influence_edges)\n\ninfluenced1 <- edges_from_sailor %>%\n  left_join(nodes_tbl, by = c(\"from\" = \"index\")) %>%\n  select(name, `Edge Type`, everything())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(influenced1)\n```\n\n::: {.cell-output-display}\n\n\n|name                  |Edge Type          | source| target| key|  from|    to|Node Type    |single |release_date |genre |notable |    id|written_date |stage_name     |notoriety_date |\n|:---------------------|:------------------|------:|------:|---:|-----:|-----:|:------------|:------|:------------|:-----|:-------|-----:|:------------|:--------------|:--------------|\n|Cassette Future       |InStyleOf          |  17022|  17255|   0| 17023| 17256|MusicalGroup |NA     |NA           |NA    |NA      | 17022|NA           |NA             |NA             |\n|Silver Veil           |LyricalReferenceTo |  17032|  17255|   0| 17033| 17256|MusicalGroup |NA     |NA           |NA    |NA      | 17032|NA           |NA             |NA             |\n|The Phantom Operators |InterpolatesFrom   |  17063|  17255|   0| 17064| 17256|MusicalGroup |NA     |NA           |NA    |NA      | 17063|NA           |NA             |NA             |\n|The Hollow Monarchs   |InStyleOf          |  17110|  17255|   0| 17111| 17256|MusicalGroup |NA     |NA           |NA    |NA      | 17110|NA           |NA             |NA             |\n|Cassian Storm         |LyricalReferenceTo |  17126|  17255|   0| 17127| 17256|Person       |NA     |NA           |NA    |NA      | 17126|NA           |Seraphina Vale |NA             |\n|Claire Holmes         |InterpolatesFrom   |  17155|  17255|   0| 17156| 17256|Person       |NA     |NA           |NA    |NA      | 17155|NA           |Jaye Finch     |NA             |\n|Copper Canyon Ghosts  |DirectlySamples    |  17361|  17255|   0| 17362| 17256|MusicalGroup |NA     |NA           |NA    |NA      | 17361|NA           |NA             |NA             |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Directly neighbours that she has influenced\"}\nsubgraph_in <- extract_subnetwork(\n  graph, \n  node_name = \"Sailor Shift\", \n  distance = 3, \n  direction = \"in\"\n)\n\nedges_vn <- igraph::as_data_frame(subgraph_in, what = \"edges\") %>%\n  filter(`Edge Type` != \"ProducerOf\") %>%\n  rename(from = from, to = to, label = `Edge Type`)\n\nnodes_vn <- igraph::as_data_frame(subgraph_in, what = \"vertices\") %>%\n  mutate(id = name, label = name, group = `Node Type`)\n\nused_nodes <- unique(c(edges_vn$from, edges_vn$to))\nnodes_vn <- nodes_vn %>% filter(id %in% used_nodes)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisNetwork(nodes_vn, edges_vn, height = \"800px\", width = \"100%\") %>%\n  visEdges(arrows = \"to\") %>%\n  visOptions(\n    highlightNearest = list(enabled = TRUE, degree = 3, hover = TRUE),\n    nodesIdSelection = TRUE,\n    selectedBy = \"group\"\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 1234) %>%\n  visInteraction(navigationButtons = TRUE)\n```\n:::\n\n\n\n\n::: callout-note\n## Who has she influenced directly or indirectly？\n\nThese are edges originating from Sailor Shift, indicating how she influences other groups or works:\n\n-   InStyleOf: stylistic influence or similar musical style\n\n-   InterpolatesFrom: portions of her work have been interpolated\n\n-   LyricalReferenceTo: her name or lyrics are referenced\n\n-   DirectlySamples: her work has been directly sampled\n\nSailor Shift has a broad creative influence\n\n-   She influences at least 5 different groups (e.g., Cassette Future, The Hollow Monarchs)\n\n-   The types of influence span style, lyrics, and sampling.\n\nAn indirect \"sub-network\" is formed\n\n-   For example, through the path Sailor Shift → Cassette Future → Zara Quinn, her influence extends to band members as well.\n\nStrong structural centrality\n\n-   Sailor Shift is the hub of this network, with nearly all edges revolving around her.\n\n-   This suggests she holds a central position of influence in this music community.\n:::\n\n***We attempted to trace Sailor Shift’s indirect influence through songs and albums to identify impacted individuals. However, this approach yielded no results, so we decided not to pursue this path further.***\n\nBased on the results, Copper Canyon Ghosts is identified as an Oceanus Folk band. To explore the third question—\"**How has Sailor Shift influenced collaborators within the broader Oceanus Folk community**?\"—we will examine both direct and indirect influence paths .\n\n#### Identify the artists and groups influenced by Sailor Shift in Oceanus Folk Genre\n\nFirst, we identify the artists and groups influenced by Sailor Shift. Among them, we determine which ones belong to the Oceanus Folk genre, using \"genre\" as our key search indicator.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"which ones belong to the Oceanus Folk genre?\"}\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\ncreator_names <- c(\n  \"Zara Quinn\", \"Milo Knight\", \"Cassette Future\", \"Eliza Brooks\",\n  \"Jasper Reed\", \"Silver Veil\", \"Juno Ray\", \"Savannah Teal\",\n  \"The Phantom Operators\", \"Chloe Montgomery\", \"Nathaniel Brooks\", \"Clara Davis\",\n  \"The Hollow Monarchs\", \"Cassian Storm\", \"Claire Holmes\", \"Beatrice Albright\",\n  \"Daniel O'Connell\", \"Copper Canyon Ghosts\"\n)\n\ncreator_ids <- nodes_tbl %>%\n  filter(name %in% creator_names) %>%\n  pull(index)\n\ntarget_edge_types <- c(\"PerformerOf\", \"ComposerOf\", \"LyricistOf\", \"ProducerOf\")\n\nedges_out <- edges_tbl %>%\n  filter(from %in% creator_ids, `Edge Type` %in% target_edge_types)\n\nedges_out_full <- edges_out %>%\n  left_join(nodes_tbl %>% mutate(index = row_number()), by = c(\"to\" = \"index\")) %>%\n  select(from, to, `Edge Type`, name, `Node Type`, release_date,genre,notable,notoriety_date)\n\nedges_out_full <- edges_out_full %>%\n  left_join(nodes_tbl %>% select(index, creator_name = name), by = c(\"from\" = \"index\")) %>%\n  select(creator_name, `Edge Type`, name, `Node Type`, release_date,genre,notable,notoriety_date)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_oceanus <- edges_out_full %>%\n  filter(genre == \"Oceanus Folk\")\n\nknitr::kable(head(edges_oceanus, 6))\n```\n\n::: {.cell-output-display}\n\n\n|creator_name      |Edge Type   |name                       |Node Type |release_date |genre        |notable |notoriety_date |\n|:-----------------|:-----------|:--------------------------|:---------|:------------|:------------|:-------|:--------------|\n|Beatrice Albright |PerformerOf |Tidesworn Ballads          |Album     |2031         |Oceanus Folk |TRUE    |NA             |\n|Beatrice Albright |LyricistOf  |Tidesworn Ballads          |Album     |2031         |Oceanus Folk |TRUE    |NA             |\n|Beatrice Albright |PerformerOf |Tidesworn Ballads          |Album     |2031         |Oceanus Folk |TRUE    |NA             |\n|Beatrice Albright |PerformerOf |The Siren's Sigh           |Song      |2031         |Oceanus Folk |TRUE    |2031           |\n|Beatrice Albright |PerformerOf |Whispers on the Jetty Wind |Song      |2031         |Oceanus Folk |TRUE    |2031           |\n|Beatrice Albright |PerformerOf |Moonlit Kelp Forest Dance  |Song      |2031         |Oceanus Folk |TRUE    |2031           |\n\n\n:::\n:::\n\n\n\n\nThis table summarizes the creative contributions of Beatrice Albright, Daniel O'Connell, and Copper Canyon Ghosts to various albums and songs—all of which are part of the Oceanus Folk genre\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"How has Sailor Shift influenced collaborators within the broader Oceanus Folk community?\"}\nedges_sailor <- edges_all %>%\n  filter(to == \"Sailor Shift\") %>%\n  filter(`Edge Type` %in% c(\"InStyleOf\", \"LyricalReferenceTo\", \"CoverOf\", \"InterpolatesFrom\", \"DirectlySamples\")) %>%\n  select(from, to, `Edge Type`)\n\ncreator_work_nodes <- unique(c(edges_oceanus$creator_name, edges_oceanus$name))\n\nall_node_names <- union(\n  creator_work_nodes,\n  unique(c(edges_sailor$from, edges_sailor$to, \"Sailor Shift\", \"Copper Canyon Ghosts\"))  \n)\n\nnodes_vn <- nodes_tbl %>%\n  filter(name %in% all_node_names) %>%\n  mutate(\n    id = index,\n    label = name,\n    group = `Node Type`,\n    color.background = ifelse(name == \"Sailor Shift\", \"blue\", NA), \n    shape = ifelse(name == \"Sailor Shift\", \"star\", \"dot\")\n  )\n\nedges_vn_creator <- edges_oceanus %>%\n  rename(from = creator_name, to = name, label = `Edge Type`) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"from\" = \"name\")) %>%\n  rename(from_id = id) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"to\" = \"name\")) %>%\n  rename(to_id = id) %>%\n  mutate(length = NA) %>%\n  select(from = from_id, to = to_id, label, length) %>%\n  filter(!is.na(from) & !is.na(to))\n\nedges_vn_sailor <- edges_sailor %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"from\" = \"name\")) %>%\n  rename(from_id = id) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"to\" = \"name\")) %>%\n  rename(to_id = id) %>%\n  mutate(length = NA) %>%\n  select(from = from_id, to = to_id, label = `Edge Type`, length) %>%\n  filter(!is.na(from) & !is.na(to))\n\nforced_edge <- tibble(\n  from = \"Copper Canyon Ghosts\",\n  to = \"Sailor Shift\",\n  label = \"DirectlySamples\",\n  length = 400\n)\n\nforced_edge_ids <- forced_edge %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"from\" = \"name\")) %>%\n  rename(from_id = id) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"to\" = \"name\")) %>%\n  rename(to_id = id) %>%\n  select(from = from_id, to = to_id, label, length) %>%\n  filter(!is.na(from) & !is.na(to))\n\nedges_final <- bind_rows(\n  edges_vn_creator,\n  edges_vn_sailor,\n  forced_edge_ids\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisNetwork(nodes_vn, edges_final, height = \"700px\", width = \"100%\") %>%\n  visEdges(arrows = \"to\") %>%\n  visOptions(\n    highlightNearest = TRUE,\n    nodesIdSelection = TRUE,\n    selectedBy = \"group\"\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 42) %>%\n  visPhysics(\n    solver = \"forceAtlas2Based\",\n    forceAtlas2Based = list(gravitationalConstant = -80),\n    stabilization = list(enabled = TRUE, iterations = 100)\n  )\n```\n:::\n\n\n\n\n::: callout-note\n## How has Sailor Shift influenced collaborators within the broader Oceanus Folk community?\n\nSailor Shift → influences Copper Canyon Ghosts → performs representative works → connects with Daniel and Beatrice through shared creations\n\nThis influence pathway shows that Sailor Shift's creative style and content are indirectly transmitted to other members of the Oceanus Folk community through collaborative performances and reinterpretations.\\\n\nThe network visualization reveals that Sailor Shift influences key figures in the Oceanus Folk scene both directly and indirectly.\\\n\nShe is sampled by Copper Canyon Ghosts, a band that performs major works composed by Daniel O'Connell and Beatrice Albright.\\\n\nThese shared works form the musical core of the Oceanus Folk genre, creating a multi-layered influence network with Sailor Shift at its source.\\\n\nHer creative impact extends beyond direct collaboration—spreading throughout the community via the chain of **work → band → collaborators**, shaping the genre’s evolution and collective identity.\n:::\n\n## Summary of Question 1\n\nSailor Shift is both a cultural inheritor and a creative engine. She draws on decades of musical history, spanning genres from Synthwave to Americana, integrating them into the Oceanus Folk style. Through direct performances and indirect stylistic channels, she influences a wide web of collaborators and emerging artists—serving as a stylistic and structural anchor for the Oceanus Folk scene. Her work demonstrates a rare balance between solo artistry and community participation, making her a pivotal node in the evolution of this genre.\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}