{
  "hash": "cf73573d19932629982c3b07e8aac728",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 2\"\nauthor: \"yang yayong\"\ndate: \"May 21 2025\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  message: false\n  freeze: true\n  warning: FALSE\n---\n\n\n\n# VAST Challenge 2024 Mini-Challenge 1\n\n# Overview\n\nIn this exercise, I will address **Question 1** and **Question 2** individually.\n\n1.  Design and develop visualizations and visual analytic tools that will allow Silas to explore and understand the profile of Sailor Shift’s career\n\n    1.  Who has she been most influenced by over time?\n\n    2.  Who has she collaborated with and directly or indirectly influenced?\n\n    3.  How has she influenced collaborators of the broader Oceanus Folk community?\n\n2.  Develop visualizations that illustrate how the influence of Oceanus Folk has spread through the musical world.\n\n    1.  Was this influence intermittent or did it have a gradual rise?\n\n    2.  What genres and top artists have been most influenced by Oceanus Folk?\n\n    3.  On the converse, how has Oceanus Folk changed with the rise of Sailor Shift? From which genres does it draw most of its contemporary inspiration?\n\n## Getting Started\n\nFor the purpose of this exercise, four R packages will be used. They are tidyverse, jsonlite, tidygraph and ggraph.\n\nIn the code chunk below, `p_load()` of **pacman** package is used to load the R packages into R environemnt.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, jsonlite,\n               tidygraph, ggraph,ggplot2,SmartEDA,igraph,visNetwork)\n```\n:::\n\n\n\n## Importing Kownledge Graph Data\n\nFor the purpose of this exercise, *MC1_graph.json* file will be used. Before getting started, you should have the data set in the **data** sub-folder.\n\nIn the code chunk below, `fromJSON()` of **jsonlite** package is used to import *MC1_graph.json* file into R and save the output object\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkg <- fromJSON(\"data/MC1_graph.json\")\n```\n:::\n\n\n\nWhat are the components of kg data?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(kg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi TRUE\n $ graph     :List of 2\n  ..$ node_default: Named list()\n  ..$ edge_default: Named list()\n $ nodes     :'data.frame':\t17412 obs. of  10 variables:\n  ..$ Node Type     : chr [1:17412] \"Song\" \"Person\" \"Person\" \"Person\" ...\n  ..$ name          : chr [1:17412] \"Breaking These Chains\" \"Carlos Duffy\" \"Min Qin\" \"Xiuying Xie\" ...\n  ..$ single        : logi [1:17412] TRUE NA NA NA NA FALSE ...\n  ..$ release_date  : chr [1:17412] \"2017\" NA NA NA ...\n  ..$ genre         : chr [1:17412] \"Oceanus Folk\" NA NA NA ...\n  ..$ notable       : logi [1:17412] TRUE NA NA NA NA TRUE ...\n  ..$ id            : int [1:17412] 0 1 2 3 4 5 6 7 8 9 ...\n  ..$ written_date  : chr [1:17412] NA NA NA NA ...\n  ..$ stage_name    : chr [1:17412] NA NA NA NA ...\n  ..$ notoriety_date: chr [1:17412] NA NA NA NA ...\n $ links     :'data.frame':\t37857 obs. of  4 variables:\n  ..$ Edge Type: chr [1:37857] \"InterpolatesFrom\" \"RecordedBy\" \"PerformerOf\" \"ComposerOf\" ...\n  ..$ source   : int [1:37857] 0 0 1 1 2 2 3 5 5 5 ...\n  ..$ target   : int [1:37857] 1841 4 0 16180 0 16180 0 5088 14332 11677 ...\n  ..$ key      : int [1:37857] 0 0 0 0 0 0 0 0 0 0 ...\n```\n\n\n:::\n:::\n\n\n\nThe result shows a typical **knowledge graph (KG)** data structure, the detail explanation is as followed:\n\n1.The overall structure is a list of 5 elements:\n\n| Element Name | Meaning |\n|------------------------------------|------------------------------------|\n| directed: TRUE | Indicates the graph is **directed** (i.e., relationships have direction, like “someone performed a song”) |\n| multigraph: TRUE | Indicates this is a **multigraph**, meaning multiple edges (relationships) can exist between the same pair of nodes (e.g., a person can be both “composer” and “performer”) |\n| graph | Contains default attributes for nodes and edges (currently empty named lists) |\n| nodes | A `data.frame`, each row represents a **node** (e.g., a person or a song) |\n| links | A `data.frame`, each row represents an **edge** (i.e., a relationship between two nodes) |\n\n2.`nodes` table (node metadata)\n\nThere are **17,412 nodes**, with the following variables:\n\n| Column Name    | Example / Meaning                               |\n|----------------|-------------------------------------------------|\n| Node Type      | Node type, such as `\"Song\"` or `\"Person\"`       |\n| name           | Name of the node (e.g., a person or song title) |\n| single         | Whether it is a single (TRUE / FALSE)           |\n| release_date   | Release date (e.g., `\"2017\"`)                   |\n| genre          | Genre (e.g., `\"Oceanus Folk\"`)                  |\n| notable        | Whether it's notable (TRUE / FALSE)             |\n| id             | Unique ID for the node                          |\n| written_date   | Date the song was written                       |\n| stage_name     | Stage name (if any)                             |\n| notoriety_date | Date the artist became known (if any)           |\n\n3.`links` table (edge/relationship information)\n\nThere are **37,857 edges**, with the following columns:\n\n| Column Name | Meaning / Example |\n|------------------------------------|------------------------------------|\n| Edge Type | Type of relationship (e.g., `\"PerformerOf\"`, `\"ComposerOf\"`, `\"InterpolateFrom\"`) |\n| source | ID of the source node |\n| target | ID of the target node |\n| key | Differentiates multiple edges between the same nodes |\n\n**Inspect structure**\n\nBefore preparing the data, it is always a good practice to examine the structure of *kg* object.\n\nIn the code chunk below `str()` is used to reveal the structure of *kg* object.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(kg, max.level = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi TRUE\n $ graph     :List of 2\n $ nodes     :'data.frame':\t17412 obs. of  10 variables:\n $ links     :'data.frame':\t37857 obs. of  4 variables:\n```\n\n\n:::\n:::\n\n\n\n## **Extracting the edges and nodes tables**\n\nNext, `as_tibble()` of **tibble** package package is used to **extract the nodes and links tibble data frames** from *kg* object into two separate tibble data frames called *nodes_tbl* and *edges_tbl* respectively.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- as_tibble(kg$nodes)\nedges_tbl <- as_tibble(kg$links) \n```\n:::\n\n\n\n### **Initial EDA**\n\nIt is time for us to apply appropriate EDA methods to examine the data.\n\nIn this code chunk below, ggplot2 functions are used the reveal the frequency distribution of *Edge Type* field of *edges_tbl*.\n\n::: panel-tabset\n## Nodes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl %>%\n  count(`Node Type`) %>%\n  ggplot(aes(x = n, y = reorder(`Node Type`, n))) +\n  geom_col(fill = \"steelblue\") +\n  labs(title = \"Distribution of Node Types in Knowledge Graph\",\n       x = \"Count\", y = \"Node Type\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n**Most nodes are of type `Person`**\n\n-   **Explanation**: Individuals (singers, composers, producers, etc.) form the majority of nodes.\n\n-   **Insight**: The knowledge graph is **person-centric**, emphasizing individual contributions in the music ecosystem.\n\n**`Song` is the second most frequent node type**\n\n-   **Explanation**: Songs are heavily represented, as expected in a music-related knowledge graph.\n\n-   **Insight**: This reflects the graph’s role in **mapping who is connected to which songs**, enabling analysis of performance, authorship, and influence.\n\n**Other node types (e.g., `RecordLabel`, `Album`, `MusicalGroup`) are far fewer**\n\n-   **Explanation**: Entities like music labels, albums, and groups are present but much less prominent.\n\n-   **Insight**: These nodes play a **supporting role** in contextualizing the people-song relationships, potentially useful for advanced analyses (e.g., influence of labels, collaborations within groups).\n\n**`MusicalGroup` nodes are very rare**\n\n-   **Insight**: Either the graph focuses more on individual artists rather than bands/groups, or group membership data may be under-represented.\n\n## Edges\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_tbl %>%\n  count(`Edge Type`) %>%\n  ggplot(aes(x = n, y = reorder(`Edge Type`, n))) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\") +\n  labs(title = \"Edge Type Distribution in Knowledge Graph\",\n       x = \"Count\", y = \"Edge Type\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n### **\"PerformerOf\" is the most frequent edge type**\n\n-   **Explanation:** The majority of edges connect a **person** to a **song** via a performance relationship.\n\n-   **Insight:** This indicates that the relationship between performers and songs is a core structure in the knowledge graph, showing that the graph places a strong emphasis on **who performed what**.\n\n**\"RecordedBy\", \"ComposerOf\", and \"ProducerOf\" are also common**\n\n-   **Explanation:** Besides performers, the graph also documents many **creators** of the music, including **composers, producers**, and **recording personnel**.\n\n-   **Insight:** This suggests the graph goes beyond surface-level links, capturing multiple roles across the **music creation pipeline**.\n\n**Edge types like \"DirectlySamples\", \"CoverOf\", \"MemberOf\", and \"LyricalReferenceTo\" are less frequent**\n\n-   **Explanation:** These edges represent more complex or less common musical relationships, such as:\n\n-   **DirectlySamples**: relates to copyright and musical inspiration\n\n-   **CoverOf**: shows the propagation of classic works through cover versions\n\n-   **MemberOf**: describes group or band membership\n\n-   **Insight:** Although less common, these edge types may hold higher value in studying **musical influence** and **cultural transmission**.\n:::\n\nOn the other hands, code chunk below uses ggplot2 functions to reveal the frequency distribution of *Node Type* field of *nodes_tbl*.\n\n## **Creating Knowledge Graph**\n\n### **Mapping from node id to row index**\n\nBefore we can go ahead to build the tidygraph object, it is important for us to ensures each id from the node list is mapped to the correct row number. This requirement can be achive by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_map <- tibble(id = nodes_tbl$id,  #Retrieve the ID column of each row node\n                 index = seq_len(\n                   nrow(nodes_tbl)))  #Generate a line number sequence from 1 to n\n```\n:::\n\n\n\n### **Map source and target IDs to row indices**\n\nNext, we will map the source and the target IDs to row indices by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_tbl <- edges_tbl %>%\n  left_join(id_map, by = c(\"source\" = \"id\")) %>%  # source id → from index\n  rename(from = index) %>% \n  left_join(id_map, by = c(\"target\" = \"id\")) %>%  # target id → to index\n  rename(to = index)\n```\n:::\n\n\n\n::: callout-note\nTo better understand the changes before and after the process, it is to take a screenshot of *edges_tbl* before and after this process and examine the differences.\n:::\n\n![](images/clipboard-2426498860.png){width=\"266\"}\n\n![](images/clipboard-3714188848.png){width=\"351\"}\n\nNow we can see the difference between before and after the *edges_tbl.*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(edges_tbl$`Edge Type`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n        ComposerOf            CoverOf    DirectlySamples      DistributedBy \n              3290               1429                619               3013 \n         InStyleOf   InterpolatesFrom LyricalReferenceTo         LyricistOf \n              2289               1574               1496               2985 \n          MemberOf        PerformerOf         ProducerOf         RecordedBy \n               568              13587               3209               3798 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\nof_edges <- edges_tbl %>%\n  filter(`Edge Type` %in% c(\"PerformerOf\", \"ComposerOf\", \"LyricistOf\", \"ProducerOf\"))\n\nof_edges_with_target_info <- of_edges %>%\n  left_join(nodes_tbl, by = c(\"target\" = \"id\")) %>%\n  select(`Edge Type`, target_name = name, target_type = `Node Type`)\n\nsummary_table <- of_edges_with_target_info %>%\n  group_by(`Edge Type`, target_type) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  arrange(`Edge Type`, desc(count))\n\nprint(summary_table)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nof_edges_full <- of_edges %>%\n  left_join(nodes_tbl, by = c(\"source\" = \"id\")) %>%\n  rename(from_name = name, from_type = `Node Type`) %>%\n  left_join(nodes_tbl, by = c(\"target\" = \"id\")) %>%\n  rename(to_name = name, to_type = `Node Type`) %>%\n  select(`Edge Type`, from_name, from_type, to_name, to_type)\n\nprint(of_edges_full)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nof_edges_full %>%\n  count(`Edge Type`, from_type)\n```\n:::\n\n\n\n### **Filter out any unmatched (invalid) edges**\n\nLastly, the code chunk below will be used to exclude the unmatch edges.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_tbl <- edges_tbl %>%\n  filter(!is.na(from), !is.na(to))\n```\n:::\n\n\n\n### **Creating tidygraph**\n\nLastly, `tbl_graph()` is used to create tidygraph’s graph object by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph <- tbl_graph(nodes = nodes_tbl, \n                   edges = edges_tbl, \n                   directed = kg$directed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tbl_graph: 17412 nodes and 37857 edges\n#\n# A directed multigraph with 16 components\n#\n# Node Data: 17,412 × 10 (active)\n   `Node Type` name         single release_date genre notable    id written_date\n   <chr>       <chr>        <lgl>  <chr>        <chr> <lgl>   <int> <chr>       \n 1 Song        Breaking Th… TRUE   2017         Ocea… TRUE        0 <NA>        \n 2 Person      Carlos Duffy NA     <NA>         <NA>  NA          1 <NA>        \n 3 Person      Min Qin      NA     <NA>         <NA>  NA          2 <NA>        \n 4 Person      Xiuying Xie  NA     <NA>         <NA>  NA          3 <NA>        \n 5 RecordLabel Nautical Mi… NA     <NA>         <NA>  NA          4 <NA>        \n 6 Song        Unshackled … FALSE  2026         Lo-F… TRUE        5 <NA>        \n 7 Person      Luke Payne   NA     <NA>         <NA>  NA          6 <NA>        \n 8 Person      Xiulan Zeng  NA     <NA>         <NA>  NA          7 <NA>        \n 9 Person      David Frank… NA     <NA>         <NA>  NA          8 <NA>        \n10 RecordLabel Colline-Cas… NA     <NA>         <NA>  NA          9 <NA>        \n# ℹ 17,402 more rows\n# ℹ 2 more variables: stage_name <chr>, notoriety_date <chr>\n#\n# Edge Data: 37,857 × 6\n   from    to `Edge Type`      source target   key\n  <int> <int> <chr>             <int>  <int> <int>\n1     1  1842 InterpolatesFrom      0   1841     0\n2     1     5 RecordedBy            0      4     0\n3     2     1 PerformerOf           1      0     0\n# ℹ 37,854 more rows\n```\n\n\n:::\n:::\n\n\n\nYou might want to confirm the output object is indeed in tidygraph format by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(graph)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"tbl_graph\" \"igraph\"   \n```\n\n\n:::\n:::\n\n\n\n## **Visualising the knowledge graph**\n\nIn this section, we will use ggraph’s functions to visualise and analyse the graph object.\n\n::: callout-warning\nThe two examples below are not model answers, they are examples to show you how to use the mantra of **Overview first, details on demand** of visual investigation.\n:::\n\nSeveral of the ggraph layouts involve randomisation. In order to ensure reproducibility, it is necessary to set the seed value before plotting by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\n\n### **Visualising the whole graph**\n\nIn the code chunk below, ggraph functions are used to visualise the whole graph.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggraph(graph, layout = \"fr\") +\n  geom_edge_link(alpha = 0.3, \n                 colour = \"gray\") +\n  geom_node_point(aes(color = `Node Type`), \n                  size = 4) +\n  geom_node_text(aes(label = name), \n                 repel = TRUE, \n                 size = 2.5) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\nNotice that the whole graph is very messy and we can hardy discover any useful patterns. This is always the case in graph visualisation and analysis. In order to gain meaningful visual discovery, it is always useful for us to looking into the details, for example by plotting sub-graphs.\n\n### **Visualising the sub-graph**\n\nIn this section, we are interested to create a sub-graph base on *MemberOf* value in *Edge Type* column of the *edges* data frame.\n\n#### **Filtering edges to only “MemberOf”**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_memberof <- graph %>%\n  activate(edges) %>%   ##\n  filter(`Edge Type` == \"MemberOf\")\n```\n:::\n\n\n\n#### **Extracting only connected nodes (i.e., used in these edges)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nused_node_indices <- graph_memberof %>%\n  activate(edges) %>%\n  as_tibble() %>%\n  select(from, to) %>%\n  unlist() %>%\n  unique()\n```\n:::\n\n\n\n#### **Keeping only those nodes**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_memberof <- graph_memberof %>%\n  activate(nodes) %>%\n  mutate(row_id = row_number()) %>%\n  filter(row_id %in% used_node_indices) %>%\n  select(-row_id)  # optional cleanup\n```\n:::\n\n\n\n#### **Plotting the sub-graph**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggraph(graph_memberof, \n       layout = \"fr\") +\n  geom_edge_link(alpha = 0.5, \n                 colour = \"gray\") +\n  geom_node_point(aes(color = `Node Type`), \n                  size = 1) +\n  geom_node_text(aes(label = name), \n                 repel = TRUE, \n                 size = 2.5) +\n  theme_void()\n```\n:::\n\n\n\nNotice that the sub-graph above is very clear and the relationship between musical group and person can be visualise easily.\n\n## Proceed to answer the questions for Mini-Challenge 1\n\nFirstly, I created an `extract_subnetwork` function to simplify the process of extracting network data. The methodology was referenced from a [senior's work.](https://isss608-kjcpaas.netlify.app/take-home_exs/ex3/take-home_ex3#mini-challenge-3) In this case, I also added a `direction` parameter to allow for further filtering.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\nlibrary(tidygraph)\nlibrary(dplyr)\nextract_subnetwork <- function(graph, node_name, \n                               distance = NULL, \n                               direction = c(\"all\", \"in\", \"out\"),\n                               edge_types = NULL,\n                               node_types = NULL) {\n  direction <- match.arg(direction)\n  node <- which(V(graph)$name == node_name)\n  if (length(node) == 0) stop(\"Node name not found in graph.\")\n  distance <- ifelse(is.null(distance), length(graph), distance)\n\n  mode <- switch(direction,\n                 all = \"all\",\n                 `in` = \"in\",\n                 out = \"out\")\n\n  igraph_subgraph <- induced_subgraph(graph, vids = ego(graph, node, order = distance, mode = mode)[[1]])\n\n  nodes_df <- igraph::as_data_frame(igraph_subgraph, what = \"vertices\")\n  edges_df <- igraph::as_data_frame(igraph_subgraph, what = \"edges\")\n\n  if (!is.null(edge_types)) {\n    edges_df <- edges_df %>% dplyr::filter(`Edge Type` %in% edge_types)\n  }\n\n  if (!is.null(node_types)) {\n    nodes_df <- nodes_df %>% dplyr::filter(`Node Type` %in% node_types)\n  }\n\n  used_node_ids <- unique(c(edges_df$from, edges_df$to))\n  nodes_df <- nodes_df %>% dplyr::filter(name %in% used_node_ids)\n\n  tidygraph::tbl_graph(nodes = nodes_df, edges = edges_df, directed = igraph::is_directed(graph))\n}\n```\n:::\n\n\n\nThere are three sub-questions in Mini-Challenge 1. I have chosen Question 1, and the following is the process I used to solve it:\n\n1.  Who has she been most influenced by over time?\n\nSailor Shift--\\>Person --\\> work\n\n1.  Who has she collaborated with and directly or indirectly influenced?\n\n1.1 Who has she collaborated with\n\nSailor Shift--\\>Person --\\> work (direct)\n\nSailor Shift--\\>work--\\>Person(indirect)\n\n1.2Who has she directly or indirectly influenced?\n\nSailor Shift--\\>Person --\\> work (direct)\n\nSailor Shift--\\>work--\\>Person(indirect)\n\n3.How has she influenced collaborators of the broader Oceanus Folk community?\n\nSailor Shift--\\>Person/community--\\>Work(direct)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-8772eab37b56363bf285\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8772eab37b56363bf285\">{\"x\":{\"diagram\":\"\\ndigraph sailor_vertical {\\n  graph [layout = dot, rankdir = LR]\\n\\n  # 样式\\n  node [fontname = Helvetica, style = filled, fillcolor = \\\"white\\\", shape = box]\\n  edge [fontname = Helvetica]\\n\\n  # 左列：问题（竖排）\\n  Q1 [label = \\\"Q1:\\\\nInfluenced by others\\\", shape = diamond]\\n  Q2 [label = \\\"Q2:\\\\nCollaboration & Influence\\\", shape = diamond]\\n  Q3 [label = \\\"Q3:\\\\nInfluence on Oceanus Folk\\\", shape = diamond]\\n\\n  # 右列：回答（每个问题对应多个，竖着排，不强制 rank）\\n  Q1a [label = \\\"Person → Sailor Shift → Work\\\"]\\n  Q1b [label = \\\"Work → Sailor Shift → Work\\\"]\\n\\n  Q2a [label = \\\"Sailor Shift → Person → Work\\\\n(direct collaboration)\\\"]\\n  Q2b [label = \\\"Sailor Shift → Work → Person\\\\n(indirect collaboration)\\\"]\\n  Q2c [label = \\\"Sailor Shift → Person → Work\\\\n(direct influence)\\\"]\\n  Q2d [label = \\\"Sailor Shift → Work → Person\\\\n(indirect influence)\\\"]\\n\\n  Q3a [label = \\\"Sailor Shift → Person/Community → Work\\\\n(Oceanus Folk)\\\"]\\n\\n \\n  Q1 -> Q1a\\n  Q1 -> Q1b\\n\\n  Q2 -> Q2a\\n  Q2 -> Q2b\\n  Q2 -> Q2c\\n  Q2 -> Q2d\\n\\n  Q3 -> Q3a\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n### Who has she collaborated with and directly or indirectly influenced?  & \n\n### How has she influenced collaborators of the broader Oceanus Folk community\n\nFirst we will first answer ：Who has she influenced ?\n\nAnd here is the directly neighbours :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\nsailor_index <- nodes_tbl %>%\n  filter(name == \"Sailor Shift\") %>%\n  pull(index)\n\ninfluence_edges <- c(\"InStyleOf\", \"CoverOf\", \"InterpolatesFrom\", \"LyricalReferenceTo\", \"DirectlySamples\")\n\nedges_from_sailor <- edges_tbl %>%\n  filter(to == sailor_index & `Edge Type` %in% influence_edges)\n\ninfluenced1 <- edges_from_sailor %>%\n  left_join(nodes_tbl, by = c(\"from\" = \"index\")) %>%\n  select(name, `Edge Type`, everything())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ninfluenced1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 16\n  name            `Edge Type` source target   key  from    to `Node Type` single\n  <chr>           <chr>        <int>  <int> <int> <int> <int> <chr>       <lgl> \n1 Cassette Future InStyleOf    17022  17255     0 17023 17256 MusicalGro… NA    \n2 Silver Veil     LyricalRef…  17032  17255     0 17033 17256 MusicalGro… NA    \n3 The Phantom Op… Interpolat…  17063  17255     0 17064 17256 MusicalGro… NA    \n4 The Hollow Mon… InStyleOf    17110  17255     0 17111 17256 MusicalGro… NA    \n5 Cassian Storm   LyricalRef…  17126  17255     0 17127 17256 Person      NA    \n6 Claire Holmes   Interpolat…  17155  17255     0 17156 17256 Person      NA    \n7 Copper Canyon … DirectlySa…  17361  17255     0 17362 17256 MusicalGro… NA    \n# ℹ 7 more variables: release_date <chr>, genre <chr>, notable <lgl>, id <int>,\n#   written_date <chr>, stage_name <chr>, notoriety_date <chr>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsubgraph_in <- extract_subnetwork(\n  graph, \n  node_name = \"Sailor Shift\", \n  distance = 3, \n  direction = \"in\"\n)\n\nedges_vn <- igraph::as_data_frame(subgraph_in, what = \"edges\") %>%\n  filter(`Edge Type` != \"ProducerOf\") %>%\n  rename(from = from, to = to, label = `Edge Type`)\n\nnodes_vn <- igraph::as_data_frame(subgraph_in, what = \"vertices\") %>%\n  mutate(id = name, label = name, group = `Node Type`)\n\nused_nodes <- unique(c(edges_vn$from, edges_vn$to))\nnodes_vn <- nodes_vn %>% filter(id %in% used_nodes)\n\nvisNetwork(nodes_vn, edges_vn, height = \"800px\", width = \"100%\") %>%\n  visEdges(arrows = \"to\") %>%\n  visOptions(\n    highlightNearest = list(enabled = TRUE, degree = 3, hover = TRUE),\n    nodesIdSelection = TRUE,\n    selectedBy = \"group\"\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 1234) %>%\n  visInteraction(navigationButtons = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-a117548d8d793ffdb939\" style=\"width:100%;height:800px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a117548d8d793ffdb939\">{\"x\":{\"nodes\":{\"Node Type\":[\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"MusicalGroup\"],\"name\":[\"Zara Quinn\",\"Milo Knight\",\"Cassette Future\",\"Eliza Brooks\",\"Jasper Reed\",\"Silver Veil\",\"Juno Ray\",\"Savannah Teal\",\"The Phantom Operators\",\"Chloe Montgomery\",\"Nathaniel Brooks\",\"Clara Davis\",\"The Hollow Monarchs\",\"Cassian Storm\",\"Claire Holmes\",\"Sailor Shift\",\"Beatrice Albright\",\"Daniel O'Connell\",\"Copper Canyon Ghosts\"],\"single\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"release_date\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"genre\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"notable\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"id\":[\"Zara Quinn\",\"Milo Knight\",\"Cassette Future\",\"Eliza Brooks\",\"Jasper Reed\",\"Silver Veil\",\"Juno Ray\",\"Savannah Teal\",\"The Phantom Operators\",\"Chloe Montgomery\",\"Nathaniel Brooks\",\"Clara Davis\",\"The Hollow Monarchs\",\"Cassian Storm\",\"Claire Holmes\",\"Sailor Shift\",\"Beatrice Albright\",\"Daniel O'Connell\",\"Copper Canyon Ghosts\"],\"written_date\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"stage_name\":[null,null,null,\"Midnight Atlas\",null,null,null,null,null,\"Lane Taylor\",\"David Cole\",\"Rosemary Banks\",null,\"Seraphina Vale\",\"Jaye Finch\",null,\"Bea Azure\",\"Kael Storm\",null],\"notoriety_date\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"label\":[\"Zara Quinn\",\"Milo Knight\",\"Cassette Future\",\"Eliza Brooks\",\"Jasper Reed\",\"Silver Veil\",\"Juno Ray\",\"Savannah Teal\",\"The Phantom Operators\",\"Chloe Montgomery\",\"Nathaniel Brooks\",\"Clara Davis\",\"The Hollow Monarchs\",\"Cassian Storm\",\"Claire Holmes\",\"Sailor Shift\",\"Beatrice Albright\",\"Daniel O'Connell\",\"Copper Canyon Ghosts\"],\"group\":[\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"Person\",\"MusicalGroup\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"MusicalGroup\"]},\"edges\":{\"from\":[\"Zara Quinn\",\"Milo Knight\",\"Cassette Future\",\"Eliza Brooks\",\"Jasper Reed\",\"Silver Veil\",\"Juno Ray\",\"Savannah Teal\",\"The Phantom Operators\",\"Chloe Montgomery\",\"Nathaniel Brooks\",\"Clara Davis\",\"The Hollow Monarchs\",\"Cassian Storm\",\"Claire Holmes\",\"Beatrice Albright\",\"Daniel O'Connell\",\"Copper Canyon Ghosts\"],\"to\":[\"Cassette Future\",\"Cassette Future\",\"Sailor Shift\",\"Silver Veil\",\"Silver Veil\",\"Sailor Shift\",\"The Phantom Operators\",\"The Phantom Operators\",\"Sailor Shift\",\"The Hollow Monarchs\",\"The Hollow Monarchs\",\"The Hollow Monarchs\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Copper Canyon Ghosts\",\"Copper Canyon Ghosts\",\"Sailor Shift\"],\"label\":[\"MemberOf\",\"MemberOf\",\"InStyleOf\",\"MemberOf\",\"MemberOf\",\"LyricalReferenceTo\",\"MemberOf\",\"MemberOf\",\"InterpolatesFrom\",\"MemberOf\",\"MemberOf\",\"MemberOf\",\"InStyleOf\",\"LyricalReferenceTo\",\"InterpolatesFrom\",\"MemberOf\",\"MemberOf\",\"DirectlySamples\"],\"source\":[17020,17021,17022,17030,17031,17032,17061,17062,17063,17107,17108,17109,17110,17126,17155,17349,17355,17361],\"target\":[17022,17022,17255,17032,17032,17255,17063,17063,17255,17110,17110,17110,17255,17255,17255,17361,17361,17255],\"key\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":\"to\"},\"interaction\":{\"hover\":true,\"navigationButtons\":true,\"zoomSpeed\":1},\"layout\":{\"randomSeed\":1234}},\"groups\":[\"Person\",\"MusicalGroup\"],\"width\":\"100%\",\"height\":\"800px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false,\"variable\":\"group\",\"main\":\"Select by group\",\"values\":[\"MusicalGroup\",\"Person\"]},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":true,\"degree\":3,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true},\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_vn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         Node Type                  name single release_date\nZara Quinn                  Person            Zara Quinn     NA         <NA>\nMilo Knight                 Person           Milo Knight     NA         <NA>\nCassette Future       MusicalGroup       Cassette Future     NA         <NA>\nEliza Brooks                Person          Eliza Brooks     NA         <NA>\nJasper Reed                 Person           Jasper Reed     NA         <NA>\nSilver Veil           MusicalGroup           Silver Veil     NA         <NA>\nJuno Ray                    Person              Juno Ray     NA         <NA>\nSavannah Teal               Person         Savannah Teal     NA         <NA>\nThe Phantom Operators MusicalGroup The Phantom Operators     NA         <NA>\nChloe Montgomery            Person      Chloe Montgomery     NA         <NA>\nNathaniel Brooks            Person      Nathaniel Brooks     NA         <NA>\nClara Davis                 Person           Clara Davis     NA         <NA>\nThe Hollow Monarchs   MusicalGroup   The Hollow Monarchs     NA         <NA>\nCassian Storm               Person         Cassian Storm     NA         <NA>\nClaire Holmes               Person         Claire Holmes     NA         <NA>\nSailor Shift                Person          Sailor Shift     NA         <NA>\nBeatrice Albright           Person     Beatrice Albright     NA         <NA>\nDaniel O'Connell            Person      Daniel O'Connell     NA         <NA>\nCopper Canyon Ghosts  MusicalGroup  Copper Canyon Ghosts     NA         <NA>\n                      genre notable                    id written_date\nZara Quinn             <NA>      NA            Zara Quinn         <NA>\nMilo Knight            <NA>      NA           Milo Knight         <NA>\nCassette Future        <NA>      NA       Cassette Future         <NA>\nEliza Brooks           <NA>      NA          Eliza Brooks         <NA>\nJasper Reed            <NA>      NA           Jasper Reed         <NA>\nSilver Veil            <NA>      NA           Silver Veil         <NA>\nJuno Ray               <NA>      NA              Juno Ray         <NA>\nSavannah Teal          <NA>      NA         Savannah Teal         <NA>\nThe Phantom Operators  <NA>      NA The Phantom Operators         <NA>\nChloe Montgomery       <NA>      NA      Chloe Montgomery         <NA>\nNathaniel Brooks       <NA>      NA      Nathaniel Brooks         <NA>\nClara Davis            <NA>      NA           Clara Davis         <NA>\nThe Hollow Monarchs    <NA>      NA   The Hollow Monarchs         <NA>\nCassian Storm          <NA>      NA         Cassian Storm         <NA>\nClaire Holmes          <NA>      NA         Claire Holmes         <NA>\nSailor Shift           <NA>      NA          Sailor Shift         <NA>\nBeatrice Albright      <NA>      NA     Beatrice Albright         <NA>\nDaniel O'Connell       <NA>      NA      Daniel O'Connell         <NA>\nCopper Canyon Ghosts   <NA>      NA  Copper Canyon Ghosts         <NA>\n                          stage_name notoriety_date                 label\nZara Quinn                      <NA>           <NA>            Zara Quinn\nMilo Knight                     <NA>           <NA>           Milo Knight\nCassette Future                 <NA>           <NA>       Cassette Future\nEliza Brooks          Midnight Atlas           <NA>          Eliza Brooks\nJasper Reed                     <NA>           <NA>           Jasper Reed\nSilver Veil                     <NA>           <NA>           Silver Veil\nJuno Ray                        <NA>           <NA>              Juno Ray\nSavannah Teal                   <NA>           <NA>         Savannah Teal\nThe Phantom Operators           <NA>           <NA> The Phantom Operators\nChloe Montgomery         Lane Taylor           <NA>      Chloe Montgomery\nNathaniel Brooks          David Cole           <NA>      Nathaniel Brooks\nClara Davis           Rosemary Banks           <NA>           Clara Davis\nThe Hollow Monarchs             <NA>           <NA>   The Hollow Monarchs\nCassian Storm         Seraphina Vale           <NA>         Cassian Storm\nClaire Holmes             Jaye Finch           <NA>         Claire Holmes\nSailor Shift                    <NA>           <NA>          Sailor Shift\nBeatrice Albright          Bea Azure           <NA>     Beatrice Albright\nDaniel O'Connell          Kael Storm           <NA>      Daniel O'Connell\nCopper Canyon Ghosts            <NA>           <NA>  Copper Canyon Ghosts\n                             group\nZara Quinn                  Person\nMilo Knight                 Person\nCassette Future       MusicalGroup\nEliza Brooks                Person\nJasper Reed                 Person\nSilver Veil           MusicalGroup\nJuno Ray                    Person\nSavannah Teal               Person\nThe Phantom Operators MusicalGroup\nChloe Montgomery            Person\nNathaniel Brooks            Person\nClara Davis                 Person\nThe Hollow Monarchs   MusicalGroup\nCassian Storm               Person\nClaire Holmes               Person\nSailor Shift                Person\nBeatrice Albright           Person\nDaniel O'Connell            Person\nCopper Canyon Ghosts  MusicalGroup\n```\n\n\n:::\n:::\n\n\n\nSecond we will first answer ：How has she influenced collaborators of the broader Oceanus Folk community?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\ncreator_names <- c(\n  \"Zara Quinn\", \"Milo Knight\", \"Cassette Future\", \"Eliza Brooks\",\n  \"Jasper Reed\", \"Silver Veil\", \"Juno Ray\", \"Savannah Teal\",\n  \"The Phantom Operators\", \"Chloe Montgomery\", \"Nathaniel Brooks\", \"Clara Davis\",\n  \"The Hollow Monarchs\", \"Cassian Storm\", \"Claire Holmes\", \"Beatrice Albright\",\n  \"Daniel O'Connell\", \"Copper Canyon Ghosts\"\n)\n\ncreator_ids <- nodes_tbl %>%\n  filter(name %in% creator_names) %>%\n  pull(index)\n\ntarget_edge_types <- c(\"PerformerOf\", \"ComposerOf\", \"LyricistOf\", \"ProducerOf\")\n\nedges_out <- edges_tbl %>%\n  filter(from %in% creator_ids, `Edge Type` %in% target_edge_types)\n\nedges_out_full <- edges_out %>%\n  left_join(nodes_tbl %>% mutate(index = row_number()), by = c(\"to\" = \"index\")) %>%\n  select(from, to, `Edge Type`, name, `Node Type`, release_date,genre,notable,notoriety_date)\n\nedges_out_full <- edges_out_full %>%\n  left_join(nodes_tbl %>% select(index, creator_name = name), by = c(\"from\" = \"index\")) %>%\n  select(creator_name, `Edge Type`, name, `Node Type`, release_date,genre,notable,notoriety_date)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_oceanus <- edges_out_full %>%\n  filter(genre == \"Oceanus Folk\")\nedges_oceanus\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 29 × 8\n   creator_name      `Edge Type` name     `Node Type` release_date genre notable\n   <chr>             <chr>       <chr>    <chr>       <chr>        <chr> <lgl>  \n 1 Beatrice Albright PerformerOf Tideswo… Album       2031         Ocea… TRUE   \n 2 Beatrice Albright LyricistOf  Tideswo… Album       2031         Ocea… TRUE   \n 3 Beatrice Albright PerformerOf Tideswo… Album       2031         Ocea… TRUE   \n 4 Beatrice Albright PerformerOf The Sir… Song        2031         Ocea… TRUE   \n 5 Beatrice Albright PerformerOf Whisper… Song        2031         Ocea… TRUE   \n 6 Beatrice Albright PerformerOf Moonlit… Song        2031         Ocea… TRUE   \n 7 Beatrice Albright PerformerOf Seven F… Song        2031         Ocea… TRUE   \n 8 Beatrice Albright LyricistOf  Tide-Wo… Album       2034         Ocea… TRUE   \n 9 Beatrice Albright PerformerOf Tide-Wo… Album       2034         Ocea… TRUE   \n10 Beatrice Albright LyricistOf  The Sun… Album       2035         Ocea… TRUE   \n# ℹ 19 more rows\n# ℹ 1 more variable: notoriety_date <chr>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(visNetwork)\n\n\nedges_sailor <- edges_all %>%\n  filter(to == \"Sailor Shift\") %>%\n  filter(`Edge Type` %in% c(\"InStyleOf\", \"LyricalReferenceTo\", \"CoverOf\", \"InterpolatesFrom\", \"DirectlySamples\")) %>%\n  select(from, to, `Edge Type`)\n\ncreator_work_nodes <- unique(c(edges_oceanus$creator_name, edges_oceanus$name))\n\nall_node_names <- union(\n  creator_work_nodes,\n  unique(c(edges_sailor$from, edges_sailor$to, \"Sailor Shift\", \"Copper Canyon Ghosts\"))  \n)\n\nnodes_vn <- nodes_tbl %>%\n  filter(name %in% all_node_names) %>%\n  mutate(\n    id = index,\n    label = name,\n    group = `Node Type`,\n    color.background = ifelse(name == \"Sailor Shift\", \"gold\", NA),  # 高亮 Sailor\n    shape = ifelse(name == \"Sailor Shift\", \"star\", \"dot\")\n  )\n\nedges_vn_creator <- edges_oceanus %>%\n  rename(from = creator_name, to = name, label = `Edge Type`) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"from\" = \"name\")) %>%\n  rename(from_id = id) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"to\" = \"name\")) %>%\n  rename(to_id = id) %>%\n  mutate(length = NA) %>%\n  select(from = from_id, to = to_id, label, length) %>%\n  filter(!is.na(from) & !is.na(to))\n\nedges_vn_sailor <- edges_sailor %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"from\" = \"name\")) %>%\n  rename(from_id = id) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"to\" = \"name\")) %>%\n  rename(to_id = id) %>%\n  mutate(length = NA) %>%\n  select(from = from_id, to = to_id, label = `Edge Type`, length) %>%\n  filter(!is.na(from) & !is.na(to))\n\nforced_edge <- tibble(\n  from = \"Copper Canyon Ghosts\",\n  to = \"Sailor Shift\",\n  label = \"DirectlySamples\",\n  length = 400\n)\n\nforced_edge_ids <- forced_edge %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"from\" = \"name\")) %>%\n  rename(from_id = id) %>%\n  left_join(nodes_vn %>% select(name, id), by = c(\"to\" = \"name\")) %>%\n  rename(to_id = id) %>%\n  select(from = from_id, to = to_id, label, length) %>%\n  filter(!is.na(from) & !is.na(to))\n\nedges_final <- bind_rows(\n  edges_vn_creator,\n  edges_vn_sailor,\n  forced_edge_ids\n)\n\nvisNetwork(nodes_vn, edges_final, height = \"700px\", width = \"100%\") %>%\n  visEdges(arrows = \"to\") %>%\n  visOptions(\n    highlightNearest = TRUE,\n    nodesIdSelection = TRUE,\n    selectedBy = \"group\"\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 42) %>%\n  visPhysics(\n    solver = \"forceAtlas2Based\",\n    forceAtlas2Based = list(gravitationalConstant = -80),\n    stabilization = list(enabled = TRUE, iterations = 100)\n  )\n```\n:::\n\n\n\nIndirectly- We want to explore through the songs and the albums,and then find who she has influenced,but the result seems to 0.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfluence_edges <- c(\"InStyleOf\", \"CoverOf\", \"InterpolatesFrom\", \"LyricalReferenceTo\", \"DirectlySamples\")\n\nedges_to_sailor <- edges_all %>%\n  filter(\n    to == \"Sailor Shift\",\n    `Edge Type` %in% influence_edges\n  )\n\nedges_to_sailor_full <- edges_to_sailor %>%\n  left_join(nodes_all %>% select(name, `Node Type`), by = c(\"from\" = \"name\")) %>%\n  rename(\n    `From Name` = from,\n    `From Type` = `Node Type`\n  ) %>%\n  mutate(\n    `To Name` = \"Sailor Shift\",\n    `To Type` = \"Person\"\n  ) %>%\n  select(`From Name`, `From Type`, `To Name`, `To Type`, `Edge Type`)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_to_sailor_full\n```\n:::\n\n\n\n### Who has she been most influenced by over time?\n\nIn order to answer this question,we need to divide the question into three sub questions:\n\n1.Directly or Indirectly been influenced?\n\n2.If the starting node is Sailor ,what and who is the next node? Her works , Groups, Other work?\n\n3.How to answer the question of influenced by over time?\n\nFrom the not very perfect visnetwork plot, we firstly see what she have produce and then explore.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubgraph_in <- extract_subnetwork(\n  graph, \n  node_name = \"Sailor Shift\", \n  distance = 5, \n  direction = \"out\"\n)\n\nsubgraph_igraph <- as.igraph(subgraph_in)\n\nnodes_all <- igraph::as_data_frame(subgraph_igraph, what = \"vertices\")\nedges_all <- igraph::as_data_frame(subgraph_igraph, what = \"edges\")\n\nsailor_id <- nodes_all$name[nodes_all$name == \"Sailor Shift\"]\nedges_1st <- edges_all %>% filter(from == \"Sailor Shift\")\n\nvalid_targets <- edges_1st %>%\n  left_join(nodes_all, by = c(\"to\" = \"name\")) %>%\n  filter(`Node Type` %in% c(\"MusicalGroup\", \"Song\", \"Album\",\"RecordLabel\")) %>%\n  pull(to)\n\nvalid_node_ids <- unique(c(\"Sailor Shift\", valid_targets))\nedges_vn <- edges_all %>% \n  filter(from %in% valid_node_ids | to %in% valid_node_ids)\n\nused_nodes <- unique(c(edges_vn$from, edges_vn$to))\nnodes_vn <- nodes_all %>%\n  filter(name %in% used_nodes) %>%\n  mutate(id = name, label = name, group = `Node Type`)\n\nedges_vn <- edges_vn %>%\n  mutate(\n    label = `Edge Type`, \n    title = paste0(\"Edge Type: \", `Edge Type`)  \n  )\n\nvisNetwork(nodes_vn, edges_vn, height = \"800px\", width = \"100%\") %>%\n  visEdges(\n    arrows = \"to\",\n    font = list(\n      size = 12,         \n      align = \"middle\", \n      color = \"black\"    \n    )\n  ) %>%  \n  visOptions(\n    highlightNearest = list(enabled = TRUE, degree = 4, hover = TRUE),\n    nodesIdSelection = TRUE,\n    selectedBy = \"group\"\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 1234) %>%\n  visInteraction(navigationButtons = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-6fa6220fda18299509fd\" style=\"width:100%;height:800px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-6fa6220fda18299509fd\">{\"x\":{\"nodes\":{\"Node Type\":[\"Song\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Song\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"MusicalGroup\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Person\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"MusicalGroup\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Song\"],\"name\":[\"Bold Without Apology\",\"Hallowed Transaction\",\"Susurros de Pasión\",\"Altitude of Mistakes\",\"Our Inevitable Path\",\"When the Bar Lights Go Up\",\"Reflejo Interior\",\"Echoes of Forgotten Light\",\"Für uns alle zusammen\",\"Partisan's Lament\",\"Dreamscape of Judgment\",\"Twelve Bells of Augsburg\",\"Parallel Memories\",\"Divergent Memories\",\"Provence Aria\",\"Coastal Whispers of Biscay\",\"Exoskeleton Dissolve\",\"Silent Steps in the Forest's Embrace\",\"Folklore's Heartbeat\",\"The Long Way Home\",\"Weathered Miles\",\"Addicted to Your Heartache\",\"Twilight's Threshold\",\"The Crown We Wear\",\"Sacred Fragments\",\"Harvest Dance at Ler Valley\",\"Neon Heartbeat\",\"Ballads for the End of Time\",\"Melancholy Circuitry\",\"Drifting Between the Stars and the Sea\",\"Artificial Sunsets\",\"Electric Reverie\",\"Ballads for the Low Tide\",\"The Salty Wakes\",\"The Fiddle & The Fjord\",\"Echoes of the Old Way\",\"Runes & Reverie\",\"Blood & Heather\",\"Mist Over Skye\",\"Where the Ravens Roam\",\"Storm & Stone\",\"The Wanderer's Oath\",\"Silver and Salt\",\"Lost at Sea\",\"The Icebound Maiden\",\"Echoes of Skalds\",\"Wild Hunt Waltz\",\"Tides of Echos\",\"Hidden Depths\",\"Sailor Shift\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Sunken Bell Song\",\"Dancer of the Dappled Light\",\"Whispers in the Fronds\",\"The Angler's Lantern\",\"Deepsea Fireflies\",\"Sandpiper's Serenade\",\"Salt-Kissed Rhymes\",\"Tidepool Epigrams\",\"Tidal Pop Waves\",\"Salty Dreams\",\"The Current & The Chord\",\"Coral Beats\",\"Tides & Ballads\",\"Oceanbound\",\"Echoes of the Deep\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Sun-Drenched Daydream\",\"Chord of the Deep\",\"Heart of the Habitat\",\"Reef Rhythm\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Into the Current\",\"Barnacle Heart\",\"Fog & Fiddle\",\"The Fisherman's Prayer\",\"Stormsong\",\"Salt in My Veins\",\"The Last Mariner\",\"The Saltwater Weavers\",\"Beneath the Coral Moon\",\"Salt-Stained Chronicles\",\"The Kelp Forest Ballads\",\"Tempest's Wake\",\"Tripping on the Water\",\"The One\",\"Alight\",\"Albatross\",\"By the Stars\",\"The Tide Singer's Knot\",\"Drowned Harbor\",\"Wreck and Reverie\",\"Ossuary of the Deep\",\"Phantom Currents\",\"Lodestone & Lament\",\"Where the Lanterns Fade\",\"The Undertow Waltz\",\"Sable Waves\",\"Blackwater Hymn\",\"The Coral Spire\",\"Wake Drinker\",\"Vanishing Point\",\"The Sompass Spins\",\"Tidesworn Ballads\",\"Submerged Sonatas\",\"Seashell Serenade\"],\"single\":[false,null,true,true,true,false,false,true,true,true,true,true,false,true,true,true,true,true,true,null,true,null,true,true,true,true,null,null,null,null,null,null,null,null,null,null,null,null,false,false,true,true,false,false,false,true,false,null,null,null,null,null,null,null,true,false,false,true,false,false,true,false,null,null,null,null,null,null,null,true,false,false,false,true,false,false,false,false,true,false,false,true,true,false,false,null,null,null,null,null,true,false,true,false,false,null,null,null,null,null,null,true,false,true,false,true,false,false,false,null,null,true],\"release_date\":[\"2010\",\"2017\",\"2004\",\"2015\",\"2017\",\"2000\",\"1983\",\"2004\",\"2017\",\"2030\",\"2023\",\"2026\",\"2028\",\"2017\",\"2023\",\"2031\",\"2020\",\"2023\",\"2020\",\"2023\",\"2023\",\"2004\",\"2007\",\"2022\",\"2003\",\"2010\",\"2031\",\"2033\",\"2033\",\"2034\",\"2035\",\"2038\",\"2037\",null,null,\"1980\",\"1981\",\"1982\",\"1980\",\"1980\",\"1980\",\"1981\",\"1981\",\"1981\",\"1982\",\"1982\",\"1982\",\"2029\",\"2031\",null,null,\"2024\",\"2025\",\"2026\",\"2024\",\"2024\",\"2024\",\"2025\",\"2025\",\"2026\",\"2026\",\"2026\",\"2028\",\"2030\",\"2032\",\"2034\",\"2036\",\"2038\",\"2040\",\"2028\",\"2028\",\"2028\",\"2028\",\"2030\",\"2030\",\"2030\",\"2032\",\"2034\",\"2034\",\"2034\",\"2036\",\"2036\",\"2038\",\"2040\",\"2040\",null,\"1995\",\"1997\",\"1999\",\"2001\",\"1995\",\"1997\",\"1999\",\"2001\",\"2001\",null,null,\"2005\",\"2008\",\"2010\",\"2013\",\"2005\",\"2005\",\"2008\",\"2010\",\"2010\",\"2013\",\"2013\",\"2013\",\"2031\",\"2031\",\"2030\"],\"genre\":[\"Indie Rock\",\"Doom Metal\",\"Synthwave\",\"Americana\",\"Indie Folk\",\"Emo/Pop Punk\",\"Americana\",\"Alternative Rock\",\"Alternative Rock\",\"Indie Pop\",\"Symphonic Metal\",\"Psychedelic Rock\",\"Dream Pop\",\"Indie Folk\",\"Indie Rock\",\"Alternative Rock\",\"Indie Rock\",\"Avant-Garde Folk\",\"Blues Rock\",\"Dream Pop\",\"Doom Metal\",\"Southern Gothic Rock\",\"Synthwave\",\"Indie Rock\",\"Synthwave\",\"Psychedelic Rock\",\"Synthwave\",\"Oceanus Folk\",\"Americana\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",null,null,\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Celtic Folk\",\"Oceanus Folk\",\"Oceanus Folk\",null,null,\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",null,\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",null,null,\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\",\"Oceanus Folk\"],\"notable\":[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,null,null,true,true,true,false,false,false,false,false,false,false,false,false,true,true,null,null,true,true,true,false,false,false,false,false,false,true,false,true,true,true,true,true,true,true,false,true,false,false,false,false,false,false,true,false,false,true,false,true,false,false,null,true,true,true,true,false,false,false,false,false,null,null,true,true,true,true,false,false,false,true,false,false,false,false,true,true,true],\"id\":[\"Bold Without Apology\",\"Hallowed Transaction\",\"Susurros de Pasión\",\"Altitude of Mistakes\",\"Our Inevitable Path\",\"When the Bar Lights Go Up\",\"Reflejo Interior\",\"Echoes of Forgotten Light\",\"Für uns alle zusammen\",\"Partisan's Lament\",\"Dreamscape of Judgment\",\"Twelve Bells of Augsburg\",\"Parallel Memories\",\"Divergent Memories\",\"Provence Aria\",\"Coastal Whispers of Biscay\",\"Exoskeleton Dissolve\",\"Silent Steps in the Forest's Embrace\",\"Folklore's Heartbeat\",\"The Long Way Home\",\"Weathered Miles\",\"Addicted to Your Heartache\",\"Twilight's Threshold\",\"The Crown We Wear\",\"Sacred Fragments\",\"Harvest Dance at Ler Valley\",\"Neon Heartbeat\",\"Ballads for the End of Time\",\"Melancholy Circuitry\",\"Drifting Between the Stars and the Sea\",\"Artificial Sunsets\",\"Electric Reverie\",\"Ballads for the Low Tide\",\"The Salty Wakes\",\"The Fiddle & The Fjord\",\"Echoes of the Old Way\",\"Runes & Reverie\",\"Blood & Heather\",\"Mist Over Skye\",\"Where the Ravens Roam\",\"Storm & Stone\",\"The Wanderer's Oath\",\"Silver and Salt\",\"Lost at Sea\",\"The Icebound Maiden\",\"Echoes of Skalds\",\"Wild Hunt Waltz\",\"Tides of Echos\",\"Hidden Depths\",\"Sailor Shift\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Sunken Bell Song\",\"Dancer of the Dappled Light\",\"Whispers in the Fronds\",\"The Angler's Lantern\",\"Deepsea Fireflies\",\"Sandpiper's Serenade\",\"Salt-Kissed Rhymes\",\"Tidepool Epigrams\",\"Tidal Pop Waves\",\"Salty Dreams\",\"The Current & The Chord\",\"Coral Beats\",\"Tides & Ballads\",\"Oceanbound\",\"Echoes of the Deep\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Sun-Drenched Daydream\",\"Chord of the Deep\",\"Heart of the Habitat\",\"Reef Rhythm\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Into the Current\",\"Barnacle Heart\",\"Fog & Fiddle\",\"The Fisherman's Prayer\",\"Stormsong\",\"Salt in My Veins\",\"The Last Mariner\",\"The Saltwater Weavers\",\"Beneath the Coral Moon\",\"Salt-Stained Chronicles\",\"The Kelp Forest Ballads\",\"Tempest's Wake\",\"Tripping on the Water\",\"The One\",\"Alight\",\"Albatross\",\"By the Stars\",\"The Tide Singer's Knot\",\"Drowned Harbor\",\"Wreck and Reverie\",\"Ossuary of the Deep\",\"Phantom Currents\",\"Lodestone & Lament\",\"Where the Lanterns Fade\",\"The Undertow Waltz\",\"Sable Waves\",\"Blackwater Hymn\",\"The Coral Spire\",\"Wake Drinker\",\"Vanishing Point\",\"The Sompass Spins\",\"Tidesworn Ballads\",\"Submerged Sonatas\",\"Seashell Serenade\"],\"written_date\":[null,null,null,null,\"2017\",null,\"1983\",null,\"2017\",null,null,null,null,null,null,null,null,\"2023\",null,null,null,\"2000\",\"2007\",null,null,null,\"2030\",\"2032\",\"2032\",\"2033\",\"2034\",\"2037\",\"2036\",null,null,\"1979\",\"1980\",\"1981\",null,null,null,null,null,null,null,null,null,\"2028\",\"2030\",null,null,\"2023\",\"2024\",\"2025\",null,null,null,null,null,null,null,null,\"2027\",\"2029\",\"2031\",\"2033\",\"2035\",\"2037\",\"2039\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1994\",\"1996\",\"1998\",\"2000\",null,null,null,null,null,null,null,\"2004\",\"2007\",\"2009\",\"2012\",null,null,null,null,null,null,null,null,\"2030\",\"2030\",null],\"stage_name\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"notoriety_date\":[null,null,\"2004\",\"2015\",null,null,null,null,null,null,null,null,null,\"2017\",null,null,\"2020\",\"2023\",\"2033\",null,null,null,\"2007\",null,\"2003\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2030\"],\"label\":[\"Bold Without Apology\",\"Hallowed Transaction\",\"Susurros de Pasión\",\"Altitude of Mistakes\",\"Our Inevitable Path\",\"When the Bar Lights Go Up\",\"Reflejo Interior\",\"Echoes of Forgotten Light\",\"Für uns alle zusammen\",\"Partisan's Lament\",\"Dreamscape of Judgment\",\"Twelve Bells of Augsburg\",\"Parallel Memories\",\"Divergent Memories\",\"Provence Aria\",\"Coastal Whispers of Biscay\",\"Exoskeleton Dissolve\",\"Silent Steps in the Forest's Embrace\",\"Folklore's Heartbeat\",\"The Long Way Home\",\"Weathered Miles\",\"Addicted to Your Heartache\",\"Twilight's Threshold\",\"The Crown We Wear\",\"Sacred Fragments\",\"Harvest Dance at Ler Valley\",\"Neon Heartbeat\",\"Ballads for the End of Time\",\"Melancholy Circuitry\",\"Drifting Between the Stars and the Sea\",\"Artificial Sunsets\",\"Electric Reverie\",\"Ballads for the Low Tide\",\"The Salty Wakes\",\"The Fiddle & The Fjord\",\"Echoes of the Old Way\",\"Runes & Reverie\",\"Blood & Heather\",\"Mist Over Skye\",\"Where the Ravens Roam\",\"Storm & Stone\",\"The Wanderer's Oath\",\"Silver and Salt\",\"Lost at Sea\",\"The Icebound Maiden\",\"Echoes of Skalds\",\"Wild Hunt Waltz\",\"Tides of Echos\",\"Hidden Depths\",\"Sailor Shift\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Sunken Bell Song\",\"Dancer of the Dappled Light\",\"Whispers in the Fronds\",\"The Angler's Lantern\",\"Deepsea Fireflies\",\"Sandpiper's Serenade\",\"Salt-Kissed Rhymes\",\"Tidepool Epigrams\",\"Tidal Pop Waves\",\"Salty Dreams\",\"The Current & The Chord\",\"Coral Beats\",\"Tides & Ballads\",\"Oceanbound\",\"Echoes of the Deep\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Sun-Drenched Daydream\",\"Chord of the Deep\",\"Heart of the Habitat\",\"Reef Rhythm\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Into the Current\",\"Barnacle Heart\",\"Fog & Fiddle\",\"The Fisherman's Prayer\",\"Stormsong\",\"Salt in My Veins\",\"The Last Mariner\",\"The Saltwater Weavers\",\"Beneath the Coral Moon\",\"Salt-Stained Chronicles\",\"The Kelp Forest Ballads\",\"Tempest's Wake\",\"Tripping on the Water\",\"The One\",\"Alight\",\"Albatross\",\"By the Stars\",\"The Tide Singer's Knot\",\"Drowned Harbor\",\"Wreck and Reverie\",\"Ossuary of the Deep\",\"Phantom Currents\",\"Lodestone & Lament\",\"Where the Lanterns Fade\",\"The Undertow Waltz\",\"Sable Waves\",\"Blackwater Hymn\",\"The Coral Spire\",\"Wake Drinker\",\"Vanishing Point\",\"The Sompass Spins\",\"Tidesworn Ballads\",\"Submerged Sonatas\",\"Seashell Serenade\"],\"group\":[\"Song\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Song\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"MusicalGroup\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Person\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"MusicalGroup\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Song\"]},\"edges\":{\"from\":[\"Melancholy Circuitry\",\"Electric Reverie\",\"Electric Reverie\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"The Fiddle & The Fjord\",\"Tides of Echos\",\"Tides of Echos\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"The Kelp Forest Canticles\",\"Salty Dreams\",\"Salty Dreams\",\"Coral Beats\",\"Coral Beats\",\"Oceanbound\",\"Oceanbound\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Electric Eel Love\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Moon Over the Tide\",\"Barnacle Heart\",\"Fog & Fiddle\",\"Fog & Fiddle\",\"Stormsong\",\"Stormsong\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"The Saltwater Weavers\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Drowned Harbor\",\"Tidesworn Ballads\"],\"to\":[\"Twilight's Threshold\",\"Reflejo Interior\",\"Folklore's Heartbeat\",\"Echoes of the Old Way\",\"Runes & Reverie\",\"Blood & Heather\",\"Mist Over Skye\",\"Where the Ravens Roam\",\"Storm & Stone\",\"The Wanderer's Oath\",\"Silver and Salt\",\"Lost at Sea\",\"The Icebound Maiden\",\"Echoes of Skalds\",\"Wild Hunt Waltz\",\"The Long Way Home\",\"Weathered Miles\",\"Neon Heartbeat\",\"Ballads for the End of Time\",\"Melancholy Circuitry\",\"Drifting Between the Stars and the Sea\",\"Artificial Sunsets\",\"Electric Reverie\",\"Ballads for the Low Tide\",\"The Fiddle & The Fjord\",\"Tides of Echos\",\"Hidden Depths\",\"Ivy Echos\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Tidal Pop Waves\",\"Tidal Pop Waves\",\"Salty Dreams\",\"Salty Dreams\",\"The Current & The Chord\",\"The Current & The Chord\",\"Coral Beats\",\"Coral Beats\",\"Tides & Ballads\",\"Tides & Ballads\",\"Oceanbound\",\"Oceanbound\",\"Echoes of the Deep\",\"Echoes of the Deep\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Sun-Drenched Daydream\",\"Chord of the Deep\",\"Heart of the Habitat\",\"Reef Rhythm\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Into the Current\",\"Barnacle Heart\",\"Fog & Fiddle\",\"The Fisherman's Prayer\",\"Stormsong\",\"Salt in My Veins\",\"The Last Mariner\",\"The Saltwater Weavers\",\"Drowned Harbor\",\"Tidesworn Ballads\",\"Tidesworn Ballads\",\"Submerged Sonatas\",\"Submerged Sonatas\",\"Seashell Serenade\",\"The Salty Wakes\",\"The Fiddle & The Fjord\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Sunken Bell Song\",\"Dancer of the Dappled Light\",\"Whispers in the Fronds\",\"The Angler's Lantern\",\"Deepsea Fireflies\",\"Sandpiper's Serenade\",\"Salt-Kissed Rhymes\",\"Tidepool Epigrams\",\"The Saltwater Weavers\",\"The Tide Singer's Knot\",\"Hallowed Transaction\",\"Für uns alle zusammen\",\"Susurros de Pasión\",\"Partisan's Lament\",\"Sacred Fragments\",\"Harvest Dance at Ler Valley\",\"Bold Without Apology\",\"Altitude of Mistakes\",\"Addicted to Your Heartache\",\"Twelve Bells of Augsburg\",\"The Crown We Wear\",\"Echoes of Forgotten Light\",\"Parallel Memories\",\"Divergent Memories\",\"Silent Steps in the Forest's Embrace\",\"Our Inevitable Path\",\"Provence Aria\",\"Coastal Whispers of Biscay\",\"When the Bar Lights Go Up\",\"Exoskeleton Dissolve\",\"Beneath the Coral Moon\",\"Salt-Stained Chronicles\",\"The Kelp Forest Ballads\",\"Tempest's Wake\",\"Tripping on the Water\",\"The One\",\"Alight\",\"Albatross\",\"By the Stars\",\"Wreck and Reverie\",\"Ossuary of the Deep\",\"Phantom Currents\",\"Lodestone & Lament\",\"Where the Lanterns Fade\",\"The Undertow Waltz\",\"Sable Waves\",\"Blackwater Hymn\",\"The Coral Spire\",\"Wake Drinker\",\"Vanishing Point\",\"The Sompass Spins\",\"Dreamscape of Judgment\"],\"Edge Type\":[\"CoverOf\",\"InterpolatesFrom\",\"InStyleOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"InStyleOf\",\"InterpolatesFrom\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"InStyleOf\",\"LyricistOf\",\"LyricistOf\",\"DirectlySamples\",\"MemberOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"InStyleOf\",\"LyricalReferenceTo\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"InStyleOf\",\"InterpolatesFrom\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricalReferenceTo\",\"InStyleOf\",\"DirectlySamples\",\"CoverOf\",\"InStyleOf\",\"CoverOf\",\"InStyleOf\",\"CoverOf\",\"LyricalReferenceTo\",\"LyricalReferenceTo\",\"InterpolatesFrom\",\"InStyleOf\",\"CoverOf\",\"InStyleOf\",\"InStyleOf\",\"InterpolatesFrom\",\"LyricalReferenceTo\",\"InStyleOf\",\"InStyleOf\",\"InterpolatesFrom\",\"InStyleOf\",\"DirectlySamples\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"CoverOf\"],\"source\":[16999,17049,17049,17192,17192,17192,17192,17192,17192,17192,17192,17192,17192,17192,17192,17231,17231,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17255,17260,17260,17260,17260,17260,17260,17260,17260,17260,17260,17260,17260,17260,17260,17260,17261,17261,17273,17273,17275,17275,17277,17277,17279,17280,17280,17285,17286,17287,17287,17289,17290,17290,17292,17292,17299,17299,17299,17299,17299,17299,17299,17299,17299,17327,17327,17327,17327,17327,17327,17327,17327,17327,17327,17327,17327,17350],\"target\":[14893,7026,14107,17193,17194,17195,17196,17197,17198,17199,17200,17201,17202,17203,17204,14296,14352,16961,16989,16999,17047,17048,17049,17121,17192,17231,17252,17260,17260,17261,17262,17263,17272,17272,17273,17273,17274,17274,17275,17275,17276,17276,17277,17277,17278,17278,17279,17280,17281,17282,17283,17284,17285,17286,17287,17288,17289,17290,17291,17292,17293,17294,17299,17327,17350,17350,17356,17356,17410,17167,17192,17261,17262,17263,17264,17265,17266,17267,17268,17269,17270,17271,17299,17314,2197,9223,3881,9848,15855,16312,876,3986,14658,10534,14933,8207,10903,11254,13589,5574,12237,12685,6592,13014,17300,17301,17302,17303,17304,17305,17306,17307,17308,17328,17329,17330,17331,17332,17333,17334,17335,17336,17337,17338,17339,10016],\"key\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"label\":[\"CoverOf\",\"InterpolatesFrom\",\"InStyleOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"InStyleOf\",\"InterpolatesFrom\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"InStyleOf\",\"LyricistOf\",\"LyricistOf\",\"DirectlySamples\",\"MemberOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"InStyleOf\",\"LyricalReferenceTo\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"InStyleOf\",\"InterpolatesFrom\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricalReferenceTo\",\"InStyleOf\",\"DirectlySamples\",\"CoverOf\",\"InStyleOf\",\"CoverOf\",\"InStyleOf\",\"CoverOf\",\"LyricalReferenceTo\",\"LyricalReferenceTo\",\"InterpolatesFrom\",\"InStyleOf\",\"CoverOf\",\"InStyleOf\",\"InStyleOf\",\"InterpolatesFrom\",\"LyricalReferenceTo\",\"InStyleOf\",\"InStyleOf\",\"InterpolatesFrom\",\"InStyleOf\",\"DirectlySamples\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"CoverOf\"],\"title\":[\"Edge Type: CoverOf\",\"Edge Type: InterpolatesFrom\",\"Edge Type: InStyleOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: InStyleOf\",\"Edge Type: InterpolatesFrom\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: InStyleOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: DirectlySamples\",\"Edge Type: MemberOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: InStyleOf\",\"Edge Type: LyricalReferenceTo\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricistOf\",\"Edge Type: PerformerOf\",\"Edge Type: InStyleOf\",\"Edge Type: InterpolatesFrom\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: LyricalReferenceTo\",\"Edge Type: InStyleOf\",\"Edge Type: DirectlySamples\",\"Edge Type: CoverOf\",\"Edge Type: InStyleOf\",\"Edge Type: CoverOf\",\"Edge Type: InStyleOf\",\"Edge Type: CoverOf\",\"Edge Type: LyricalReferenceTo\",\"Edge Type: LyricalReferenceTo\",\"Edge Type: InterpolatesFrom\",\"Edge Type: InStyleOf\",\"Edge Type: CoverOf\",\"Edge Type: InStyleOf\",\"Edge Type: InStyleOf\",\"Edge Type: InterpolatesFrom\",\"Edge Type: LyricalReferenceTo\",\"Edge Type: InStyleOf\",\"Edge Type: InStyleOf\",\"Edge Type: InterpolatesFrom\",\"Edge Type: InStyleOf\",\"Edge Type: DirectlySamples\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: PerformerOf\",\"Edge Type: CoverOf\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":\"to\",\"font\":{\"size\":12,\"align\":\"middle\",\"color\":\"black\"}},\"interaction\":{\"hover\":true,\"navigationButtons\":true,\"zoomSpeed\":1},\"layout\":{\"randomSeed\":1234}},\"groups\":[\"Song\",\"Album\",\"MusicalGroup\",\"Person\"],\"width\":\"100%\",\"height\":\"800px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false,\"variable\":\"group\",\"main\":\"Select by group\",\"values\":[\"Album\",\"MusicalGroup\",\"Person\",\"Song\"]},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":true,\"degree\":4,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true},\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_1st <- edges_all %>% \n  filter(from == \"Sailor Shift\")\n\n\nedges_1st_full <- edges_1st %>%\n  left_join(nodes_all, by = c(\"to\" = \"name\")) %>%\n  select(from, to, `Edge Type`, `Node Type`)  \n\nedges_1st_full\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           from                                     to          Edge Type\n1  Sailor Shift                         Neon Heartbeat         LyricistOf\n2  Sailor Shift            Ballads for the End of Time         LyricistOf\n3  Sailor Shift                   Melancholy Circuitry         LyricistOf\n4  Sailor Shift Drifting Between the Stars and the Sea         LyricistOf\n5  Sailor Shift                     Artificial Sunsets         LyricistOf\n6  Sailor Shift                       Electric Reverie         LyricistOf\n7  Sailor Shift               Ballads for the Low Tide         LyricistOf\n8  Sailor Shift                 The Fiddle & The Fjord          InStyleOf\n9  Sailor Shift                         Tides of Echos         LyricistOf\n10 Sailor Shift                          Hidden Depths         LyricistOf\n11 Sailor Shift                              Ivy Echos    DirectlySamples\n12 Sailor Shift                              Ivy Echos           MemberOf\n13 Sailor Shift              The Kelp Forest Canticles         LyricistOf\n14 Sailor Shift                      Luminescent Tides         LyricistOf\n15 Sailor Shift                      Shoreline Sonnets         LyricistOf\n16 Sailor Shift                        Tidal Pop Waves         LyricistOf\n17 Sailor Shift                        Tidal Pop Waves        PerformerOf\n18 Sailor Shift                           Salty Dreams         LyricistOf\n19 Sailor Shift                           Salty Dreams        PerformerOf\n20 Sailor Shift                The Current & The Chord         LyricistOf\n21 Sailor Shift                The Current & The Chord        PerformerOf\n22 Sailor Shift                            Coral Beats         LyricistOf\n23 Sailor Shift                            Coral Beats        PerformerOf\n24 Sailor Shift                        Tides & Ballads         LyricistOf\n25 Sailor Shift                        Tides & Ballads        PerformerOf\n26 Sailor Shift                             Oceanbound         LyricistOf\n27 Sailor Shift                             Oceanbound        PerformerOf\n28 Sailor Shift                     Echoes of the Deep         LyricistOf\n29 Sailor Shift                     Echoes of the Deep        PerformerOf\n30 Sailor Shift                    High Tide Heartbeat        PerformerOf\n31 Sailor Shift                      Electric Eel Love        PerformerOf\n32 Sailor Shift                  Sun-Drenched Daydream        PerformerOf\n33 Sailor Shift                      Chord of the Deep        PerformerOf\n34 Sailor Shift                   Heart of the Habitat        PerformerOf\n35 Sailor Shift                            Reef Rhythm        PerformerOf\n36 Sailor Shift                      Driftwood Lullaby        PerformerOf\n37 Sailor Shift                         Saltwater Hymn        PerformerOf\n38 Sailor Shift                     Moon Over the Tide        PerformerOf\n39 Sailor Shift                       Into the Current        PerformerOf\n40 Sailor Shift                         Barnacle Heart        PerformerOf\n41 Sailor Shift                           Fog & Fiddle        PerformerOf\n42 Sailor Shift                 The Fisherman's Prayer        PerformerOf\n43 Sailor Shift                              Stormsong        PerformerOf\n44 Sailor Shift                       Salt in My Veins        PerformerOf\n45 Sailor Shift                       The Last Mariner        PerformerOf\n46 Sailor Shift                  The Saltwater Weavers          InStyleOf\n47 Sailor Shift                         Drowned Harbor LyricalReferenceTo\n48 Sailor Shift                      Tidesworn Ballads        PerformerOf\n49 Sailor Shift                      Tidesworn Ballads         LyricistOf\n50 Sailor Shift                      Submerged Sonatas        PerformerOf\n51 Sailor Shift                      Submerged Sonatas         LyricistOf\n52 Sailor Shift                      Seashell Serenade        PerformerOf\n      Node Type\n1         Album\n2         Album\n3         Album\n4         Album\n5         Album\n6         Album\n7         Album\n8  MusicalGroup\n9         Album\n10        Album\n11 MusicalGroup\n12 MusicalGroup\n13        Album\n14        Album\n15        Album\n16        Album\n17        Album\n18        Album\n19        Album\n20        Album\n21        Album\n22        Album\n23        Album\n24        Album\n25        Album\n26        Album\n27        Album\n28        Album\n29        Album\n30         Song\n31         Song\n32         Song\n33         Song\n34         Song\n35         Song\n36         Song\n37         Song\n38         Song\n39         Song\n40         Song\n41         Song\n42         Song\n43         Song\n44         Song\n45         Song\n46 MusicalGroup\n47 MusicalGroup\n48        Album\n49        Album\n50        Album\n51        Album\n52         Song\n```\n\n\n:::\n:::\n\n\n\nAll edges starting from Sailor Shift (i.e. first layer edges)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_1st <- edges_all %>% \n  filter(from == \"Sailor Shift\")\n\ncolnames(nodes_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Node Type\"      \"name\"           \"single\"         \"release_date\"  \n [5] \"genre\"          \"notable\"        \"id\"             \"written_date\"  \n [9] \"stage_name\"     \"notoriety_date\"\n```\n\n\n:::\n\n```{.r .cell-code}\nedges_1st_full <- edges_1st %>%\n  left_join(nodes_all, by = c(\"to\" = \"name\")) \n\nedges_1st_full\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           from                                     to          Edge Type\n1  Sailor Shift                         Neon Heartbeat         LyricistOf\n2  Sailor Shift            Ballads for the End of Time         LyricistOf\n3  Sailor Shift                   Melancholy Circuitry         LyricistOf\n4  Sailor Shift Drifting Between the Stars and the Sea         LyricistOf\n5  Sailor Shift                     Artificial Sunsets         LyricistOf\n6  Sailor Shift                       Electric Reverie         LyricistOf\n7  Sailor Shift               Ballads for the Low Tide         LyricistOf\n8  Sailor Shift                 The Fiddle & The Fjord          InStyleOf\n9  Sailor Shift                         Tides of Echos         LyricistOf\n10 Sailor Shift                          Hidden Depths         LyricistOf\n11 Sailor Shift                              Ivy Echos    DirectlySamples\n12 Sailor Shift                              Ivy Echos           MemberOf\n13 Sailor Shift              The Kelp Forest Canticles         LyricistOf\n14 Sailor Shift                      Luminescent Tides         LyricistOf\n15 Sailor Shift                      Shoreline Sonnets         LyricistOf\n16 Sailor Shift                        Tidal Pop Waves         LyricistOf\n17 Sailor Shift                        Tidal Pop Waves        PerformerOf\n18 Sailor Shift                           Salty Dreams         LyricistOf\n19 Sailor Shift                           Salty Dreams        PerformerOf\n20 Sailor Shift                The Current & The Chord         LyricistOf\n21 Sailor Shift                The Current & The Chord        PerformerOf\n22 Sailor Shift                            Coral Beats         LyricistOf\n23 Sailor Shift                            Coral Beats        PerformerOf\n24 Sailor Shift                        Tides & Ballads         LyricistOf\n25 Sailor Shift                        Tides & Ballads        PerformerOf\n26 Sailor Shift                             Oceanbound         LyricistOf\n27 Sailor Shift                             Oceanbound        PerformerOf\n28 Sailor Shift                     Echoes of the Deep         LyricistOf\n29 Sailor Shift                     Echoes of the Deep        PerformerOf\n30 Sailor Shift                    High Tide Heartbeat        PerformerOf\n31 Sailor Shift                      Electric Eel Love        PerformerOf\n32 Sailor Shift                  Sun-Drenched Daydream        PerformerOf\n33 Sailor Shift                      Chord of the Deep        PerformerOf\n34 Sailor Shift                   Heart of the Habitat        PerformerOf\n35 Sailor Shift                            Reef Rhythm        PerformerOf\n36 Sailor Shift                      Driftwood Lullaby        PerformerOf\n37 Sailor Shift                         Saltwater Hymn        PerformerOf\n38 Sailor Shift                     Moon Over the Tide        PerformerOf\n39 Sailor Shift                       Into the Current        PerformerOf\n40 Sailor Shift                         Barnacle Heart        PerformerOf\n41 Sailor Shift                           Fog & Fiddle        PerformerOf\n42 Sailor Shift                 The Fisherman's Prayer        PerformerOf\n43 Sailor Shift                              Stormsong        PerformerOf\n44 Sailor Shift                       Salt in My Veins        PerformerOf\n45 Sailor Shift                       The Last Mariner        PerformerOf\n46 Sailor Shift                  The Saltwater Weavers          InStyleOf\n47 Sailor Shift                         Drowned Harbor LyricalReferenceTo\n48 Sailor Shift                      Tidesworn Ballads        PerformerOf\n49 Sailor Shift                      Tidesworn Ballads         LyricistOf\n50 Sailor Shift                      Submerged Sonatas        PerformerOf\n51 Sailor Shift                      Submerged Sonatas         LyricistOf\n52 Sailor Shift                      Seashell Serenade        PerformerOf\n   source target key    Node Type single release_date        genre notable\n1   17255  16961   0        Album     NA         2031    Synthwave   FALSE\n2   17255  16989   0        Album     NA         2033 Oceanus Folk    TRUE\n3   17255  16999   0        Album     NA         2033    Americana    TRUE\n4   17255  17047   0        Album     NA         2034 Oceanus Folk    TRUE\n5   17255  17048   0        Album     NA         2035 Oceanus Folk    TRUE\n6   17255  17049   0        Album     NA         2038 Oceanus Folk    TRUE\n7   17255  17121   0        Album     NA         2037 Oceanus Folk    TRUE\n8   17255  17192   0 MusicalGroup     NA         <NA>         <NA>      NA\n9   17255  17231   0        Album     NA         2029 Oceanus Folk    TRUE\n10  17255  17252   0        Album     NA         2031 Oceanus Folk    TRUE\n11  17255  17260   1 MusicalGroup     NA         <NA>         <NA>      NA\n12  17255  17260   0 MusicalGroup     NA         <NA>         <NA>      NA\n13  17255  17261   0        Album     NA         2024 Oceanus Folk    TRUE\n14  17255  17262   0        Album     NA         2025 Oceanus Folk    TRUE\n15  17255  17263   0        Album     NA         2026 Oceanus Folk    TRUE\n16  17255  17272   1        Album     NA         2028 Oceanus Folk    TRUE\n17  17255  17272   0        Album     NA         2028 Oceanus Folk    TRUE\n18  17255  17273   1        Album     NA         2030 Oceanus Folk    TRUE\n19  17255  17273   0        Album     NA         2030 Oceanus Folk    TRUE\n20  17255  17274   1        Album     NA         2032 Oceanus Folk    TRUE\n21  17255  17274   0        Album     NA         2032 Oceanus Folk    TRUE\n22  17255  17275   1        Album     NA         2034 Oceanus Folk    TRUE\n23  17255  17275   0        Album     NA         2034 Oceanus Folk    TRUE\n24  17255  17276   1        Album     NA         2036 Oceanus Folk    TRUE\n25  17255  17276   0        Album     NA         2036 Oceanus Folk    TRUE\n26  17255  17277   1        Album     NA         2038 Oceanus Folk    TRUE\n27  17255  17277   0        Album     NA         2038 Oceanus Folk    TRUE\n28  17255  17278   1        Album     NA         2040 Oceanus Folk    TRUE\n29  17255  17278   0        Album     NA         2040 Oceanus Folk    TRUE\n30  17255  17279   0         Song   TRUE         2028 Oceanus Folk   FALSE\n31  17255  17280   0         Song  FALSE         2028 Oceanus Folk    TRUE\n32  17255  17281   0         Song  FALSE         2028 Oceanus Folk   FALSE\n33  17255  17282   0         Song  FALSE         2028 Oceanus Folk   FALSE\n34  17255  17283   0         Song   TRUE         2030 Oceanus Folk   FALSE\n35  17255  17284   0         Song  FALSE         2030 Oceanus Folk   FALSE\n36  17255  17285   0         Song  FALSE         2030 Oceanus Folk   FALSE\n37  17255  17286   0         Song  FALSE         2032 Oceanus Folk   FALSE\n38  17255  17287   0         Song  FALSE         2034 Oceanus Folk    TRUE\n39  17255  17288   0         Song   TRUE         2034 Oceanus Folk   FALSE\n40  17255  17289   0         Song  FALSE         2034 Oceanus Folk   FALSE\n41  17255  17290   0         Song  FALSE         2036 Oceanus Folk    TRUE\n42  17255  17291   0         Song   TRUE         2036 Oceanus Folk   FALSE\n43  17255  17292   0         Song   TRUE         2038 Oceanus Folk    TRUE\n44  17255  17293   0         Song  FALSE         2040 Oceanus Folk   FALSE\n45  17255  17294   0         Song  FALSE         2040 Oceanus Folk   FALSE\n46  17255  17299   0 MusicalGroup     NA         <NA>         <NA>      NA\n47  17255  17327   0 MusicalGroup     NA         <NA>         <NA>      NA\n48  17255  17350   1        Album     NA         2031 Oceanus Folk    TRUE\n49  17255  17350   0        Album     NA         2031 Oceanus Folk    TRUE\n50  17255  17356   1        Album     NA         2031 Oceanus Folk    TRUE\n51  17255  17356   0        Album     NA         2031 Oceanus Folk    TRUE\n52  17255  17410   0         Song   TRUE         2030 Oceanus Folk    TRUE\n      id written_date stage_name notoriety_date\n1  16961         2030       <NA>           <NA>\n2  16989         2032       <NA>           <NA>\n3  16999         2032       <NA>           <NA>\n4  17047         2033       <NA>           <NA>\n5  17048         2034       <NA>           <NA>\n6  17049         2037       <NA>           <NA>\n7  17121         2036       <NA>           <NA>\n8  17192         <NA>       <NA>           <NA>\n9  17231         2028       <NA>           <NA>\n10 17252         2030       <NA>           <NA>\n11 17260         <NA>       <NA>           <NA>\n12 17260         <NA>       <NA>           <NA>\n13 17261         2023       <NA>           <NA>\n14 17262         2024       <NA>           <NA>\n15 17263         2025       <NA>           <NA>\n16 17272         2027       <NA>           <NA>\n17 17272         2027       <NA>           <NA>\n18 17273         2029       <NA>           <NA>\n19 17273         2029       <NA>           <NA>\n20 17274         2031       <NA>           <NA>\n21 17274         2031       <NA>           <NA>\n22 17275         2033       <NA>           <NA>\n23 17275         2033       <NA>           <NA>\n24 17276         2035       <NA>           <NA>\n25 17276         2035       <NA>           <NA>\n26 17277         2037       <NA>           <NA>\n27 17277         2037       <NA>           <NA>\n28 17278         2039       <NA>           <NA>\n29 17278         2039       <NA>           <NA>\n30 17279         <NA>       <NA>           <NA>\n31 17280         <NA>       <NA>           <NA>\n32 17281         <NA>       <NA>           <NA>\n33 17282         <NA>       <NA>           <NA>\n34 17283         <NA>       <NA>           <NA>\n35 17284         <NA>       <NA>           <NA>\n36 17285         <NA>       <NA>           <NA>\n37 17286         <NA>       <NA>           <NA>\n38 17287         <NA>       <NA>           <NA>\n39 17288         <NA>       <NA>           <NA>\n40 17289         <NA>       <NA>           <NA>\n41 17290         <NA>       <NA>           <NA>\n42 17291         <NA>       <NA>           <NA>\n43 17292         <NA>       <NA>           <NA>\n44 17293         <NA>       <NA>           <NA>\n45 17294         <NA>       <NA>           <NA>\n46 17299         <NA>       <NA>           <NA>\n47 17327         <NA>       <NA>           <NA>\n48 17350         2030       <NA>           <NA>\n49 17350         2030       <NA>           <NA>\n50 17356         2030       <NA>           <NA>\n51 17356         2030       <NA>           <NA>\n52 17410         <NA>       <NA>           2030\n```\n\n\n:::\n:::\n\n\n\nAdd type information of the from node\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_1st_full_named <- edges_1st %>%\n  left_join(nodes_all %>% select(name, `Node Type`) %>%\n              rename(from = name, `From Type` = `Node Type`), by = \"from\") %>%\n  \n  left_join(nodes_all %>% select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n              rename(to = name, `To Type` = `Node Type`, `To Release` = release_date,\n                     `To Genre` = genre, `To Notable` = notable, `To Notoriety Date` = notoriety_date),\n            by = \"to\") %>%\n  \n  select(from, `From Type`, to, `To Type`, `Edge Type`, `To Release`, `To Genre`, `To Notable`, `To Notoriety Date`)\n\nedges_1st_full_named\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           from From Type                                     to      To Type\n1  Sailor Shift    Person                         Neon Heartbeat        Album\n2  Sailor Shift    Person            Ballads for the End of Time        Album\n3  Sailor Shift    Person                   Melancholy Circuitry        Album\n4  Sailor Shift    Person Drifting Between the Stars and the Sea        Album\n5  Sailor Shift    Person                     Artificial Sunsets        Album\n6  Sailor Shift    Person                       Electric Reverie        Album\n7  Sailor Shift    Person               Ballads for the Low Tide        Album\n8  Sailor Shift    Person                 The Fiddle & The Fjord MusicalGroup\n9  Sailor Shift    Person                         Tides of Echos        Album\n10 Sailor Shift    Person                          Hidden Depths        Album\n11 Sailor Shift    Person                              Ivy Echos MusicalGroup\n12 Sailor Shift    Person                              Ivy Echos MusicalGroup\n13 Sailor Shift    Person              The Kelp Forest Canticles        Album\n14 Sailor Shift    Person                      Luminescent Tides        Album\n15 Sailor Shift    Person                      Shoreline Sonnets        Album\n16 Sailor Shift    Person                        Tidal Pop Waves        Album\n17 Sailor Shift    Person                        Tidal Pop Waves        Album\n18 Sailor Shift    Person                           Salty Dreams        Album\n19 Sailor Shift    Person                           Salty Dreams        Album\n20 Sailor Shift    Person                The Current & The Chord        Album\n21 Sailor Shift    Person                The Current & The Chord        Album\n22 Sailor Shift    Person                            Coral Beats        Album\n23 Sailor Shift    Person                            Coral Beats        Album\n24 Sailor Shift    Person                        Tides & Ballads        Album\n25 Sailor Shift    Person                        Tides & Ballads        Album\n26 Sailor Shift    Person                             Oceanbound        Album\n27 Sailor Shift    Person                             Oceanbound        Album\n28 Sailor Shift    Person                     Echoes of the Deep        Album\n29 Sailor Shift    Person                     Echoes of the Deep        Album\n30 Sailor Shift    Person                    High Tide Heartbeat         Song\n31 Sailor Shift    Person                      Electric Eel Love         Song\n32 Sailor Shift    Person                  Sun-Drenched Daydream         Song\n33 Sailor Shift    Person                      Chord of the Deep         Song\n34 Sailor Shift    Person                   Heart of the Habitat         Song\n35 Sailor Shift    Person                            Reef Rhythm         Song\n36 Sailor Shift    Person                      Driftwood Lullaby         Song\n37 Sailor Shift    Person                         Saltwater Hymn         Song\n38 Sailor Shift    Person                     Moon Over the Tide         Song\n39 Sailor Shift    Person                       Into the Current         Song\n40 Sailor Shift    Person                         Barnacle Heart         Song\n41 Sailor Shift    Person                           Fog & Fiddle         Song\n42 Sailor Shift    Person                 The Fisherman's Prayer         Song\n43 Sailor Shift    Person                              Stormsong         Song\n44 Sailor Shift    Person                       Salt in My Veins         Song\n45 Sailor Shift    Person                       The Last Mariner         Song\n46 Sailor Shift    Person                  The Saltwater Weavers MusicalGroup\n47 Sailor Shift    Person                         Drowned Harbor MusicalGroup\n48 Sailor Shift    Person                      Tidesworn Ballads        Album\n49 Sailor Shift    Person                      Tidesworn Ballads        Album\n50 Sailor Shift    Person                      Submerged Sonatas        Album\n51 Sailor Shift    Person                      Submerged Sonatas        Album\n52 Sailor Shift    Person                      Seashell Serenade         Song\n            Edge Type To Release     To Genre To Notable To Notoriety Date\n1          LyricistOf       2031    Synthwave      FALSE              <NA>\n2          LyricistOf       2033 Oceanus Folk       TRUE              <NA>\n3          LyricistOf       2033    Americana       TRUE              <NA>\n4          LyricistOf       2034 Oceanus Folk       TRUE              <NA>\n5          LyricistOf       2035 Oceanus Folk       TRUE              <NA>\n6          LyricistOf       2038 Oceanus Folk       TRUE              <NA>\n7          LyricistOf       2037 Oceanus Folk       TRUE              <NA>\n8           InStyleOf       <NA>         <NA>         NA              <NA>\n9          LyricistOf       2029 Oceanus Folk       TRUE              <NA>\n10         LyricistOf       2031 Oceanus Folk       TRUE              <NA>\n11    DirectlySamples       <NA>         <NA>         NA              <NA>\n12           MemberOf       <NA>         <NA>         NA              <NA>\n13         LyricistOf       2024 Oceanus Folk       TRUE              <NA>\n14         LyricistOf       2025 Oceanus Folk       TRUE              <NA>\n15         LyricistOf       2026 Oceanus Folk       TRUE              <NA>\n16         LyricistOf       2028 Oceanus Folk       TRUE              <NA>\n17        PerformerOf       2028 Oceanus Folk       TRUE              <NA>\n18         LyricistOf       2030 Oceanus Folk       TRUE              <NA>\n19        PerformerOf       2030 Oceanus Folk       TRUE              <NA>\n20         LyricistOf       2032 Oceanus Folk       TRUE              <NA>\n21        PerformerOf       2032 Oceanus Folk       TRUE              <NA>\n22         LyricistOf       2034 Oceanus Folk       TRUE              <NA>\n23        PerformerOf       2034 Oceanus Folk       TRUE              <NA>\n24         LyricistOf       2036 Oceanus Folk       TRUE              <NA>\n25        PerformerOf       2036 Oceanus Folk       TRUE              <NA>\n26         LyricistOf       2038 Oceanus Folk       TRUE              <NA>\n27        PerformerOf       2038 Oceanus Folk       TRUE              <NA>\n28         LyricistOf       2040 Oceanus Folk       TRUE              <NA>\n29        PerformerOf       2040 Oceanus Folk       TRUE              <NA>\n30        PerformerOf       2028 Oceanus Folk      FALSE              <NA>\n31        PerformerOf       2028 Oceanus Folk       TRUE              <NA>\n32        PerformerOf       2028 Oceanus Folk      FALSE              <NA>\n33        PerformerOf       2028 Oceanus Folk      FALSE              <NA>\n34        PerformerOf       2030 Oceanus Folk      FALSE              <NA>\n35        PerformerOf       2030 Oceanus Folk      FALSE              <NA>\n36        PerformerOf       2030 Oceanus Folk      FALSE              <NA>\n37        PerformerOf       2032 Oceanus Folk      FALSE              <NA>\n38        PerformerOf       2034 Oceanus Folk       TRUE              <NA>\n39        PerformerOf       2034 Oceanus Folk      FALSE              <NA>\n40        PerformerOf       2034 Oceanus Folk      FALSE              <NA>\n41        PerformerOf       2036 Oceanus Folk       TRUE              <NA>\n42        PerformerOf       2036 Oceanus Folk      FALSE              <NA>\n43        PerformerOf       2038 Oceanus Folk       TRUE              <NA>\n44        PerformerOf       2040 Oceanus Folk      FALSE              <NA>\n45        PerformerOf       2040 Oceanus Folk      FALSE              <NA>\n46          InStyleOf       <NA>         <NA>         NA              <NA>\n47 LyricalReferenceTo       <NA>         <NA>         NA              <NA>\n48        PerformerOf       2031 Oceanus Folk       TRUE              <NA>\n49         LyricistOf       2031 Oceanus Folk       TRUE              <NA>\n50        PerformerOf       2031 Oceanus Folk       TRUE              <NA>\n51         LyricistOf       2031 Oceanus Folk       TRUE              <NA>\n52        PerformerOf       2030 Oceanus Folk       TRUE              2030\n```\n\n\n:::\n:::\n\n\n\nBelow is all the information on the second layer, and remove if there is no other layer\n\n::: panel-tabset\n## DirectlySamples \\#\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"DirectlySamples\")\n\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\nedges_selected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          from        to       Edge Type source target key    Node Type single\n1 Sailor Shift Ivy Echos DirectlySamples  17255  17260   1 MusicalGroup     NA\n  release_date genre notable    id written_date stage_name notoriety_date\n1         <NA>  <NA>      NA 17260         <NA>       <NA>           <NA>\n```\n\n\n:::\n:::\n\n\n\n## InStyleOf \\#\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"InStyleOf\")\n\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\nedges_selected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          from                     to Edge Type source target key    Node Type\n1 Sailor Shift The Fiddle & The Fjord InStyleOf  17255  17192   0 MusicalGroup\n2 Sailor Shift  The Saltwater Weavers InStyleOf  17255  17299   0 MusicalGroup\n  single release_date genre notable    id written_date stage_name\n1     NA         <NA>  <NA>      NA 17192         <NA>       <NA>\n2     NA         <NA>  <NA>      NA 17299         <NA>       <NA>\n  notoriety_date\n1           <NA>\n2           <NA>\n```\n\n\n:::\n:::\n\n\n\n## LyricalReferenceTo \\#\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"LyricalReferenceTo\")\n\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\nedges_selected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          from             to          Edge Type source target key    Node Type\n1 Sailor Shift Drowned Harbor LyricalReferenceTo  17255  17327   0 MusicalGroup\n  single release_date genre notable    id written_date stage_name\n1     NA         <NA>  <NA>      NA 17327         <NA>       <NA>\n  notoriety_date\n1           <NA>\n```\n\n\n:::\n:::\n\n\n\n## LyricistOf\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"LyricistOf\")\n\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\nedges_selected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           from                                     to  Edge Type source target\n1  Sailor Shift                         Neon Heartbeat LyricistOf  17255  16961\n2  Sailor Shift            Ballads for the End of Time LyricistOf  17255  16989\n3  Sailor Shift                   Melancholy Circuitry LyricistOf  17255  16999\n4  Sailor Shift Drifting Between the Stars and the Sea LyricistOf  17255  17047\n5  Sailor Shift                     Artificial Sunsets LyricistOf  17255  17048\n6  Sailor Shift                       Electric Reverie LyricistOf  17255  17049\n7  Sailor Shift               Ballads for the Low Tide LyricistOf  17255  17121\n8  Sailor Shift                         Tides of Echos LyricistOf  17255  17231\n9  Sailor Shift                          Hidden Depths LyricistOf  17255  17252\n10 Sailor Shift              The Kelp Forest Canticles LyricistOf  17255  17261\n11 Sailor Shift                      Luminescent Tides LyricistOf  17255  17262\n12 Sailor Shift                      Shoreline Sonnets LyricistOf  17255  17263\n13 Sailor Shift                        Tidal Pop Waves LyricistOf  17255  17272\n14 Sailor Shift                           Salty Dreams LyricistOf  17255  17273\n15 Sailor Shift                The Current & The Chord LyricistOf  17255  17274\n16 Sailor Shift                            Coral Beats LyricistOf  17255  17275\n17 Sailor Shift                        Tides & Ballads LyricistOf  17255  17276\n18 Sailor Shift                             Oceanbound LyricistOf  17255  17277\n19 Sailor Shift                     Echoes of the Deep LyricistOf  17255  17278\n20 Sailor Shift                      Tidesworn Ballads LyricistOf  17255  17350\n21 Sailor Shift                      Submerged Sonatas LyricistOf  17255  17356\n   key Node Type single release_date        genre notable    id written_date\n1    0     Album     NA         2031    Synthwave   FALSE 16961         2030\n2    0     Album     NA         2033 Oceanus Folk    TRUE 16989         2032\n3    0     Album     NA         2033    Americana    TRUE 16999         2032\n4    0     Album     NA         2034 Oceanus Folk    TRUE 17047         2033\n5    0     Album     NA         2035 Oceanus Folk    TRUE 17048         2034\n6    0     Album     NA         2038 Oceanus Folk    TRUE 17049         2037\n7    0     Album     NA         2037 Oceanus Folk    TRUE 17121         2036\n8    0     Album     NA         2029 Oceanus Folk    TRUE 17231         2028\n9    0     Album     NA         2031 Oceanus Folk    TRUE 17252         2030\n10   0     Album     NA         2024 Oceanus Folk    TRUE 17261         2023\n11   0     Album     NA         2025 Oceanus Folk    TRUE 17262         2024\n12   0     Album     NA         2026 Oceanus Folk    TRUE 17263         2025\n13   1     Album     NA         2028 Oceanus Folk    TRUE 17272         2027\n14   1     Album     NA         2030 Oceanus Folk    TRUE 17273         2029\n15   1     Album     NA         2032 Oceanus Folk    TRUE 17274         2031\n16   1     Album     NA         2034 Oceanus Folk    TRUE 17275         2033\n17   1     Album     NA         2036 Oceanus Folk    TRUE 17276         2035\n18   1     Album     NA         2038 Oceanus Folk    TRUE 17277         2037\n19   1     Album     NA         2040 Oceanus Folk    TRUE 17278         2039\n20   0     Album     NA         2031 Oceanus Folk    TRUE 17350         2030\n21   0     Album     NA         2031 Oceanus Folk    TRUE 17356         2030\n   stage_name notoriety_date\n1        <NA>           <NA>\n2        <NA>           <NA>\n3        <NA>           <NA>\n4        <NA>           <NA>\n5        <NA>           <NA>\n6        <NA>           <NA>\n7        <NA>           <NA>\n8        <NA>           <NA>\n9        <NA>           <NA>\n10       <NA>           <NA>\n11       <NA>           <NA>\n12       <NA>           <NA>\n13       <NA>           <NA>\n14       <NA>           <NA>\n15       <NA>           <NA>\n16       <NA>           <NA>\n17       <NA>           <NA>\n18       <NA>           <NA>\n19       <NA>           <NA>\n20       <NA>           <NA>\n21       <NA>           <NA>\n```\n\n\n:::\n:::\n\n\n\n## MemberOf \\#\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"MemberOf\")\n\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\nedges_selected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          from        to Edge Type source target key    Node Type single\n1 Sailor Shift Ivy Echos  MemberOf  17255  17260   0 MusicalGroup     NA\n  release_date genre notable    id written_date stage_name notoriety_date\n1         <NA>  <NA>      NA 17260         <NA>       <NA>           <NA>\n```\n\n\n:::\n:::\n\n\n\n## PerformerOf\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_types <- c(\"PerformerOf\")\n\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\nedges_selected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           from                      to   Edge Type source target key Node Type\n1  Sailor Shift         Tidal Pop Waves PerformerOf  17255  17272   0     Album\n2  Sailor Shift            Salty Dreams PerformerOf  17255  17273   0     Album\n3  Sailor Shift The Current & The Chord PerformerOf  17255  17274   0     Album\n4  Sailor Shift             Coral Beats PerformerOf  17255  17275   0     Album\n5  Sailor Shift         Tides & Ballads PerformerOf  17255  17276   0     Album\n6  Sailor Shift              Oceanbound PerformerOf  17255  17277   0     Album\n7  Sailor Shift      Echoes of the Deep PerformerOf  17255  17278   0     Album\n8  Sailor Shift     High Tide Heartbeat PerformerOf  17255  17279   0      Song\n9  Sailor Shift       Electric Eel Love PerformerOf  17255  17280   0      Song\n10 Sailor Shift   Sun-Drenched Daydream PerformerOf  17255  17281   0      Song\n11 Sailor Shift       Chord of the Deep PerformerOf  17255  17282   0      Song\n12 Sailor Shift    Heart of the Habitat PerformerOf  17255  17283   0      Song\n13 Sailor Shift             Reef Rhythm PerformerOf  17255  17284   0      Song\n14 Sailor Shift       Driftwood Lullaby PerformerOf  17255  17285   0      Song\n15 Sailor Shift          Saltwater Hymn PerformerOf  17255  17286   0      Song\n16 Sailor Shift      Moon Over the Tide PerformerOf  17255  17287   0      Song\n17 Sailor Shift        Into the Current PerformerOf  17255  17288   0      Song\n18 Sailor Shift          Barnacle Heart PerformerOf  17255  17289   0      Song\n19 Sailor Shift            Fog & Fiddle PerformerOf  17255  17290   0      Song\n20 Sailor Shift  The Fisherman's Prayer PerformerOf  17255  17291   0      Song\n21 Sailor Shift               Stormsong PerformerOf  17255  17292   0      Song\n22 Sailor Shift        Salt in My Veins PerformerOf  17255  17293   0      Song\n23 Sailor Shift        The Last Mariner PerformerOf  17255  17294   0      Song\n24 Sailor Shift       Tidesworn Ballads PerformerOf  17255  17350   1     Album\n25 Sailor Shift       Submerged Sonatas PerformerOf  17255  17356   1     Album\n26 Sailor Shift       Seashell Serenade PerformerOf  17255  17410   0      Song\n   single release_date        genre notable    id written_date stage_name\n1      NA         2028 Oceanus Folk    TRUE 17272         2027       <NA>\n2      NA         2030 Oceanus Folk    TRUE 17273         2029       <NA>\n3      NA         2032 Oceanus Folk    TRUE 17274         2031       <NA>\n4      NA         2034 Oceanus Folk    TRUE 17275         2033       <NA>\n5      NA         2036 Oceanus Folk    TRUE 17276         2035       <NA>\n6      NA         2038 Oceanus Folk    TRUE 17277         2037       <NA>\n7      NA         2040 Oceanus Folk    TRUE 17278         2039       <NA>\n8    TRUE         2028 Oceanus Folk   FALSE 17279         <NA>       <NA>\n9   FALSE         2028 Oceanus Folk    TRUE 17280         <NA>       <NA>\n10  FALSE         2028 Oceanus Folk   FALSE 17281         <NA>       <NA>\n11  FALSE         2028 Oceanus Folk   FALSE 17282         <NA>       <NA>\n12   TRUE         2030 Oceanus Folk   FALSE 17283         <NA>       <NA>\n13  FALSE         2030 Oceanus Folk   FALSE 17284         <NA>       <NA>\n14  FALSE         2030 Oceanus Folk   FALSE 17285         <NA>       <NA>\n15  FALSE         2032 Oceanus Folk   FALSE 17286         <NA>       <NA>\n16  FALSE         2034 Oceanus Folk    TRUE 17287         <NA>       <NA>\n17   TRUE         2034 Oceanus Folk   FALSE 17288         <NA>       <NA>\n18  FALSE         2034 Oceanus Folk   FALSE 17289         <NA>       <NA>\n19  FALSE         2036 Oceanus Folk    TRUE 17290         <NA>       <NA>\n20   TRUE         2036 Oceanus Folk   FALSE 17291         <NA>       <NA>\n21   TRUE         2038 Oceanus Folk    TRUE 17292         <NA>       <NA>\n22  FALSE         2040 Oceanus Folk   FALSE 17293         <NA>       <NA>\n23  FALSE         2040 Oceanus Folk   FALSE 17294         <NA>       <NA>\n24     NA         2031 Oceanus Folk    TRUE 17350         2030       <NA>\n25     NA         2031 Oceanus Folk    TRUE 17356         2030       <NA>\n26   TRUE         2030 Oceanus Folk    TRUE 17410         <NA>       <NA>\n   notoriety_date\n1            <NA>\n2            <NA>\n3            <NA>\n4            <NA>\n5            <NA>\n6            <NA>\n7            <NA>\n8            <NA>\n9            <NA>\n10           <NA>\n11           <NA>\n12           <NA>\n13           <NA>\n14           <NA>\n15           <NA>\n16           <NA>\n17           <NA>\n18           <NA>\n19           <NA>\n20           <NA>\n21           <NA>\n22           <NA>\n23           <NA>\n24           <NA>\n25           <NA>\n26           2030\n```\n\n\n:::\n:::\n\n\n:::\n\nThen we can visual all the connect from Sailor:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_1st_filtered <- edges_1st_full %>%\n  filter(`Edge Type` %in% c(\"LyricistOf\", \"PerformerOf\", \"MemberOf\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_subgraph <- nodes_all %>%\n  filter(name %in% c(\"Sailor Shift\", edges_1st_filtered$to)) %>%\n  transmute(id = name, label = name, group = `Node Type`)\n\nedges_subgraph <- edges_1st_filtered %>%\n  transmute(\n    from = from,\n    to = to,\n    label = `Edge Type`,\n    title = paste0(\"Edge Type: \", `Edge Type`, \"<br>To Type: \", `Node Type`, \"<br>Year: \", release_date)\n  )\n\nvisNetwork(nodes_subgraph, edges_subgraph, width = \"100%\", height = \"700px\") %>%\n  visEdges(arrows = \"to\") %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%\n  visLegend(useGroups = TRUE, position = \"right\") %>%\n  visPhysics(\n    solver = \"forceAtlas2Based\",\n    forceAtlas2Based = list(gravitationalConstant = -80),\n    stabilization = list(enabled = TRUE, iterations = 100)\n  ) %>%\n  visLayout(randomSeed = 123)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-d885da379289af7a2723\" style=\"width:100%;height:700px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d885da379289af7a2723\">{\"x\":{\"nodes\":{\"id\":[\"Neon Heartbeat\",\"Ballads for the End of Time\",\"Melancholy Circuitry\",\"Drifting Between the Stars and the Sea\",\"Artificial Sunsets\",\"Electric Reverie\",\"Ballads for the Low Tide\",\"Tides of Echos\",\"Hidden Depths\",\"Sailor Shift\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Tidal Pop Waves\",\"Salty Dreams\",\"The Current & The Chord\",\"Coral Beats\",\"Tides & Ballads\",\"Oceanbound\",\"Echoes of the Deep\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Sun-Drenched Daydream\",\"Chord of the Deep\",\"Heart of the Habitat\",\"Reef Rhythm\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Into the Current\",\"Barnacle Heart\",\"Fog & Fiddle\",\"The Fisherman's Prayer\",\"Stormsong\",\"Salt in My Veins\",\"The Last Mariner\",\"Tidesworn Ballads\",\"Submerged Sonatas\",\"Seashell Serenade\"],\"label\":[\"Neon Heartbeat\",\"Ballads for the End of Time\",\"Melancholy Circuitry\",\"Drifting Between the Stars and the Sea\",\"Artificial Sunsets\",\"Electric Reverie\",\"Ballads for the Low Tide\",\"Tides of Echos\",\"Hidden Depths\",\"Sailor Shift\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Tidal Pop Waves\",\"Salty Dreams\",\"The Current & The Chord\",\"Coral Beats\",\"Tides & Ballads\",\"Oceanbound\",\"Echoes of the Deep\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Sun-Drenched Daydream\",\"Chord of the Deep\",\"Heart of the Habitat\",\"Reef Rhythm\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Into the Current\",\"Barnacle Heart\",\"Fog & Fiddle\",\"The Fisherman's Prayer\",\"Stormsong\",\"Salt in My Veins\",\"The Last Mariner\",\"Tidesworn Ballads\",\"Submerged Sonatas\",\"Seashell Serenade\"],\"group\":[\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Person\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Album\",\"Album\",\"Song\"]},\"edges\":{\"from\":[\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\",\"Sailor Shift\"],\"to\":[\"Neon Heartbeat\",\"Ballads for the End of Time\",\"Melancholy Circuitry\",\"Drifting Between the Stars and the Sea\",\"Artificial Sunsets\",\"Electric Reverie\",\"Ballads for the Low Tide\",\"Tides of Echos\",\"Hidden Depths\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Luminescent Tides\",\"Shoreline Sonnets\",\"Tidal Pop Waves\",\"Tidal Pop Waves\",\"Salty Dreams\",\"Salty Dreams\",\"The Current & The Chord\",\"The Current & The Chord\",\"Coral Beats\",\"Coral Beats\",\"Tides & Ballads\",\"Tides & Ballads\",\"Oceanbound\",\"Oceanbound\",\"Echoes of the Deep\",\"Echoes of the Deep\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Sun-Drenched Daydream\",\"Chord of the Deep\",\"Heart of the Habitat\",\"Reef Rhythm\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Into the Current\",\"Barnacle Heart\",\"Fog & Fiddle\",\"The Fisherman's Prayer\",\"Stormsong\",\"Salt in My Veins\",\"The Last Mariner\",\"Tidesworn Ballads\",\"Tidesworn Ballads\",\"Submerged Sonatas\",\"Submerged Sonatas\",\"Seashell Serenade\"],\"label\":[\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"MemberOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\"],\"title\":[\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2031\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2033\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2033\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2034\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2035\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2038\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2037\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2029\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2031\",\"Edge Type: MemberOf<br>To Type: MusicalGroup<br>Year: NA\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2024\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2025\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2026\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2028\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2028\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2030\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2030\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2032\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2032\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2034\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2034\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2036\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2036\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2038\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2038\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2040\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2040\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2028\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2028\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2028\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2028\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2030\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2030\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2030\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2032\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2034\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2034\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2034\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2036\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2036\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2038\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2040\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2040\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2031\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2031\",\"Edge Type: PerformerOf<br>To Type: Album<br>Year: 2031\",\"Edge Type: LyricistOf<br>To Type: Album<br>Year: 2031\",\"Edge Type: PerformerOf<br>To Type: Song<br>Year: 2030\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":\"to\"},\"physics\":{\"solver\":\"forceAtlas2Based\",\"stabilization\":{\"enabled\":true,\"iterations\":100},\"forceAtlas2Based\":{\"gravitationalConstant\":-80}},\"layout\":{\"randomSeed\":123}},\"groups\":[\"Album\",\"Person\",\"MusicalGroup\",\"Song\"],\"width\":\"100%\",\"height\":\"700px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"right\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nivy_groups <- edges_all %>%\n  filter(to == \"Ivy Echos\", `Edge Type` == \"MemberOf\") %>%\n  pull(from)\nivy_groups\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Sailor Shift\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_members <- edges_all %>%\n  filter(`Edge Type` == \"MemberOf\", to %in% ivy_groups) %>%\n  select(from, to) %>%\n  rename(Member = from, Group = to)\ngroup_members\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Member Group \n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsailor_works <- edges_1st_full %>%\n  filter(`Edge Type` %in% c(\"ComposerOf\", \"PerformerOf\", \"LyricistOf\", \"ProducerOf\",\"MemberOf\"),\n         `Node Type` %in% c(\"Song\", \"Album\",\"MusicalGroup\",\"Person\",\"RecordLabel\")) %>%\n  pull(to) %>%\n  unique()\n\nedges_others <- edges_all %>%\n  filter(\n    to %in% sailor_works,\n    `Edge Type` %in% c(\"ComposerOf\", \"PerformerOf\", \"LyricistOf\", \"ProducerOf\"),\n    from != \"Sailor Shift\"  \n  )\n\nedges_others_full <- edges_others %>%\n  left_join(nodes_all, by = c(\"from\" = \"name\")) %>%\n  rename(Participant = from, ParticipantType = `Node Type`) %>%\n  select(Participant, ParticipantType, to, `Edge Type`)\n\nedges_others_full\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Participant ParticipantType                        to   Edge Type\n1   Ivy Echos    MusicalGroup The Kelp Forest Canticles PerformerOf\n2   Ivy Echos    MusicalGroup         Luminescent Tides PerformerOf\n3   Ivy Echos    MusicalGroup         Shoreline Sonnets PerformerOf\n```\n\n\n:::\n:::\n\n\n\nAnd we have select the node that have connect the the third layer and to see the indirectly being influenced.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\nedges_1st <- edges_all %>%\n  filter(from == \"Sailor Shift\")\n\nedges_1st_full <- edges_1st %>%\n  left_join(nodes_all, by = c(\"to\" = \"name\")) %>%\n  select(from, to, `Edge Type`, `Node Type`, release_date,genre,notable,notoriety_date)\n\nselected_types <- c(\"LyricistOf\", \"PerformerOf\")\nedges_selected <- edges_1st_full %>%\n  filter(`Edge Type` %in% selected_types)\n\ntarget_nodes <- unique(edges_selected$to)\n\nedges_2nd <- edges_all %>%\n  filter(from %in% target_nodes)\n\nfrom_info <- nodes_all %>%\n  select(name, `Node Type`) %>%\n  rename(from = name, `From Node Type` = `Node Type`)\n\nto_info <- nodes_all %>%\n  select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n  rename(\n    to = name,\n    `To Node Type` = `Node Type`,\n    to_release_date = release_date,\n    to_genre = genre,\n    to_notable = notable,\n    to_notoriety_date = notoriety_date\n  )\n\nedges_2nd_full <- edges_2nd %>%\n  left_join(from_info, by = \"from\") %>%\n  left_join(to_info, by = \"to\") %>%\n  select(\n    from, `From Node Type`, to, `To Node Type`, `Edge Type`,\n    to_release_date, to_genre, to_notable, to_notoriety_date\n  )\n\nedges_2nd_full\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        from From Node Type\n1       Melancholy Circuitry          Album\n2           Electric Reverie          Album\n3           Electric Reverie          Album\n4             Tides of Echos          Album\n5             Tides of Echos          Album\n6  The Kelp Forest Canticles          Album\n7  The Kelp Forest Canticles          Album\n8               Salty Dreams          Album\n9               Salty Dreams          Album\n10               Coral Beats          Album\n11               Coral Beats          Album\n12                Oceanbound          Album\n13                Oceanbound          Album\n14       High Tide Heartbeat           Song\n15         Electric Eel Love           Song\n16         Electric Eel Love           Song\n17         Driftwood Lullaby           Song\n18            Saltwater Hymn           Song\n19        Moon Over the Tide           Song\n20        Moon Over the Tide           Song\n21            Barnacle Heart           Song\n22              Fog & Fiddle           Song\n23              Fog & Fiddle           Song\n24                 Stormsong           Song\n25                 Stormsong           Song\n26         Tidesworn Ballads          Album\n                                     to To Node Type          Edge Type\n1                  Twilight's Threshold         Song            CoverOf\n2                      Reflejo Interior         Song   InterpolatesFrom\n3                  Folklore's Heartbeat         Song          InStyleOf\n4                     The Long Way Home        Album          InStyleOf\n5                       Weathered Miles         Song   InterpolatesFrom\n6                  Hallowed Transaction        Album    DirectlySamples\n7                 Für uns alle zusammen         Song            CoverOf\n8                    Susurros de Pasión         Song          InStyleOf\n9                     Partisan's Lament         Song            CoverOf\n10                     Sacred Fragments         Song          InStyleOf\n11          Harvest Dance at Ler Valley         Song            CoverOf\n12                 Bold Without Apology         Song LyricalReferenceTo\n13                 Altitude of Mistakes         Song LyricalReferenceTo\n14           Addicted to Your Heartache        Album   InterpolatesFrom\n15             Twelve Bells of Augsburg         Song          InStyleOf\n16                    The Crown We Wear         Song            CoverOf\n17            Echoes of Forgotten Light         Song          InStyleOf\n18                    Parallel Memories         Song          InStyleOf\n19                   Divergent Memories         Song   InterpolatesFrom\n20 Silent Steps in the Forest's Embrace         Song LyricalReferenceTo\n21                  Our Inevitable Path         Song          InStyleOf\n22                        Provence Aria         Song          InStyleOf\n23           Coastal Whispers of Biscay         Song   InterpolatesFrom\n24            When the Bar Lights Go Up         Song          InStyleOf\n25                 Exoskeleton Dissolve         Song    DirectlySamples\n26               Dreamscape of Judgment         Song            CoverOf\n   to_release_date             to_genre to_notable to_notoriety_date\n1             2007            Synthwave       TRUE              2007\n2             1983            Americana       TRUE              <NA>\n3             2020           Blues Rock       TRUE              2033\n4             2023            Dream Pop       TRUE              <NA>\n5             2023           Doom Metal       TRUE              <NA>\n6             2017           Doom Metal       TRUE              <NA>\n7             2017     Alternative Rock       TRUE              <NA>\n8             2004            Synthwave       TRUE              2004\n9             2030            Indie Pop       TRUE              <NA>\n10            2003            Synthwave       TRUE              2003\n11            2010     Psychedelic Rock       TRUE              <NA>\n12            2010           Indie Rock       TRUE              <NA>\n13            2015            Americana       TRUE              2015\n14            2004 Southern Gothic Rock       TRUE              <NA>\n15            2026     Psychedelic Rock       TRUE              <NA>\n16            2022           Indie Rock       TRUE              <NA>\n17            2004     Alternative Rock       TRUE              <NA>\n18            2028            Dream Pop       TRUE              <NA>\n19            2017           Indie Folk       TRUE              2017\n20            2023     Avant-Garde Folk       TRUE              2023\n21            2017           Indie Folk       TRUE              <NA>\n22            2023           Indie Rock       TRUE              <NA>\n23            2031     Alternative Rock       TRUE              <NA>\n24            2000         Emo/Pop Punk       TRUE              <NA>\n25            2020           Indie Rock       TRUE              2020\n26            2023      Symphonic Metal       TRUE              <NA>\n```\n\n\n:::\n:::\n\n\n\nGet the complete information of the from node\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrom_info <- nodes_all %>%\n  select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n  rename(\n    from = name,\n    `From Node Type` = `Node Type`,\n    from_release_date = release_date,\n    from_genre = genre,\n    from_notable = notable,\n    from_notoriety_date = notoriety_date\n  )\n\nto_info <- nodes_all %>%\n  select(name, `Node Type`, release_date, genre, notable, notoriety_date) %>%\n  rename(\n    to = name,\n    `To Node Type` = `Node Type`,\n    to_release_date = release_date,\n    to_genre = genre,\n    to_notable = notable,\n    to_notoriety_date = notoriety_date\n  )\n\nedges_2nd_full <- edges_2nd %>%\n  left_join(from_info, by = \"from\") %>%\n  left_join(to_info, by = \"to\") %>%\n  select(\n    from, `From Node Type`, from_release_date, from_genre, from_notable, from_notoriety_date,\n    to, `To Node Type`, to_release_date, to_genre, to_notable, to_notoriety_date,\n    `Edge Type`\n  )\n\nedges_2nd_full\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        from From Node Type from_release_date   from_genre\n1       Melancholy Circuitry          Album              2033    Americana\n2           Electric Reverie          Album              2038 Oceanus Folk\n3           Electric Reverie          Album              2038 Oceanus Folk\n4             Tides of Echos          Album              2029 Oceanus Folk\n5             Tides of Echos          Album              2029 Oceanus Folk\n6  The Kelp Forest Canticles          Album              2024 Oceanus Folk\n7  The Kelp Forest Canticles          Album              2024 Oceanus Folk\n8               Salty Dreams          Album              2030 Oceanus Folk\n9               Salty Dreams          Album              2030 Oceanus Folk\n10               Coral Beats          Album              2034 Oceanus Folk\n11               Coral Beats          Album              2034 Oceanus Folk\n12                Oceanbound          Album              2038 Oceanus Folk\n13                Oceanbound          Album              2038 Oceanus Folk\n14       High Tide Heartbeat           Song              2028 Oceanus Folk\n15         Electric Eel Love           Song              2028 Oceanus Folk\n16         Electric Eel Love           Song              2028 Oceanus Folk\n17         Driftwood Lullaby           Song              2030 Oceanus Folk\n18            Saltwater Hymn           Song              2032 Oceanus Folk\n19        Moon Over the Tide           Song              2034 Oceanus Folk\n20        Moon Over the Tide           Song              2034 Oceanus Folk\n21            Barnacle Heart           Song              2034 Oceanus Folk\n22              Fog & Fiddle           Song              2036 Oceanus Folk\n23              Fog & Fiddle           Song              2036 Oceanus Folk\n24                 Stormsong           Song              2038 Oceanus Folk\n25                 Stormsong           Song              2038 Oceanus Folk\n26         Tidesworn Ballads          Album              2031 Oceanus Folk\n   from_notable from_notoriety_date                                   to\n1          TRUE                <NA>                 Twilight's Threshold\n2          TRUE                <NA>                     Reflejo Interior\n3          TRUE                <NA>                 Folklore's Heartbeat\n4          TRUE                <NA>                    The Long Way Home\n5          TRUE                <NA>                      Weathered Miles\n6          TRUE                <NA>                 Hallowed Transaction\n7          TRUE                <NA>                Für uns alle zusammen\n8          TRUE                <NA>                   Susurros de Pasión\n9          TRUE                <NA>                    Partisan's Lament\n10         TRUE                <NA>                     Sacred Fragments\n11         TRUE                <NA>          Harvest Dance at Ler Valley\n12         TRUE                <NA>                 Bold Without Apology\n13         TRUE                <NA>                 Altitude of Mistakes\n14        FALSE                <NA>           Addicted to Your Heartache\n15         TRUE                <NA>             Twelve Bells of Augsburg\n16         TRUE                <NA>                    The Crown We Wear\n17        FALSE                <NA>            Echoes of Forgotten Light\n18        FALSE                <NA>                    Parallel Memories\n19         TRUE                <NA>                   Divergent Memories\n20         TRUE                <NA> Silent Steps in the Forest's Embrace\n21        FALSE                <NA>                  Our Inevitable Path\n22         TRUE                <NA>                        Provence Aria\n23         TRUE                <NA>           Coastal Whispers of Biscay\n24         TRUE                <NA>            When the Bar Lights Go Up\n25         TRUE                <NA>                 Exoskeleton Dissolve\n26         TRUE                <NA>               Dreamscape of Judgment\n   To Node Type to_release_date             to_genre to_notable\n1          Song            2007            Synthwave       TRUE\n2          Song            1983            Americana       TRUE\n3          Song            2020           Blues Rock       TRUE\n4         Album            2023            Dream Pop       TRUE\n5          Song            2023           Doom Metal       TRUE\n6         Album            2017           Doom Metal       TRUE\n7          Song            2017     Alternative Rock       TRUE\n8          Song            2004            Synthwave       TRUE\n9          Song            2030            Indie Pop       TRUE\n10         Song            2003            Synthwave       TRUE\n11         Song            2010     Psychedelic Rock       TRUE\n12         Song            2010           Indie Rock       TRUE\n13         Song            2015            Americana       TRUE\n14        Album            2004 Southern Gothic Rock       TRUE\n15         Song            2026     Psychedelic Rock       TRUE\n16         Song            2022           Indie Rock       TRUE\n17         Song            2004     Alternative Rock       TRUE\n18         Song            2028            Dream Pop       TRUE\n19         Song            2017           Indie Folk       TRUE\n20         Song            2023     Avant-Garde Folk       TRUE\n21         Song            2017           Indie Folk       TRUE\n22         Song            2023           Indie Rock       TRUE\n23         Song            2031     Alternative Rock       TRUE\n24         Song            2000         Emo/Pop Punk       TRUE\n25         Song            2020           Indie Rock       TRUE\n26         Song            2023      Symphonic Metal       TRUE\n   to_notoriety_date          Edge Type\n1               2007            CoverOf\n2               <NA>   InterpolatesFrom\n3               2033          InStyleOf\n4               <NA>          InStyleOf\n5               <NA>   InterpolatesFrom\n6               <NA>    DirectlySamples\n7               <NA>            CoverOf\n8               2004          InStyleOf\n9               <NA>            CoverOf\n10              2003          InStyleOf\n11              <NA>            CoverOf\n12              <NA> LyricalReferenceTo\n13              2015 LyricalReferenceTo\n14              <NA>   InterpolatesFrom\n15              <NA>          InStyleOf\n16              <NA>            CoverOf\n17              <NA>          InStyleOf\n18              <NA>          InStyleOf\n19              2017   InterpolatesFrom\n20              2023 LyricalReferenceTo\n21              <NA>          InStyleOf\n22              <NA>          InStyleOf\n23              <NA>   InterpolatesFrom\n24              <NA>          InStyleOf\n25              2020    DirectlySamples\n26              <NA>            CoverOf\n```\n\n\n:::\n:::\n\n\n\nAnd next we are going to add the time dimension with the influnce.\n\nConstruct edges_time_ready data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_time_ready <- edges_2nd_full %>%\n  mutate(\n    from_release_date = as.numeric(from_release_date),\n    to_release_date = as.numeric(to_release_date)\n  ) %>%\n  filter(!is.na(from_release_date) & !is.na(to_release_date)) %>%\n  mutate(\n    influencer_point = to,\n    sailor_point = from,\n    work_label = paste0(from, \" (Sailor)\"),\n    y_axis_label = paste0(from, \" (Sailor)\")  # 固定 Y 轴标签\n  ) %>%\n  tidyr::pivot_longer(\n    cols = c(to_release_date, from_release_date),\n    names_to = \"timepoint\",\n    values_to = \"year\"\n  ) %>%\n  mutate(\n    point_type = ifelse(timepoint == \"from_release_date\", \"Sailor\", \"Influencer\"),\n    label = ifelse(point_type == \"Sailor\", from, to),\n    label_display = ifelse(point_type == \"Sailor\", paste0(label, \" (Sailor)\"), label),\n    genre = ifelse(point_type == \"Sailor\", from_genre, to_genre),\n    notable = ifelse(point_type == \"Sailor\", from_notable, to_notable)\n  )\n\np <- ggplot(edges_time_ready, aes(x = year, y = y_axis_label, group = paste(from, to))) +\n  geom_line(\n    aes(text = paste(\"Influence:\", to, \"→\", from)),\n    color = \"grey40\", linewidth = 0.4, alpha = 0.6\n  ) +\n  geom_point(\n    aes(\n      text = paste0(\n        \"Year: \", year,\n        \"<br>Work: \", label_display,\n        \"<br>Type: \", point_type,\n        \"<br>Genre: \", genre,\n        \"<br>Notable: \", ifelse(notable == TRUE, \"Yes\", \"No\"),\n        \"<br>Edge Type: \", `Edge Type`\n      ),\n      color = point_type\n    ),\n    size = 1.8, alpha = 0.9\n  ) +\n  scale_color_manual(values = c(\"Influencer\" = \"#1F78B4\", \"Sailor\" = \"#E41A1C\")) +\n  labs(\n    title = \"Influence Timeline of Sailor Shift's Works\",\n    subtitle = \"Lines point to Sailor's works (fixed y-axis)\",\n    x = \"Release Year\", y = \"Sailor's Work\", color = \"Point Type\"\n  ) +\n  scale_x_continuous(breaks = pretty(edges_time_ready$year, n = 10)) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_text(size = 7),\n    plot.title = element_text(face = \"bold\"),\n    panel.grid.minor = element_blank(),\n    legend.position = \"bottom\"\n  )\n\ninteractive_plot <- plotly::ggplotly(p, tooltip = \"text\")\ninteractive_plot\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-5033ac683003777276d3\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5033ac683003777276d3\">{\"x\":{\"data\":[{\"x\":[2017,2034,null,2010,2034,null,2003,2034,null,2004,2030,null,2022,2028,null,2026,2028,null,2020,2038,null,1983,2038,null,2031,2036,null,2023,2036,null,2004,2028,null,2007,2033,null,2017,2034,null,2023,2034,null,2015,2038,null,2010,2038,null,2028,2032,null,2030,2030,null,2004,2030,null,2020,2038,null,2000,2038,null,2017,2024,null,2017,2024,null,2023,2029,null,2023,2029,null,2023,2031],\"y\":[1,1,null,2,2,null,2,2,null,3,3,null,4,4,null,4,4,null,5,5,null,5,5,null,6,6,null,6,6,null,7,7,null,8,8,null,9,9,null,9,9,null,10,10,null,10,10,null,11,11,null,12,12,null,12,12,null,13,13,null,13,13,null,14,14,null,14,14,null,15,15,null,15,15,null,16,16],\"text\":[\"Influence: Our Inevitable Path → Barnacle Heart\",\"Influence: Our Inevitable Path → Barnacle Heart\",null,\"Influence: Harvest Dance at Ler Valley → Coral Beats\",\"Influence: Harvest Dance at Ler Valley → Coral Beats\",null,\"Influence: Sacred Fragments → Coral Beats\",\"Influence: Sacred Fragments → Coral Beats\",null,\"Influence: Echoes of Forgotten Light → Driftwood Lullaby\",\"Influence: Echoes of Forgotten Light → Driftwood Lullaby\",null,\"Influence: The Crown We Wear → Electric Eel Love\",\"Influence: The Crown We Wear → Electric Eel Love\",null,\"Influence: Twelve Bells of Augsburg → Electric Eel Love\",\"Influence: Twelve Bells of Augsburg → Electric Eel Love\",null,\"Influence: Folklore's Heartbeat → Electric Reverie\",\"Influence: Folklore's Heartbeat → Electric Reverie\",null,\"Influence: Reflejo Interior → Electric Reverie\",\"Influence: Reflejo Interior → Electric Reverie\",null,\"Influence: Coastal Whispers of Biscay → Fog & Fiddle\",\"Influence: Coastal Whispers of Biscay → Fog & Fiddle\",null,\"Influence: Provence Aria → Fog & Fiddle\",\"Influence: Provence Aria → Fog & Fiddle\",null,\"Influence: Addicted to Your Heartache → High Tide Heartbeat\",\"Influence: Addicted to Your Heartache → High Tide Heartbeat\",null,\"Influence: Twilight's Threshold → Melancholy Circuitry\",\"Influence: Twilight's Threshold → Melancholy Circuitry\",null,\"Influence: Divergent Memories → Moon Over the Tide\",\"Influence: Divergent Memories → Moon Over the Tide\",null,\"Influence: Silent Steps in the Forest's Embrace → Moon Over the Tide\",\"Influence: Silent Steps in the Forest's Embrace → Moon Over the Tide\",null,\"Influence: Altitude of Mistakes → Oceanbound\",\"Influence: Altitude of Mistakes → Oceanbound\",null,\"Influence: Bold Without Apology → Oceanbound\",\"Influence: Bold Without Apology → Oceanbound\",null,\"Influence: Parallel Memories → Saltwater Hymn\",\"Influence: Parallel Memories → Saltwater Hymn\",null,\"Influence: Partisan's Lament → Salty Dreams\",\"Influence: Partisan's Lament → Salty Dreams\",null,\"Influence: Susurros de Pasión → Salty Dreams\",\"Influence: Susurros de Pasión → Salty Dreams\",null,\"Influence: Exoskeleton Dissolve → Stormsong\",\"Influence: Exoskeleton Dissolve → Stormsong\",null,\"Influence: When the Bar Lights Go Up → Stormsong\",\"Influence: When the Bar Lights Go Up → Stormsong\",null,\"Influence: Für uns alle zusammen → The Kelp Forest Canticles\",\"Influence: Für uns alle zusammen → The Kelp Forest Canticles\",null,\"Influence: Hallowed Transaction → The Kelp Forest Canticles\",\"Influence: Hallowed Transaction → The Kelp Forest Canticles\",null,\"Influence: The Long Way Home → Tides of Echos\",\"Influence: The Long Way Home → Tides of Echos\",null,\"Influence: Weathered Miles → Tides of Echos\",\"Influence: Weathered Miles → Tides of Echos\",null,\"Influence: Dreamscape of Judgment → Tidesworn Ballads\",\"Influence: Dreamscape of Judgment → Tidesworn Ballads\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.5118110236220474,\"color\":\"rgba(102,102,102,0.6)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2007,1983,2020,2023,2023,2017,2017,2004,2030,2003,2010,2010,2015,2004,2026,2022,2004,2028,2017,2023,2017,2023,2031,2000,2020,2023],\"y\":[8,5,5,15,15,14,14,12,12,2,2,10,10,7,4,4,3,11,9,9,1,6,6,13,13,16],\"text\":[\"Year: 2007<br>Work: Twilight's Threshold<br>Type: Influencer<br>Genre: Synthwave<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 1983<br>Work: Reflejo Interior<br>Type: Influencer<br>Genre: Americana<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2020<br>Work: Folklore's Heartbeat<br>Type: Influencer<br>Genre: Blues Rock<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2023<br>Work: The Long Way Home<br>Type: Influencer<br>Genre: Dream Pop<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2023<br>Work: Weathered Miles<br>Type: Influencer<br>Genre: Doom Metal<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2017<br>Work: Hallowed Transaction<br>Type: Influencer<br>Genre: Doom Metal<br>Notable: Yes<br>Edge Type: DirectlySamples\",\"Year: 2017<br>Work: Für uns alle zusammen<br>Type: Influencer<br>Genre: Alternative Rock<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2004<br>Work: Susurros de Pasión<br>Type: Influencer<br>Genre: Synthwave<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2030<br>Work: Partisan's Lament<br>Type: Influencer<br>Genre: Indie Pop<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2003<br>Work: Sacred Fragments<br>Type: Influencer<br>Genre: Synthwave<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2010<br>Work: Harvest Dance at Ler Valley<br>Type: Influencer<br>Genre: Psychedelic Rock<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2010<br>Work: Bold Without Apology<br>Type: Influencer<br>Genre: Indie Rock<br>Notable: Yes<br>Edge Type: LyricalReferenceTo\",\"Year: 2015<br>Work: Altitude of Mistakes<br>Type: Influencer<br>Genre: Americana<br>Notable: Yes<br>Edge Type: LyricalReferenceTo\",\"Year: 2004<br>Work: Addicted to Your Heartache<br>Type: Influencer<br>Genre: Southern Gothic Rock<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2026<br>Work: Twelve Bells of Augsburg<br>Type: Influencer<br>Genre: Psychedelic Rock<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2022<br>Work: The Crown We Wear<br>Type: Influencer<br>Genre: Indie Rock<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2004<br>Work: Echoes of Forgotten Light<br>Type: Influencer<br>Genre: Alternative Rock<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2028<br>Work: Parallel Memories<br>Type: Influencer<br>Genre: Dream Pop<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2017<br>Work: Divergent Memories<br>Type: Influencer<br>Genre: Indie Folk<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2023<br>Work: Silent Steps in the Forest's Embrace<br>Type: Influencer<br>Genre: Avant-Garde Folk<br>Notable: Yes<br>Edge Type: LyricalReferenceTo\",\"Year: 2017<br>Work: Our Inevitable Path<br>Type: Influencer<br>Genre: Indie Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2023<br>Work: Provence Aria<br>Type: Influencer<br>Genre: Indie Rock<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2031<br>Work: Coastal Whispers of Biscay<br>Type: Influencer<br>Genre: Alternative Rock<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2000<br>Work: When the Bar Lights Go Up<br>Type: Influencer<br>Genre: Emo/Pop Punk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2020<br>Work: Exoskeleton Dissolve<br>Type: Influencer<br>Genre: Indie Rock<br>Notable: Yes<br>Edge Type: DirectlySamples\",\"Year: 2023<br>Work: Dreamscape of Judgment<br>Type: Influencer<br>Genre: Symphonic Metal<br>Notable: Yes<br>Edge Type: CoverOf\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(31,120,180,1)\",\"opacity\":0.90000000000000002,\"size\":6.8031496062992138,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(31,120,180,1)\"}},\"hoveron\":\"points\",\"name\":\"Influencer\",\"legendgroup\":\"Influencer\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2033,2038,2038,2029,2029,2024,2024,2030,2030,2034,2034,2038,2038,2028,2028,2028,2030,2032,2034,2034,2034,2036,2036,2038,2038,2031],\"y\":[8,5,5,15,15,14,14,12,12,2,2,10,10,7,4,4,3,11,9,9,1,6,6,13,13,16],\"text\":[\"Year: 2033<br>Work: Melancholy Circuitry (Sailor)<br>Type: Sailor<br>Genre: Americana<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2038<br>Work: Electric Reverie (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2038<br>Work: Electric Reverie (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2029<br>Work: Tides of Echos (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2029<br>Work: Tides of Echos (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2024<br>Work: The Kelp Forest Canticles (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: DirectlySamples\",\"Year: 2024<br>Work: The Kelp Forest Canticles (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2030<br>Work: Salty Dreams (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2030<br>Work: Salty Dreams (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2034<br>Work: Coral Beats (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2034<br>Work: Coral Beats (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2038<br>Work: Oceanbound (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: LyricalReferenceTo\",\"Year: 2038<br>Work: Oceanbound (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: LyricalReferenceTo\",\"Year: 2028<br>Work: High Tide Heartbeat (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: No<br>Edge Type: InterpolatesFrom\",\"Year: 2028<br>Work: Electric Eel Love (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2028<br>Work: Electric Eel Love (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: CoverOf\",\"Year: 2030<br>Work: Driftwood Lullaby (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: No<br>Edge Type: InStyleOf\",\"Year: 2032<br>Work: Saltwater Hymn (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: No<br>Edge Type: InStyleOf\",\"Year: 2034<br>Work: Moon Over the Tide (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2034<br>Work: Moon Over the Tide (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: LyricalReferenceTo\",\"Year: 2034<br>Work: Barnacle Heart (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: No<br>Edge Type: InStyleOf\",\"Year: 2036<br>Work: Fog & Fiddle (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2036<br>Work: Fog & Fiddle (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InterpolatesFrom\",\"Year: 2038<br>Work: Stormsong (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: InStyleOf\",\"Year: 2038<br>Work: Stormsong (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: DirectlySamples\",\"Year: 2031<br>Work: Tidesworn Ballads (Sailor)<br>Type: Sailor<br>Genre: Oceanus Folk<br>Notable: Yes<br>Edge Type: CoverOf\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(228,26,28,1)\",\"opacity\":0.90000000000000002,\"size\":6.8031496062992138,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(228,26,28,1)\"}},\"hoveron\":\"points\",\"name\":\"Sailor\",\"legendgroup\":\"Sailor\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":43.762557077625573,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":183.64466583644668},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"<b> Influence Timeline of Sailor Shift's Works <\\/b>\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[1980.25,2040.75],\"tickmode\":\"array\",\"ticktext\":[\"1985\",\"1990\",\"1995\",\"2000\",\"2005\",\"2010\",\"2015\",\"2020\",\"2025\",\"2030\",\"2035\",\"2040\"],\"tickvals\":[1985,1990,1995,2000,2005,2010,2015,2020,2025,2030,2035,2040],\"categoryorder\":\"array\",\"categoryarray\":[\"1985\",\"1990\",\"1995\",\"2000\",\"2005\",\"2010\",\"2015\",\"2020\",\"2025\",\"2030\",\"2035\",\"2040\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Release Year\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,16.600000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Barnacle Heart (Sailor)\",\"Coral Beats (Sailor)\",\"Driftwood Lullaby (Sailor)\",\"Electric Eel Love (Sailor)\",\"Electric Reverie (Sailor)\",\"Fog & Fiddle (Sailor)\",\"High Tide Heartbeat (Sailor)\",\"Melancholy Circuitry (Sailor)\",\"Moon Over the Tide (Sailor)\",\"Oceanbound (Sailor)\",\"Saltwater Hymn (Sailor)\",\"Salty Dreams (Sailor)\",\"Stormsong (Sailor)\",\"The Kelp Forest Canticles (Sailor)\",\"Tides of Echos (Sailor)\",\"Tidesworn Ballads (Sailor)\"],\"tickvals\":[1,2,3.0000000000000004,4,5,6,7,8,9,10,11,12,13,14,15,16],\"categoryorder\":\"array\",\"categoryarray\":[\"Barnacle Heart (Sailor)\",\"Coral Beats (Sailor)\",\"Driftwood Lullaby (Sailor)\",\"Electric Eel Love (Sailor)\",\"Electric Reverie (Sailor)\",\"Fog & Fiddle (Sailor)\",\"High Tide Heartbeat (Sailor)\",\"Melancholy Circuitry (Sailor)\",\"Moon Over the Tide (Sailor)\",\"Oceanbound (Sailor)\",\"Saltwater Hymn (Sailor)\",\"Salty Dreams (Sailor)\",\"Stormsong (Sailor)\",\"The Kelp Forest Canticles (Sailor)\",\"Tides of Echos (Sailor)\",\"Tidesworn Ballads (Sailor)\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":9.2984640929846432},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Sailor's Work\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Point Type\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"b7e51adba3ff\":{\"x\":{},\"y\":{},\"text\":{},\"type\":\"scatter\"},\"b7e549ebc81f\":{\"x\":{},\"y\":{},\"text\":{},\"colour\":{}}},\"cur_data\":\"b7e51adba3ff\",\"visdat\":{\"b7e51adba3ff\":[\"function (y) \",\"x\"],\"b7e549ebc81f\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: callout-note\n## When was she influenced, by whom, and in what way?\n\nTiming and Type of Influence\n\n-   Sailor Shift’s compositions were inspired by a wide temporal range of influencer works from the 1980s to the 2020s.\n\n-   Notable classics that shaped her music include:\n\n    Reflejo Interior (1983, Americana) → Influenced *Electric Reverie*\n\n    Twilight’s Threshold (2007, Synthwave) → Influenced *Tides of Echos*\n\n    Hallowed Transaction (2017, Doom Metal) and *Divergent Memories (2017, Indie Folk)* → Contributed to her emerging Indie and Metal sounds\n\n-   From a genre perspective, Sailor draws from Synthwave, Doom Metal, Dream Pop, Indie Rock, and Psychedelic Rock, blending them into her distinctive Oceanus Folk style.\n\nTime Distribution & Creative Rhythm\n\n-   2015–2020 marks the *starting phase of stylistic absorption*.\\\n\n    Songs like *Melancholy Circuitry* and *Stormsong* show early influence connections — indicating the onset of external musical borrowing.\n\n-   2023–2035 is her most active creative and stylistic integration period.\\\n\n    The visualization shows a dense cluster of red points (Sailor’s works) and blue points (influencer works), suggesting heavy external inspiration and high creative output during this time.\n\nCreative Maturity vs. Density of Inspiration\n\n-   Songs such as:\n\n    *Tidesworn Ballads*, *Coral Beats*, *Driftwood Lullaby*, *Electric Reverie*\\\n\n    are influenced by multiple sources — identifying them as \"convergent inspiration\" pieces reflecting diverse stylistic integration.\n\n-   Data also reveals:\n\n    Most of Sailor’s songs are of the Oceanus Folk genre, while the influencers span Synthwave, Southern Gothic, Indie Pop, Symphonic Metal, and more.\n\n    Her most notable works (marked as `Notable = TRUE`) tend to be those that were heavily influenced — indicating that *inspiration led to impact*.\n:::\n\nView the “person → work” relationships that influence second-level works\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges_people_to_2nd_tbl <- edges_people_to_2nd %>%\n  left_join(nodes_tbl %>% select(index, name), by = c(\"from\" = \"index\")) %>%\n  rename(`Person Name` = name) %>%\n  left_join(nodes_tbl %>% select(index, name), by = c(\"to\" = \"index\")) %>%\n  rename(`Work Name` = name) %>%\n  select(`Person Name`, `Work Name`, `Edge Type`, `From Node Type`, `To Node Type`, release_date)\n\nedges_people_to_2nd_tbl\n```\n:::\n\n\n\nHere are the final plot that she has been influenced directly and indirectly.\n\nFirst layer: only keep what Sailor Shift points to: (indirectly, who is affected by the following)\n\nSongs and albums (these must also be spread in the second layer)\n\nBands and companies (no need to continue to spread)\n\nSecond layer: keep all \"works with affected people\" Third layer: connect the creators, producers, etc. of the second layer works\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(visNetwork)\n\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\nsailor_index <- nodes_tbl %>%\n  filter(name == \"Sailor Shift\") %>%\n  pull(index)\n\nedges_from_sailor <- edges_tbl %>%\n  filter(from == sailor_index)\n\nfirst_layer_info <- edges_from_sailor %>%\n  inner_join(nodes_tbl, by = c(\"to\" = \"index\")) %>%\n  filter(`Node Type` %in% c(\"Song\", \"Album\", \"MusicalGroup\", \"RecordLabel\"))\n\nfirst_layer_targets <- first_layer_info$to\n\ninfluence_edges <- c(\"InStyleOf\", \"LyricalReferenceTo\", \"InterpolatesFrom\", \"CoverOf\", \"DirectlySamples\")\n\nedges_2nd <- edges_tbl %>%\n  filter(from %in% first_layer_targets & `Edge Type` %in% influence_edges)\n\ninfluenced_works <- edges_2nd$to\nsongs_with_outgoing <- unique(edges_2nd$from)\n\nperson_edge_types <- c(\"PerformerOf\", \"ComposerOf\", \"LyricistOf\", \"ProducerOf\")\n\nedges_people_to_2nd <- edges_tbl %>%\n  filter(\n    to %in% influenced_works,\n    `Edge Type` %in% person_edge_types\n  ) %>%\n  left_join(nodes_tbl %>% select(index, `Node Type`), by = c(\"from\" = \"index\")) %>%\n  rename(`From Node Type` = `Node Type`) %>%\n  filter(`From Node Type` %in% c(\"Person\", \"RecordLabel\")) %>%\n  left_join(nodes_tbl %>% select(index, `Node Type`, release_date), by = c(\"to\" = \"index\")) %>%\n  rename(`To Node Type` = `Node Type`, release_date = release_date)\n\nfirst_layer_filtered <- first_layer_info %>%\n  filter(\n    (`Node Type` %in% c(\"Song\", \"Album\") & to %in% songs_with_outgoing) |\n    (`Node Type` %in% c(\"MusicalGroup\", \"RecordLabel\"))\n  )\n\nedges_from_sailor_filtered <- edges_from_sailor %>%\n  semi_join(first_layer_filtered, by = c(\"to\" = \"to\"))\n\nall_edges <- bind_rows(\n  edges_from_sailor_filtered,\n  edges_2nd,\n  edges_people_to_2nd %>% rename(from = from, to = to)\n)\n\nnode_ids <- unique(c(all_edges$from, all_edges$to))\n\nnodes_subgraph <- nodes_tbl %>%\n  filter(index %in% node_ids) %>%\n  transmute(\n    id = index,\n    label = name,\n    group = `Node Type`\n  )\n\nedges_subgraph <- all_edges %>%\n  transmute(\n    from = from,\n    to = to,\n    label = `Edge Type`,\n    title = paste0(\"Edge Type: \", `Edge Type`, \"<br>Release: \", release_date)\n  )\n\nvisNetwork(nodes_subgraph, edges_subgraph, width = \"100%\", height = \"700px\") %>%\n  visEdges(arrows = \"to\") %>%\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%\n  visLegend(useGroups = TRUE, position = \"right\") %>%\n  visLayout(randomSeed = 123)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-257cc8bf3361c857ede6\" style=\"width:100%;height:700px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-257cc8bf3361c857ede6\">{\"x\":{\"nodes\":{\"id\":[77,305,456,458,877,878,879,935,1277,1295,1336,1337,1953,2198,2199,2200,2201,2401,2706,2707,2708,3087,3761,3762,3764,3765,3882,3883,3884,3987,3988,3989,3990,3991,5214,5575,5576,6593,6594,7027,7028,7029,7030,7031,8027,8208,8209,8881,9224,9225,9226,9227,9228,9229,9849,10017,10018,10019,10020,10021,10022,10023,10535,10904,10905,10906,10907,10908,10909,11255,11256,12238,12239,12240,12241,12242,12686,12687,12688,12689,12949,13015,13016,13017,13018,13019,13590,13591,14108,14109,14297,14298,14299,14353,14354,14355,14356,14357,14358,14359,14360,14361,14362,14659,14894,14895,14896,14934,14935,14936,14937,14938,14939,15225,15856,15857,16032,16313,17000,17050,17168,17193,17232,17256,17261,17262,17274,17276,17278,17280,17281,17286,17287,17288,17290,17291,17293,17300,17315,17328,17351,17371,17395],\"label\":[\"Ming Ren\",\"Belinda Knappe\",\"Yang Peng\",\"Min Cao\",\"Bold Without Apology\",\"Qiang Zhou\",\"Jing Kang\",\"Jun Zhou\",\"Yong Dong\",\"Urszula Stochmal\",\"Ming Long\",\"Yong Lu\",\"Yang Wan\",\"Hallowed Transaction\",\"Yoko Hashimoto\",\"Kaori Ito\",\"Naoko Sato\",\"Yan Tang\",\"Jeremiah Love\",\"Zachary Francis\",\"Robert Woods\",\"Sean Jones\",\"Min Long\",\"Gang Shao\",\"Qiang Yuan\",\"Wei Zhao\",\"Susurros de Pasión\",\"Juan Zhou\",\"Yang Zhao\",\"Altitude of Mistakes\",\"Xiulan Fang\",\"Qiang Liu\",\"Jun Qiao\",\"Ming Huang\",\"Samantha Bullock\",\"Our Inevitable Path\",\"Shannon Harvey\",\"When the Bar Lights Go Up\",\"Lori Massey\",\"Reflejo Interior\",\"Sheryl Roman\",\"John Graves\",\"Jason Aguirre\",\"Matthew Lane\",\"Cipriano Peranda\",\"Echoes of Forgotten Light\",\"Igor Dyś\",\"Tao Gao\",\"Für uns alle zusammen\",\"Joseph Ponce\",\"Herbert Mcfarland\",\"Rachel Montes\",\"Caitlin Miller\",\"Rebecca Wise\",\"Partisan's Lament\",\"Dreamscape of Judgment\",\"Ping Liao\",\"Trevor Bass\",\"Xiuying Du\",\"Xia Yuan\",\"Sandra Burke\",\"Yan Li\",\"Twelve Bells of Augsburg\",\"Parallel Memories\",\"Ping Jin\",\"Tao Wen\",\"Guiying Ren\",\"Lei Shi\",\"Wei Liang\",\"Divergent Memories\",\"Joshua Taylor\",\"Provence Aria\",\"Lei Fu\",\"Yan Dai\",\"Daniel Mccormick\",\"Lei Jin\",\"Coastal Whispers of Biscay\",\"James Medina\",\"Matthew Best\",\"Linda Burns\",\"Brooke Olson\",\"Exoskeleton Dissolve\",\"David Reese\",\"Ryan Dunlap\",\"Elmo Calbo\",\"Amico Luciani\",\"Silent Steps in the Forest's Embrace\",\"Wei Zhao\",\"Folklore's Heartbeat\",\"Tao Hu\",\"The Long Way Home\",\"Ming Qiao\",\"Na Ye\",\"Weathered Miles\",\"Debra Graham\",\"Edward Evans\",\"Dylan Schwartz\",\"James Henderson\",\"Amy Powell\",\"Shawn Johnson\",\"Joel Long\",\"Michael Nixon\",\"Nathan Jones\",\"Addicted to Your Heartache\",\"Twilight's Threshold\",\"Kimberly Estrada\",\"Fang Ding\",\"The Crown We Wear\",\"Miss Jennifer Williams\",\"William Robinson\",\"Judy Yang\",\"Joanna Avery\",\"Molly Gonzalez\",\"Juan Shi\",\"Sacred Fragments\",\"Ming Zhou\",\"Simone Säuberlich\",\"Harvest Dance at Ler Valley\",\"Melancholy Circuitry\",\"Electric Reverie\",\"The Salty Wakes\",\"The Fiddle & The Fjord\",\"Tides of Echos\",\"Sailor Shift\",\"Ivy Echos\",\"The Kelp Forest Canticles\",\"Salty Dreams\",\"Coral Beats\",\"Oceanbound\",\"High Tide Heartbeat\",\"Electric Eel Love\",\"Driftwood Lullaby\",\"Saltwater Hymn\",\"Moon Over the Tide\",\"Barnacle Heart\",\"Fog & Fiddle\",\"Stormsong\",\"The Saltwater Weavers\",\"The Tide Singer's Knot\",\"Drowned Harbor\",\"Tidesworn Ballads\",\"Oceanic Records\",\"Oceanus Records\"],\"group\":[\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Album\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Song\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Song\",\"Person\",\"Album\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Album\",\"Song\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Song\",\"Person\",\"Person\",\"Song\",\"Album\",\"Album\",\"MusicalGroup\",\"MusicalGroup\",\"Album\",\"Person\",\"MusicalGroup\",\"Album\",\"Album\",\"Album\",\"Album\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"Song\",\"MusicalGroup\",\"MusicalGroup\",\"MusicalGroup\",\"Album\",\"RecordLabel\",\"RecordLabel\"]},\"edges\":{\"from\":[17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17256,17000,17050,17050,17232,17232,17261,17261,17261,17261,17262,17262,17274,17274,17276,17276,17278,17278,17280,17281,17281,17286,17287,17288,17288,17290,17291,17291,17293,17293,17351,77,305,456,456,458,878,879,879,935,1277,1295,1295,1295,1336,1336,1337,1953,2199,2200,2201,2201,2401,2706,2706,2707,2708,2708,3087,3761,3761,3762,3762,3764,3765,3883,3884,3988,3989,3989,3990,3991,5214,5576,5576,5576,6594,6594,7028,7029,7030,7031,8027,8209,8209,8881,8881,9225,9226,9227,9228,9229,10018,10019,10020,10021,10022,10023,10023,10905,10906,10906,10907,10908,10909,10909,11256,11256,11256,12239,12239,12240,12240,12241,12242,12687,12688,12688,12689,12949,13016,13017,13018,13019,13591,14109,14109,14298,14299,14299,14354,14354,14355,14356,14357,14358,14359,14360,14361,14361,14362,14895,14896,14935,14936,14936,14937,14938,14939,15225,15857,16032,16032,17371,17371,17395,17395],\"to\":[17000,17050,17232,17261,17261,17262,17274,17274,17276,17276,17278,17278,17280,17281,17286,17287,17288,17290,17291,17293,17300,17328,17193,17351,17351,14894,14108,7027,14353,14297,17168,17315,17300,17193,2198,9224,3882,9849,16313,15856,877,3987,14659,14934,10535,8208,10904,13590,11255,5575,12686,12238,13015,6593,10017,12238,16313,15856,15856,15856,877,877,877,3882,3987,14659,14659,14659,14894,14894,14894,15856,2198,2198,2198,2198,3987,10535,10535,10535,10535,10535,9849,3882,3882,3882,3882,3882,3882,3882,3882,3987,3987,3987,3987,3987,9849,5575,5575,5575,6593,6593,7027,7027,7027,7027,13015,8208,8208,13590,13590,9224,9224,9224,9224,9224,10017,10017,10017,10017,10017,10017,10017,10904,10904,10904,10904,10904,10904,10904,11255,11255,11255,12238,12238,12238,12238,12238,12238,12686,12686,12686,12686,14108,13015,13015,13015,13015,13590,14108,14108,14297,14297,14297,14353,14353,14353,14353,14353,14353,14353,14353,14353,14353,14353,14894,14894,14934,14934,14934,14934,14934,14934,15856,15856,16313,16313,17300,17315,17168,17193],\"label\":[\"LyricistOf\",\"LyricistOf\",\"LyricistOf\",\"MemberOf\",\"DirectlySamples\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"InStyleOf\",\"LyricalReferenceTo\",\"InStyleOf\",\"LyricistOf\",\"PerformerOf\",\"CoverOf\",\"InStyleOf\",\"InterpolatesFrom\",\"InterpolatesFrom\",\"InStyleOf\",\"InStyleOf\",\"InStyleOf\",\"LyricalReferenceTo\",\"InterpolatesFrom\",\"DirectlySamples\",\"CoverOf\",\"InStyleOf\",\"CoverOf\",\"CoverOf\",\"InStyleOf\",\"LyricalReferenceTo\",\"LyricalReferenceTo\",\"InterpolatesFrom\",\"CoverOf\",\"InStyleOf\",\"InStyleOf\",\"InStyleOf\",\"LyricalReferenceTo\",\"InterpolatesFrom\",\"InStyleOf\",\"InterpolatesFrom\",\"InStyleOf\",\"DirectlySamples\",\"InStyleOf\",\"CoverOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricistOf\",\"ComposerOf\",\"PerformerOf\",\"ProducerOf\",\"LyricistOf\",\"ComposerOf\",\"ProducerOf\",\"ComposerOf\",\"LyricistOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"ProducerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricistOf\",\"ComposerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"ProducerOf\",\"ComposerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricistOf\",\"ComposerOf\",\"PerformerOf\",\"ProducerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"ComposerOf\",\"ComposerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"ProducerOf\",\"ComposerOf\",\"PerformerOf\",\"LyricistOf\",\"PerformerOf\",\"PerformerOf\",\"ProducerOf\",\"ProducerOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"ProducerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"PerformerOf\",\"ComposerOf\",\"PerformerOf\",\"ProducerOf\",\"ProducerOf\",\"ProducerOf\",\"ProducerOf\"],\"title\":[\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: MemberOf<br>Release: NA\",\"Edge Type: DirectlySamples<br>Release: NA\",\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: LyricalReferenceTo<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: LyricistOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: NA\",\"Edge Type: CoverOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: InterpolatesFrom<br>Release: NA\",\"Edge Type: InterpolatesFrom<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: LyricalReferenceTo<br>Release: NA\",\"Edge Type: InterpolatesFrom<br>Release: NA\",\"Edge Type: DirectlySamples<br>Release: NA\",\"Edge Type: CoverOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: CoverOf<br>Release: NA\",\"Edge Type: CoverOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: LyricalReferenceTo<br>Release: NA\",\"Edge Type: LyricalReferenceTo<br>Release: NA\",\"Edge Type: InterpolatesFrom<br>Release: NA\",\"Edge Type: CoverOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: LyricalReferenceTo<br>Release: NA\",\"Edge Type: InterpolatesFrom<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: InterpolatesFrom<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: DirectlySamples<br>Release: NA\",\"Edge Type: InStyleOf<br>Release: NA\",\"Edge Type: CoverOf<br>Release: NA\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: ProducerOf<br>Release: 2010\",\"Edge Type: PerformerOf<br>Release: 2003\",\"Edge Type: ProducerOf<br>Release: 2003\",\"Edge Type: PerformerOf<br>Release: 2003\",\"Edge Type: ComposerOf<br>Release: 2010\",\"Edge Type: PerformerOf<br>Release: 2010\",\"Edge Type: ProducerOf<br>Release: 2010\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2015\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: LyricistOf<br>Release: 2004\",\"Edge Type: ComposerOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2007\",\"Edge Type: ProducerOf<br>Release: 2007\",\"Edge Type: LyricistOf<br>Release: 2007\",\"Edge Type: ComposerOf<br>Release: 2003\",\"Edge Type: ProducerOf<br>Release: 2017\",\"Edge Type: ComposerOf<br>Release: 2017\",\"Edge Type: LyricistOf<br>Release: 2017\",\"Edge Type: PerformerOf<br>Release: 2017\",\"Edge Type: ComposerOf<br>Release: 2015\",\"Edge Type: PerformerOf<br>Release: 2026\",\"Edge Type: ProducerOf<br>Release: 2026\",\"Edge Type: PerformerOf<br>Release: 2026\",\"Edge Type: LyricistOf<br>Release: 2026\",\"Edge Type: PerformerOf<br>Release: 2026\",\"Edge Type: ProducerOf<br>Release: 2030\",\"Edge Type: LyricistOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: LyricistOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: ProducerOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2015\",\"Edge Type: ComposerOf<br>Release: 2015\",\"Edge Type: PerformerOf<br>Release: 2015\",\"Edge Type: PerformerOf<br>Release: 2015\",\"Edge Type: PerformerOf<br>Release: 2015\",\"Edge Type: PerformerOf<br>Release: 2030\",\"Edge Type: PerformerOf<br>Release: 2017\",\"Edge Type: LyricistOf<br>Release: 2017\",\"Edge Type: ComposerOf<br>Release: 2017\",\"Edge Type: PerformerOf<br>Release: 2000\",\"Edge Type: LyricistOf<br>Release: 2000\",\"Edge Type: PerformerOf<br>Release: 1983\",\"Edge Type: ComposerOf<br>Release: 1983\",\"Edge Type: PerformerOf<br>Release: 1983\",\"Edge Type: ProducerOf<br>Release: 1983\",\"Edge Type: ComposerOf<br>Release: 2020\",\"Edge Type: PerformerOf<br>Release: 2004\",\"Edge Type: LyricistOf<br>Release: 2004\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: ProducerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2017\",\"Edge Type: PerformerOf<br>Release: 2017\",\"Edge Type: PerformerOf<br>Release: 2017\",\"Edge Type: LyricistOf<br>Release: 2017\",\"Edge Type: PerformerOf<br>Release: 2017\",\"Edge Type: LyricistOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: ComposerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: LyricistOf<br>Release: 2028\",\"Edge Type: PerformerOf<br>Release: 2028\",\"Edge Type: ProducerOf<br>Release: 2028\",\"Edge Type: PerformerOf<br>Release: 2028\",\"Edge Type: PerformerOf<br>Release: 2028\",\"Edge Type: ComposerOf<br>Release: 2028\",\"Edge Type: PerformerOf<br>Release: 2028\",\"Edge Type: PerformerOf<br>Release: 2017\",\"Edge Type: LyricistOf<br>Release: 2017\",\"Edge Type: ComposerOf<br>Release: 2017\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: ProducerOf<br>Release: 2023\",\"Edge Type: LyricistOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2031\",\"Edge Type: LyricistOf<br>Release: 2031\",\"Edge Type: PerformerOf<br>Release: 2031\",\"Edge Type: PerformerOf<br>Release: 2031\",\"Edge Type: PerformerOf<br>Release: 2020\",\"Edge Type: PerformerOf<br>Release: 2020\",\"Edge Type: PerformerOf<br>Release: 2020\",\"Edge Type: PerformerOf<br>Release: 2020\",\"Edge Type: PerformerOf<br>Release: 2020\",\"Edge Type: ComposerOf<br>Release: 2023\",\"Edge Type: ComposerOf<br>Release: 2020\",\"Edge Type: PerformerOf<br>Release: 2020\",\"Edge Type: LyricistOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: ProducerOf<br>Release: 2023\",\"Edge Type: ComposerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: LyricistOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: ProducerOf<br>Release: 2023\",\"Edge Type: ProducerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: ComposerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2023\",\"Edge Type: PerformerOf<br>Release: 2007\",\"Edge Type: PerformerOf<br>Release: 2007\",\"Edge Type: PerformerOf<br>Release: 2022\",\"Edge Type: PerformerOf<br>Release: 2022\",\"Edge Type: ProducerOf<br>Release: 2022\",\"Edge Type: PerformerOf<br>Release: 2022\",\"Edge Type: PerformerOf<br>Release: 2022\",\"Edge Type: PerformerOf<br>Release: 2022\",\"Edge Type: PerformerOf<br>Release: 2003\",\"Edge Type: PerformerOf<br>Release: 2003\",\"Edge Type: ComposerOf<br>Release: 2010\",\"Edge Type: PerformerOf<br>Release: 2010\",\"Edge Type: ProducerOf<br>Release: NA\",\"Edge Type: ProducerOf<br>Release: NA\",\"Edge Type: ProducerOf<br>Release: NA\",\"Edge Type: ProducerOf<br>Release: NA\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":\"to\"},\"layout\":{\"randomSeed\":123}},\"groups\":[\"Person\",\"Song\",\"Album\",\"MusicalGroup\",\"RecordLabel\"],\"width\":\"100%\",\"height\":\"700px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"right\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(visNetwork)\n\nnodes_tbl <- nodes_tbl %>% mutate(index = row_number())\n\nsailor_index <- nodes_tbl %>%\n  filter(name == \"Sailor Shift\") %>%\n  pull(index)\n\nedges_from_sailor <- edges_tbl %>%\n  filter(from == sailor_index)\n\nfirst_layer_info <- edges_from_sailor %>%\n  inner_join(nodes_tbl, by = c(\"to\" = \"index\")) %>%\n  filter(`Node Type` %in% c(\"Song\", \"Album\", \"MusicalGroup\", \"RecordLabel\"))\n\nfirst_layer_targets <- first_layer_info$to\n\ninfluence_edges <- c(\"InStyleOf\", \"LyricalReferenceTo\", \"InterpolatesFrom\", \"CoverOf\", \"DirectlySamples\")\n\nedges_2nd <- edges_tbl %>%\n  filter(from %in% first_layer_targets & `Edge Type` %in% influence_edges)\n\ninfluenced_works <- edges_2nd$to\nsongs_with_outgoing <- unique(edges_2nd$from) \n\nrelated_edge_types <- c(\"PerformerOf\", \"ComposerOf\", \"LyricistOf\", \"ProducerOf\",\n                        \"InStyleOf\", \"LyricalReferenceTo\", \"InterpolatesFrom\", \"CoverOf\", \"DirectlySamples\")\n\nedges_3rd <- edges_tbl %>%\n  filter(to %in% influenced_works & `Edge Type` %in% related_edge_types) %>%\n  left_join(nodes_tbl %>% select(index, `Node Type`), by = c(\"to\" = \"index\")) %>%\n  rename(to_type = `Node Type`) %>%\n  filter(\n    !(\n      (to_type == \"Song\" & `Edge Type` %in% c(\"PerformerOf\", \"LyricalReferenceTo\", \"InStyleOf\", \"InterpolatesFrom\")) |\n      (to_type == \"Album\" & `Edge Type` %in% c(\"InStyleOf\", \"CoverOf\", \"InterpolatesFrom\", \"LyricalReferenceTo\", \"DirectlySamples\")) |\n      (to_type == \"MusicalGroup\" & `Edge Type` %in% c(\"InStyleOf\", \"CoverOf\", \"InterpolatesFrom\", \"LyricalReferenceTo\", \"DirectlySamples\"))\n    )\n  )\n\n\nfirst_layer_filtered <- first_layer_info %>%\n  filter(\n    (`Node Type` %in% c(\"Song\", \"Album\") & to %in% songs_with_outgoing) |\n    (`Node Type` %in% c(\"MusicalGroup\", \"RecordLabel\"))\n  )\n\nedges_from_sailor_filtered <- edges_from_sailor %>%\n  semi_join(first_layer_filtered, by = c(\"to\" = \"to\"))\n\nall_edges <- bind_rows(\n  edges_from_sailor_filtered,\n  edges_2nd,\n  edges_3rd\n)\n\nused_ids <- unique(c(all_edges$from, all_edges$to))\n\nnodes_filtered <- nodes_tbl %>%\n  filter(index %in% used_ids) %>%\n  mutate(\n    id = index,\n    label = name,\n    group = `Node Type`,\n    size = case_when(\n      name == \"Sailor Shift\" ~ 30,\n      `Node Type` == \"Song\" ~ 20,\n      TRUE ~ 15\n    )\n  )\n\nedges_filtered <- all_edges %>%\n  rename(from = from, to = to, label = `Edge Type`) %>%\n  mutate(color = case_when(\n    label %in% influence_edges ~ \"orange\",\n    label %in% related_edge_types ~ \"red\",\n    TRUE ~ \"gray\"\n  ))\n\nvisNetwork(nodes_filtered, edges_filtered, height = \"800px\", width = \"100%\") %>%\n  visEdges(arrows = \"to\", color = edges_filtered$color) %>%\n  visOptions(\n    highlightNearest = list(enabled = TRUE, degree = 3, hover = TRUE),\n    nodesIdSelection = TRUE,\n    selectedBy = \"group\"\n  ) %>%\n  visLegend() %>%\n  visLayout(randomSeed = 1234) %>%\n  visInteraction(navigationButtons = TRUE)\n```\n:::\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/grViz-binding-1.0.11/grViz.js\"></script>\n<link href=\"../../site_libs/vis-9.1.0/vis-network.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/vis-9.1.0/vis-network.min.js\"></script>\n<script src=\"../../site_libs/visNetwork-binding-2.1.2/visNetwork.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}