project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise" 
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3A"
            href: "Hands-on_Ex/Hands_on_Ex03/Hands-on_Ex03A.html"
          - text: "Hands-on Exercise 3B"
            href: "Hands-on_Ex/Hands_on_Ex03/Hands-on_Ex03B.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04A.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04B.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04C.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04D.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 8A"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08A.html"
          - text: "Hands-on Exercise 8B"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08B.html"
          - text: "Hands-on Exercise 8C"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08C.html"
          - text: "Hands-on Exercise 9A"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09A.html"
          - text: "Hands-on Exercise 9B"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09B.html"
          - text: "Hands-on Exercise 9C"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09C.html"

      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 0"
            href:  https://public.tableau.com/app/profile/irene.yang2979/vizzes
          - text: "In-class Exercise 2"
            href:  https://public.tableau.com/app/profile/irene.yang2979/vizzes
          - text: "In-class Exercise 3"
            href:  https://public.tableau.com/app/profile/irene.yang2979/vizzes
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex4/In-class_Ex4.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex5/In-class_Ex5.html"
          - text: "In-class Exercise 6"
            href: "In-class_EX/In-class_EX06/In-class_EX06.html"
          - text: "In-class Exercise 7"
            href: "In-class_EX/In-class_EX07/In-class_EX07.html"
          - text: "In-class Exercise 8"
            href: "In-class_EX/In-class_EX08/In-class_EX08.html"
          - text: "In-class Exercise 9"
            href: "In-class_EX/In-class_EX09/In-class_EX09.html"
          - text: "In-class Exercise 10"
            href: "In-class_EX/In-class_EX10/In-class_EX10.html"

      - text: "Take-home Exercise"
        menu:
          - text: "Take home exercise 1A"
            href: "Take-home_Exercise/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take home exercise 1B"
            href: "Take-home_Exercise/Take-home_Ex01/Take-home_Ex01B.html"
          - text: "Take home exercise 2"
            href: "Take-home_Exercise/Take-home_Ex02/Take-home_Ex02.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: "index.html"
      - section: "Hands-on Exercise"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        contents:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3A"
            href: "Hands-on_Ex/Hands_on_Ex03/Hands-on_Ex03A.html"
          - text: "Hands-on Exercise 3B"
            href: "Hands-on_Ex/Hands_on_Ex03/Hands-on_Ex03B.html"
          - text: "Hands-on Exercise 4A"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04A.html"
          - text: "Hands-on Exercise 4B"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04B.html"
          - text: "Hands-on Exercise 4C"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04C.html"
          - text: "Hands-on Exercise 4D"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04C.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 8A"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08A.html"
          - text: "Hands-on Exercise 8B"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08B.html"
          - text: "Hands-on Exercise 8C"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08C.html"  
          
      - text: "In-class Exercise"
        href: https://public.tableau.com/app/profile/irene.yang2979/vizzes
      - section: "Take-home Exercise"
        href: "Take-home_Exercise/Take-home_Ex01/Take-home_Ex01.html"
        contents:
          - text: "Take-home Exercise 1A"
            href: "Take-home_Exercise/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 1B"
            href: "Take-home_Exercise/Take-home_Ex01/Take-home_Ex01B.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Exercise/Take-home_Ex02/Take-home_Ex02.html"
          
format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual

